import {chromium} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {createTransportAdapter} from '../server/adapter.js';
import {LIVE_STATIONS} from '../src/live-data.js';

const base=process.env.TEST_BASE_URL??'http://localhost:4173/replay.html',output=process.env.CAPTURE_DIR??'test-results/phase1';
await mkdir(output,{recursive:true});
const initial=Date.parse('2026-09-18T12:05:00Z');
const adapter=createTransportAdapter({clock:()=>initial,fetcher:async url=>Response.json(url.includes('TrainServiceAlerts')?{value:{Status:1,Message:[{Content:'Synthetic advisory <img src=x onerror=bad()>',CreatedDate:'2026-09-18 20:00:00'}],AffectedSegments:[{Line:'EWL',Stations:'EW8,EW9',Direction:'Both'},{Line:'NSL',Stations:'NS13',Direction:'Both'}]}}:{value:LIVE_STATIONS.filter(s=>s.line===new URL(url).searchParams.get('TrainLine')).map(s=>({Station:s.code,StartTime:'2026-09-18T20:00:00+08:00',EndTime:'2026-09-18T20:10:00+08:00',CrowdLevel:'l'}))})});
let fixture=await adapter({LTA_ACCOUNT_KEY:'synthetic-browser-only'}),mode='valid';
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'allow'});
const page=await context.newPage(),errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));
const check=(name,okay)=>{assert.ok(okay,name);results.push({name,status:'PASS'});console.log('PASS '+name);};
await page.clock.install({time:new Date(initial)});
await page.route('**/api/status',async route=>{
  if(mode==='failure')return route.abort('failed');
  if(mode==='malformed')return route.fulfill({json:{schemaVersion:1,notices:{items:{}},crowding:{lines:[]}}});
  return route.fulfill({json:fixture});
});
const refresh=async()=>{await page.locator('#refresh-live').click();await page.waitForTimeout(60);};
const ew2=()=>page.locator('[data-station-code="EW2"]');
const scenario=async name=>{await page.getByRole('button',{name:'Demo controls'}).click();await page.getByRole('button',{name}).click();};
try{
  await page.goto(base);await page.locator('.station-report.current').first().waitFor({state:'attached'});
  await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
  check('19 exact line-specific station reports rendered',await page.locator('.station-report.current').count()===19);
  check('live panel and replay arrival visibly distinct',await page.locator('.arrival').innerText()==='08:41'&&(await page.locator('.live-boundary').innerText()).includes('replay calculations'));
  check('normal status includes minor delays, not a corridor all-clear',await page.locator('#live-panel').innerText().then(t=>t.includes('minor delays')&&t.includes('not a corridor all-clear')));
  check('relevant segment retained, irrelevant segment counted but omitted',await page.locator('.notice-segments').innerText().then(t=>t.includes('EW8')&&!t.includes('NS13'))&&(await page.locator('#live-panel').innerText()).includes('outside this corridor omitted'));
  await page.locator('.live-advisories summary').click();check('message provenance and unsafe text escaped',await page.locator('.live-advisories').innerText().then(t=>t.includes('timezone or format unconfirmed'))&&await page.locator('.live-advisories img').count()===0);
  await page.locator('.crowd-line summary').first().click();await page.locator('#save').click();
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('commute-copilot-journey-v1')));
  check('saved source interval and retrieval are separate from replay timestamp',saved.liveFeed.crowding.lines[0].records[0].endTime==='2026-09-18T20:10:00+08:00'&&saved.liveFeed.crowding.lines[0].retrievedAt&&saved.liveFeed.clientReceivedAt);
  await page.locator('.crowd-line summary').first().click();
  check('live panel fits mobile viewport',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.clock.fastForward(6*60000);await page.waitForFunction(()=>document.querySelector('[data-station-code="EW2"]').dataset.freshness==='expired');
  check('interval expires without a successful new observation',await page.locator('.station-report.current').count()===0&&(await ew2().innerText()).includes('Expired'));
  fixture.checkedAt='2026-09-18T20:11:00+08:00';for(const line of fixture.crowding.lines)line.retrievedAt=fixture.checkedAt;await refresh();
  check('refetching expired interval does not renew freshness',await page.locator('.station-report.current').count()===0);
  fixture.crowding.lines[0].records[0].startTime='2026-09-18T20:12:00+08:00';fixture.crowding.lines[0].records[0].endTime='2026-09-18T20:22:00+08:00';await refresh();
  check('future interval is unavailable',await ew2().innerText().then(t=>t.includes('Future interval')));
  await page.clock.fastForward(2*60000);check('future report cannot become observed merely as clock advances',await ew2().innerText().then(t=>t.includes('Source timing unconfirmed')));
  fixture.crowding.lines[0].records[0].startTime=null;await refresh();check('missing source timestamp stays unknown',await ew2().innerText().then(t=>t.includes('Unknown')));
  fixture.crowding.lines[0].records[0].startTime='2026-09-18T20:00:00+08:00';fixture.crowding.lines[0].records[0].endTime='2026-09-18T20:10:00+08:00';await refresh();
  await scenario('Disruption during travel');await page.locator('#primary-action').click();await page.locator('[data-accept="circle"]').click();
  check('live states do not change replay disruption reroute',await page.locator('.arrival').innerText()==='08:59');
  await page.locator('#save').click();const beforeOffline=await page.evaluate(()=>JSON.parse(localStorage.getItem('commute-copilot-journey-v1')));
  await context.setOffline(true);await page.reload();await page.locator('.data-bar.offline').waitFor();
  await page.locator('.crowd-line summary').first().click();
  check('actual offline reload preserves live-source metadata and expired state',await ew2().innerText().then(t=>t.includes('Expired')&&t.includes('20:10:00')));
  check('actual offline reload preserves selected guidance',await page.locator('.arrival').innerText()==='08:59'&&(await page.locator('.steps').innerText()).includes('Circle Line'));
  check('offline UI never claims a current live observation',await page.locator('.station-report.current').count()===0&&(await page.locator('#live-panel').innerText()).includes('Offline'));
  await context.setOffline(false);await page.locator('.data-bar:not(.offline)').waitFor();
  check('reconnection preserves chosen replay route',await page.locator('.arrival').innerText()==='08:59');
  mode='failure';await refresh();check('client network failure preserves last known provenance',await page.locator('#live-panel').innerText().then(t=>t.includes('Connection failed')));
  mode='malformed';await refresh();check('malformed application response preserves useful guidance',await page.locator('.arrival').innerText()==='08:59'&&await ew2().count()===1);
  mode='valid';fixture.crowding.lines[1]={...fixture.crowding.lines[1],status:'unavailable',error:'rate_limited'};await refresh();
  await page.locator('.crowd-line summary').nth(1).click();
  check('partial feed failure has an explicit source error',await page.locator('#live-panel').innerText().then(t=>t.includes('rate limit reached')));
  await page.locator('#save').click();const after=await page.evaluate(()=>JSON.parse(localStorage.getItem('commute-copilot-journey-v1')));
  check('live refresh does not mutate full saved replay routes',JSON.stringify(after.routes)===JSON.stringify(beforeOffline.routes)&&after.selected===beforeOffline.selected);
  await page.setViewportSize({width:320,height:740});await page.evaluate(()=>document.documentElement.style.fontSize='200%');
  check('live information remains within viewport at 200 percent text',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.evaluate(()=>document.documentElement.style.fontSize='');await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:`${output}/live-corridor-mobile.png`,fullPage:true});
  check('no live-UI JavaScript errors',errors.length===0);
  await writeFile(`${output}/live-browser-results.json`,JSON.stringify({timestamp:new Date().toISOString(),mode:'synthetic-contract-browser',emulationOnly:true,actualNetworkOfflineReload:true,browser:browser.version(),results,errors},null,2));
  console.log(`PASS ${results.length} live UI browser checks (synthetic feeds).`);
}catch(error){await page.screenshot({path:`${output}/live-browser-failure.png`,fullPage:true});await writeFile(`${output}/live-browser-failure.json`,JSON.stringify({message:error.message,results,errors},null,2));throw error;}
finally{await browser.close();}
