import test from 'node:test';
import assert from 'node:assert/strict';
import {createLocationAssistance,locationDescription} from '../src/location-assistance.js';
import {createOfflineReadiness,requestShellReadiness} from '../src/offline-readiness.js';

function locationHarness(){let visible=true,sequence=0;const callbacks=[],cleared=[],positions=[],states=[];const geolocation={watchPosition(success,failure){callbacks.push({success,failure});return ++sequence;},clearWatch:id=>cleared.push(id)};const controller=createLocationAssistance({geolocation,isVisible:()=>visible,now:()=>1000000,onPosition:p=>positions.push(p),onState:s=>states.push(s)});return {controller,callbacks,cleared,positions,states,visible:value=>{visible=value;controller.visibilityChanged();},fix:(index=0,overrides={})=>callbacks[index].success({coords:{latitude:1.3,longitude:103.8,accuracy:30,...overrides.coords},timestamp:overrides.timestamp??1000000})};}
test('app load requests local assistance before a journey without caregiver consent or internet',async()=>{const h=locationHarness();assert.equal(h.callbacks.length,0);await h.controller.boot();h.fix();assert.equal(h.positions.length,1);assert.equal(h.controller.getState().collecting,true);assert.equal(h.controller.getState().usable,true);assert.equal(h.positions[0].latitude,1.3);});
test('hidden tab stops collection; returning resumes the enabled session and rejects old callbacks',async()=>{const h=locationHarness();await h.controller.boot();h.visible(false);h.fix();assert.equal(h.controller.getState().collecting,false);h.visible(true);h.fix();assert.equal(h.positions.length,0);assert.equal(h.callbacks.length,2);assert.deepEqual(h.cleared,[1]);h.fix(1);assert.equal(h.positions.length,1);assert.equal(h.controller.getState().usable,true);});
test('trip lifecycle changes retain app assistance while explicit stop prevents further collection',async()=>{const h=locationHarness();await h.controller.boot();h.controller.lifecycleChanged();h.fix();assert.equal(h.callbacks.length,1);assert.equal(h.positions.length,1);h.controller.stop();h.fix();h.visible(false);h.visible(true);assert.equal(h.positions.length,1);assert.equal(h.callbacks.length,1);assert.equal(h.controller.getState().enabled,false);assert.equal(h.controller.getState().position,null);});
test('denial stops the watch; timeout remains manually correctable and accepts a later usable fix',()=>{const h=locationHarness();h.controller.start();h.callbacks[0].failure({code:3});assert.match(h.states.at(-1).reason,/timed out/);h.fix();assert.equal(h.positions.length,1);h.callbacks[0].failure({code:1});h.fix();assert.equal(h.positions.length,1);assert.equal(h.controller.getState().status,'denied');assert.deepEqual(h.cleared,[1]);});
test('stale/invalid fixes are rejected and poor accuracy remains approximate and unusable',()=>{const h=locationHarness();h.controller.start();h.fix(0,{timestamp:1});h.fix(0,{coords:{latitude:200}});assert.equal(h.positions.length,0);h.fix(0,{coords:{accuracy:300}});assert.equal(h.positions.length,1);assert.equal(h.controller.getState().usable,false);assert.match(h.states.at(-1).reason,/Low accuracy/);assert.match(locationDescription(h.positions[0],{collecting:true,now:1200000}),/stale/);assert.match(locationDescription(h.positions[0],{now:1000000}),/Floor and boarding remain unconfirmed/);});
test('loading hidden defers the location request until the app is foreground',async()=>{const h=locationHarness();h.visible(false);await h.controller.boot();assert.equal(h.callbacks.length,0);assert.equal(h.controller.getState().enabled,true);assert.equal(h.controller.getState().status,'suspended');h.visible(true);assert.equal(h.callbacks.length,1);});

const trip={id:'accepted-trip',revision:2,updatedAt:1000,route:{id:'accepted-route'}};
const memory=()=>{let raw=null;return {getItem:()=>raw,setItem:(key,value)=>{raw=value;},removeItem:()=>{raw=null;}};};
test('offline availability requires both exact accepted-trip persistence and verified shell',async()=>{const storage=memory();let cached=false;const c=createOfflineReadiness({storage,key:'trip',checkShell:async()=>({ready:cached,reason:'Missing assets'})});c.setTrip(trip);assert.equal(c.getState().ready,false);storage.setItem('trip',JSON.stringify(trip));await c.verify();assert.equal(c.getState().durable,true);assert.equal(c.getState().ready,false);cached=true;await c.verify();assert.equal(c.getState().ready,true);assert.equal(c.getState().savedAt,1000);storage.setItem('trip','corrupt');assert.equal(c.storageChanged().ready,false);});
test('updates immediately withdraw offline readiness while checking the new controller',async()=>{const storage=memory();storage.setItem('trip',JSON.stringify(trip));let callback,resolveShell;const sw={addEventListener:(name,fn)=>{callback=fn;},removeEventListener(){}};let delayed=false;const c=createOfflineReadiness({storage,key:'trip',serviceWorker:sw,checkShell:()=>delayed?new Promise(resolve=>{resolveShell=resolve;}):Promise.resolve({ready:true})});c.setTrip(trip);await c.verify();assert.equal(c.getState().ready,true);delayed=true;const pending=callback();assert.equal(c.getState().ready,false);resolveShell({ready:false,reason:'Update cache is incomplete'});await pending;assert.equal(c.getState().ready,false);assert.match(c.getState().reason,/incomplete/);});
test('blocked storage and removed trip never claim offline availability',async()=>{const c=createOfflineReadiness({storage:{getItem(){throw Error('blocked');}},key:'trip',checkShell:async()=>({ready:true})});c.setTrip(trip);await c.verify();assert.equal(c.getState().ready,false);assert.equal(c.getState().savedAt,null);c.setTrip(null);assert.match(c.getState().reason,/Start Journey/);});
test('missing worker, cache-check timeout and controller replacement fail closed',async()=>{assert.equal((await requestShellReadiness(null)).ready,false);class Channel {constructor(){this.port1={close(){}};this.port2={};}}const sw={controller:{postMessage(){}}};assert.equal((await requestShellReadiness(sw,{timeout:1,Channel})).ready,false);class ChangedChannel {constructor(){this.port1={close(){}};this.port2={};queueMicrotask(()=>{sw.controller={};this.port1.onmessage({data:{type:'offline-readiness',ready:true}});});}}assert.equal((await requestShellReadiness(sw,{timeout:20,Channel:ChangedChannel})).ready,false);});
