import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {saveJourney,restoreJourney,sourceState} from '../src/storage.js';import {DEFAULT_INPUT} from '../src/data.js';import {plan} from '../src/engine.js';import {transportStatus,handleApi} from '../server/adapter.js';
const storage=()=>{let item=null;return {getItem:()=>item,setItem:(_k,v)=>item=v};};
const geometry=JSON.parse(await readFile(new URL('../public/data/corridor.json',import.meta.url),'utf8'));
const sample=()=>({input:DEFAULT_INPUT,selected:'circle',scene:'disruption',current:'payalebar',routes:plan(DEFAULT_INPUT).routes,geometry:structuredClone(geometry)});
test('save/restore preserves selected journey; broken storage never acknowledges save',()=>{const s=storage();assert.equal(saveJourney(s,sample()).ok,true);assert.equal(restoreJourney(s).selected,'circle');assert.equal(saveJourney({setItem(){throw Error('quota');}},sample()).ok,false);});
test('corrupt and old payloads rejected',()=>{for(const v of ['{oops',JSON.stringify({version:1,input:{},routes:[null],selected:'direct'}),JSON.stringify({...sample(),version:0})])assert.equal(restoreJourney({getItem:()=>v}),null);});
test('corrupt saved ride stops and geometry cannot crash offline recovery',()=>{for(const mutate of [p=>delete p.routes[0].legs.find(l=>l.type==='ride').stops,p=>p.geometry.features[0].geometry.coordinates=[[NaN,1]],p=>delete p.routes[0].reasons]){const s=storage(),p=sample();mutate(p);saveJourney(s,p);assert.equal(restoreJourney(s),null);}});
test('freshness is independent of journey state and rejects invalid/future stamps',()=>{const now=Date.now();assert.equal(sourceState({online:false,status:'replay'},now),'offline');for(const checkedAt of ['bad','2099-01-01T00:00:00Z',new Date(now-120001).toISOString()])assert.equal(sourceState({online:true,checkedAt,status:'replay'},now),'stale');assert.equal(sourceState({online:true,checkedAt:new Date(now).toISOString(),status:'partial'},now),'partial');});
test('missing key does not fetch and exposes unavailable not live',async()=>{const r=await transportStatus({},()=>{throw Error('must not call');});assert.equal(r.status,'unavailable');assert.deepEqual(r.alerts,[]);});
test('upstream failure does not leak credentials or erase source quality',async()=>{const r=await transportStatus({LTA_ACCOUNT_KEY:'SECRET-TEST'},async()=>{throw Error('SECRET-TEST');});assert.equal(r.status,'unavailable');assert.equal(JSON.stringify(r).includes('SECRET-TEST'),false);});
test('live notices are partial and do not pretend to supply carriage or route predictions',async()=>{let opts;const r=await transportStatus({LTA_ACCOUNT_KEY:'test-only'},async(_url,o)=>{opts=o;return Response.json({value:{Status:2,Message:[{Content:'Operator advisory',CreatedDate:'2026-09-19'}]}});});assert.equal(opts.headers.AccountKey,'test-only');assert.equal(r.status,'partial');assert.equal(r.crowding.status,'unavailable');assert.equal(r.routing.status,'replay');});
test('malformed API payload fails closed',async()=>{assert.equal((await transportStatus({LTA_ACCOUNT_KEY:'test'},async()=>Response.json({value:[]}))).status,'unavailable');});
test('API health endpoint works without secret',async()=>{const r=await handleApi(new Request('https://example.com/api/health'),{});assert.equal(r.status,200);assert.equal((await r.json()).ok,true);});
test('GIS contains actual directed tracks and explicitly indicative transfer links',async()=>{const geo=JSON.parse(await readFile(new URL('../public/data/corridor.json',import.meta.url),'utf8'));const rails=geo.features.filter(f=>f.properties.kind!=='interchange');assert.equal(rails.length,16);assert.ok(rails.every(f=>f.geometry.coordinates.length>2&&f.properties.osmRelation));const links=geo.features.filter(f=>f.properties.kind==='interchange');assert.equal(links.length,2);assert.ok(links.every(f=>f.properties.geometryAccuracy==='illustrative'&&f.properties.walkingDistanceMeters===null));});
test('service worker never caches OSM tiles or API responses',async()=>{const sw=await readFile(new URL('../public/sw.js',import.meta.url),'utf8');assert.match(sw,/url.origin!==self.location.origin/);assert.match(sw,/pathname.startsWith\('\/api\/'\)/);assert.ok(!sw.includes('tile.openstreetmap.org/'));});

