import test from 'node:test';
import assert from 'node:assert/strict';
import {canonicalReroute} from '../src/reroute-model.js';
import {acceptDetour,startJourney} from '../src/journey-v2.js';
import {estimatePlanFare} from '../src/fares.js';

function remaining(){return {input:{originId:'EW2',destinationId:'EW12',date:'2026-09-18',departureTime:'10:00',walkingLimitMinutes:30},carriedWalkSeconds:1200,carriedContext:{hasBoarded:true},progress:{legIndex:0,kind:'waiting'},route:{id:'remaining-trip',departureSeconds:37200,arrivalSeconds:38100,walkingSeconds:300,legs:[{type:'access',fromStopId:'EW8_A',toStopId:'EW8_A',durationSeconds:300,startSeconds:37200,endSeconds:37500,walkingSeconds:300},{type:'ride',mode:'rail',routeId:'EWL',fromStopId:'EW8_A',toStopId:'EW12_A',durationSeconds:600,startSeconds:37500,endSeconds:38100}]}};}
test('an accepted remaining route retains walking used before it and rejects an over-budget toilet detour',()=>{const plan=canonicalReroute(remaining());assert.equal(plan.route.walkingSeconds,1500);assert.equal(plan.route.legacyRoute.walkingSeconds,300);plan.mode='replay';const journey=startJourney(plan);assert.throws(()=>acceptDetour(journey,{toiletId:'test-toilet',fixture:true,addedSeconds:600,walkingSeconds:600,breakMinutes:0,steps:[{text:'Test detour walk',durationSeconds:600}]}),/walking allowance/);});
test('paid travel before the accepted remainder prevents a partial fare being presented as the complete charge',()=>{const plan=canonicalReroute(remaining());const result=estimatePlanFare(plan);assert.equal(result.status,'unavailable');assert.equal(result.totalCents,null);assert.match(result.reason,/earlier paid travel/);});
test('a before-departure alternative still receives the supported whole-trip fare estimate',()=>{const context=remaining();context.carriedWalkSeconds=0;context.carriedContext.hasBoarded=false;context.progress.kind='not-departed';const plan=canonicalReroute(context);assert.equal(plan.route.walkingSeconds,300);assert.equal(estimatePlanFare(plan).totalCents,149);});
test('an existing fare reassessment requirement survives later routing context resets',()=>{const context=remaining();context.carriedContext.hasBoarded=false;context.carriedWalkSeconds=0;const priorRoute={fareEstimate:{status:'unavailable',reason:'Gate re-entry requires actual charge.'}};const plan=canonicalReroute(context,{priorRoute});assert.equal(estimatePlanFare(plan).reason,priorRoute.fareEstimate.reason);assert.notEqual(plan.route.fareEstimate,priorRoute.fareEstimate);});
test('confirmed completed ride legs also require full fare reassessment',()=>{const context=remaining();context.carriedContext.hasBoarded=false;context.progress.legIndex=2;assert.equal(estimatePlanFare(canonicalReroute(context)).status,'unavailable');});
