import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.TEST_BASE_URL??'http://127.0.0.1:4186';
const output=process.env.CAPTURE_DIR??'test-results/upgrades';
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
const results=[],errors=[];const check=(name,value)=>{assert.ok(value,name);results.push({name,status:'PASS'});console.log('PASS '+name);};
// These legacy flows exercise direct pause/finish controls with a persisted full-guidance choice.
const contexts=[];async function client(){const c=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'allow'});contexts.push(c);await c.addInitScript(()=>{if(localStorage.getItem('commute-copilot-presentation-v1')===null)localStorage.setItem('commute-copilot-presentation-v1',JSON.stringify({schemaVersion:1,simpleGuidance:false}));});const p=await c.newPage();p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/?legacy=1');await p.locator('#saved-title').waitFor();return {c,p};}
const active=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('commute-copilot-journey-v2')));
try{
 const {p:caregiver}=await client();
 for(const [label,station]of [['Home','Paya Lebar'],['Hospital','Bugis']]){const f=caregiver.locator('#place-add');await f.locator('[name=label]').fill(label);await f.getByText('Or choose a station',{exact:true}).click();await f.locator('[name=source]').selectOption({label:station});await f.getByRole('button',{name:'Save place on this device',exact:true}).click();}
 await caregiver.getByText('Save a frequent journey between your places',{exact:true}).click();const pair=caregiver.locator('#pair-add');await pair.locator('[name=label]').fill('Appointment');await pair.locator('[name=originId]').selectOption({label:'Home'});await pair.locator('[name=destinationId]').selectOption({label:'Hospital'});await pair.getByRole('button',{name:'Save Route'}).click();await caregiver.reload();await caregiver.locator('#saved-time').fill('10:00');await caregiver.locator('[data-template][data-action=select]').click();await caregiver.getByRole('button',{name:'Find rail journeys'}).click();await caregiver.locator('#review-selected').click();check('saved pair reloads and resolves both real endpoints',await caregiver.locator('#companion-preview').innerText().then(t=>t.includes('Paya Lebar')&&t.includes('Bugis')));
 await caregiver.locator('#companion-preview .confirmation-details > summary').click();check('official corridor fare appears',await caregiver.locator('#companion-preview').innerText().then(t=>t.includes('1.49')));
 // Physical accessible corridor data is missing. Rehearsal is visibly separate.
 await caregiver.locator('[data-field=station]').selectOption('fixture-interchange');await caregiver.locator('#companion-facilities details').first().locator('summary').click();await caregiver.locator('[data-action=start-fixture]').click();await caregiver.locator('#prepare-link').click();await caregiver.locator('[data-qr=invite]').waitFor();await caregiver.locator('[data-qr=invite]').click();await caregiver.locator('#share-qr svg').waitFor();
 const session=await caregiver.evaluate(()=>JSON.parse(localStorage.getItem('commute-copilot-pairing-v2')));check('recipient QR generated locally',await caregiver.locator('#share-qr svg').count()===1);
 const {c:travellerContext,p:traveller}=await client();await traveller.goto(base+`/?legacy=1#invite=${session.id}.${session.inviteToken}`);await traveller.locator('#accept-invite').click();await traveller.locator('#apply-sharing').waitFor();check('acceptance does not grant either sharing permission',(await active(traveller)).permissions.progress===false&&(await active(traveller)).permissions.location===false);
 check('invitation credentials removed from address bar',!traveller.url().includes('#'));
 await traveller.locator('#share-progress').check();await traveller.locator('#apply-sharing').click();await traveller.waitForFunction(()=>JSON.parse(localStorage.getItem('commute-copilot-journey-v2')).permissions.progress);
 await traveller.locator('[data-field=station]').selectOption('fixture-interchange');await traveller.locator('[data-field=checkpoint]').selectOption('platform');await traveller.locator('[data-action=confirm]').click();await traveller.locator('#companion-facilities [data-action=toilets]').click();
 check('closest toilet initially has a prepared graph route',await traveller.locator('[data-preview=fixture-toilet-a]').count()===1);
 if(!await traveller.locator('#companion-facilities details').first().getAttribute('open').then(v=>v!==null))await traveller.locator('#companion-facilities details').first().locator('summary').click();
 await traveller.locator('[data-field=scenario]').selectOption('lift-outage');check('failed lift removes closest toilet, independent option remains',await traveller.locator('[data-preview=fixture-toilet-a]').count()===0&&await traveller.locator('[data-preview=fixture-toilet-b]').count()===1);
 if(await traveller.locator('#accept-proposal').count())await traveller.locator('#accept-proposal').click();
 await traveller.locator('[data-preview=fixture-toilet-b]').click();await traveller.locator('[data-action=accept-detour]').click();check('accepted detour preserves destination and updates trip card',(await active(traveller)).plan.destination.id==='fixture-destination'&&(await active(traveller)).detour.toiletId==='fixture-toilet-b'&&await traveller.locator('.ongoing-card').innerText().then(t=>t.includes('Lift B')||t.includes('fixture-lift-b')||t.includes('Continue via')));
 await traveller.waitForTimeout(300);await caregiver.locator('#refresh-share').click();await caregiver.waitForFunction(()=>document.querySelector('#shared-view')?.textContent.includes('Latest authorised update'));check('caregiver sees authorised accepted update only',await caregiver.locator('#shared-view').innerText().then(t=>t.includes('Latest authorised update')&&!t.includes('Latest approximate location')));
 await traveller.locator('#companion-facilities [data-action=reached]').click();await traveller.locator('#companion-facilities [data-action=resume]').click();check('resume retains return guidance without assuming original platform',(await active(traveller)).detour.status==='returning');await traveller.locator('[data-action=layout]').click();await traveller.locator('[data-field=checkpoint]').selectOption('platform');await traveller.locator('[data-action=confirm]').click();check('manual onward checkpoint resumes original journey',(await active(traveller)).detour.status==='resumed');
 await traveller.locator('#journey-pause').click();check('pause updates the same trip card',await traveller.locator('.ongoing-card').innerText().then(t=>t.includes('Journey paused')));await traveller.locator('#journey-pause').click();
 await travellerContext.setOffline(true);await traveller.reload();await traveller.locator('#companion-active').waitFor();await traveller.locator('.ongoing-card summary').click();check('offline reload restores accepted state and facility scenario',(await active(traveller)).facilityScenario==='lift-outage'&&await traveller.locator('.ongoing-card').innerText().then(t=>t.includes('Offline')));await travellerContext.setOffline(false);await traveller.waitForTimeout(300);
 await traveller.locator('#revoke-sharing').click();await traveller.waitForFunction(()=>JSON.parse(localStorage.getItem('commute-copilot-journey-v2')).permissions.revoked);await traveller.locator('#journey-finish').click();await traveller.locator('#show-demo-spend').check();const count=await traveller.locator('#companion-fares [data-edit]').count();await traveller.locator('#retry-fare').click();check('completion records exactly once in separate rehearsal ledger',count===1&&await traveller.locator('#companion-fares [data-edit]').count()===1);
 check('390px has no horizontal page overflow',await traveller.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await traveller.evaluate(()=>document.documentElement.style.fontSize='200%');check('200% type has no horizontal page overflow',await traveller.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await traveller.evaluate(()=>document.documentElement.style.fontSize='');await traveller.locator('#companion-active').scrollIntoViewIfNeeded();await mkdir(output,{recursive:true});await traveller.screenshot({path:output+'/mobile-trip.png'});
 const cached=await traveller.evaluate(async()=>{const entries=await Promise.all((await caches.keys()).map(async name=>(await (await caches.open(name)).keys()).map(r=>new URL(r.url).pathname)));return entries.flat();});check('offline shell contains new guidance but never personal APIs',cached.includes('/src/facility-ui.js')&&!cached.some(p=>p.startsWith('/api/')));
 check('no browser runtime errors',errors.length===0);
 await writeFile(output+'/browser.json',JSON.stringify({environment:'Headless Chromium engine via installed Edge; mobile emulation, not physical devices',results,errors},null,2));
}catch(error){for(const c of contexts)for(const p of c.pages())console.log('UI diagnostic:',await p.locator('#companion-message').innerText().catch(()=>''));console.log('Page errors:',errors);throw error;}finally{for(const c of contexts)await c.close();await browser.close();}
