import {createMultimodalRouter} from './multimodal-engine.js';
import {mountCompanion} from './copilot-ui.js';
import {createPersonalStore,singaporeNow,instantiateTemplate} from './personal.js';
import {createPreferencesStore,TRAVEL_STYLES} from './preferences.js';
import {endpointCatalog,suggestEndpoints,resolveEndpoint,timeInput,clock} from './planner-model.js';
import {acceptJourney} from './journey-state.js';
import {journeyCard,routeFromLegacy} from './journey-v2.js';
import {mountRerouting} from './rerouting-ui.js';
import {icon} from './icons.js';
import {mountTimePickers} from './time-picker.js';
import {drawNetworkOverview} from './network-map.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=id=>document.getElementById(id);
const mins=s=>`${Math.ceil(s/60)} min`;
let storage;try{storage=window.localStorage;}catch{storage={getItem:()=>null,setItem:()=>{throw Error('Storage blocked');},removeItem:()=>{throw Error('Storage blocked');}};}
const personal=createPersonalStore(storage),preferencesStore=createPreferencesStore(storage);
let preferences=preferencesStore.read().preferences,rail,bus,walking,router,build,catalog=[],routes=[],selected=null,input=null,companion,map,mapLayers,view='plan',resolved={origin:null,destination:null},suggestionState={},searchEpoch=0;
const names=new Map();
const name=id=>names.get(id)??id??'station';
document.body.className='commute-app';document.title='Commute Copilot · Your way, together';
document.querySelector('.skip')?.setAttribute('href','#main');
$('app').innerHTML=`<div class="app-shell">
  <div class="app-map" id="commute-map" aria-label="Singapore journey map"></div>
  <header class="app-topbar"><a class="brand-mark" href="/" aria-label="Commute Copilot home">${icon('compass',28)}</a><div class="brand-copy"><strong>Commute Copilot</strong><span>A little help along the way.</span></div><div class="topbar-actions"><span id="network-status" class="status-pill">${icon('online',16)} Online</span><button class="icon-button" id="open-demo" aria-label="Open demo and coverage">${icon('info')}</button></div></header>
  <div class="map-caption" id="map-caption">${icon('layers',16)} Station overview · not indoor directions</div>
  <button class="icon-button map-recenter" id="recenter-map" aria-label="Show whole route">${icon('location')}</button>
  <main id="main" class="app-panel" tabindex="-1"><div class="sheet-handle" aria-hidden="true"></div><div class="panel-scroll">
    <section id="view-plan" class="view" aria-labelledby="plan-heading"><div class="view-heading"><p class="eyebrow">LET’S GET YOU THERE</p><h1 id="plan-heading">Where are we going?</h1><p>Your next connection, made a little easier.</p></div>
    <form id="plan-form"><div class="endpoint-card">
      ${['origin','destination'].map((k,i)=>`<div class="endpoint-field"><span class="field-icon">${icon(i?'location':'compass')}</span><div class="field-content"><label for="${k}">${i?'Where to?':'Starting from'}</label><input id="${k}" autocomplete="off" placeholder="Station, bus stop or saved place" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-controls="${k}-suggestions" required><div id="${k}-suggestions" class="search-options suggestions" role="listbox" aria-label="${i?'Destination':'Origin'} suggestions" hidden></div></div></div>`).join('')}
      <button class="icon-button endpoint-swap" type="button" id="swap" aria-label="Swap origin and destination">${icon('swap')}</button></div>
      <p id="endpoint-help" class="field-note">Type a station name or code. Select a suggestion to confirm it.</p>
      <div class="time-options segmented" role="group" aria-label="Journey timing"><button type="button" data-time="leave-now" aria-pressed="true">${icon('clock',18)} Leave now</button><button type="button" data-time="depart-later" aria-pressed="false">Depart later</button><button type="button" data-time="arrive-by" aria-pressed="false">Arrive by</button></div>
      <input type="hidden" name="timeMode" value="leave-now"><div id="departure-fields" class="field-pair" hidden><label>Departure date<input type="date" name="date" required></label><label>Depart at<input type="time" name="departureTime" required></label></div>
      <div id="deadline-fields" class="field-pair" hidden><label>Arrival date<input type="date" name="deadlineDate"></label><label>Arrive by<input type="time" name="deadlineTime"></label></div><p id="time-note" class="field-note">Uses the current date and time in Singapore (SGT).</p>
      <button class="preference-summary" type="button" id="edit-preferences"></button><button class="primary" id="find-routes" disabled>${icon('route',20)} Find my route ${icon('arrow-right',20)}</button>
    </form><p class="planner-status" id="planner-status" role="status" aria-live="polite">Loading supported routes…</p>
    <div id="route-results"></div><div id="review-companion" hidden></div>
    <details class="coverage-details"><summary>Where can I travel?</summary><div id="coverage-copy"></div></details></section>
    <section id="view-current" class="view" hidden aria-labelledby="current-heading"><div class="view-heading"><p class="eyebrow">ONE STEP AT A TIME</p><h1 id="current-heading">Your current trip</h1><p>Keep your next connection close.</p></div><div id="current-summary" class="empty-state">${icon('trip',42)}<h2>Ready when you are.</h2><p>Find a route, review it, then Start Journey.</p><button class="secondary" data-go="plan">Plan a journey</button></div><div id="companion-host"></div><div id="rerouting-host"></div></section>
    <section id="view-saved" class="view" hidden aria-labelledby="saved-heading"><div class="view-heading"><p class="eyebrow">YOUR FAMILIAR PLACES</p><h1 id="saved-heading">Saved routes</h1><p>A shortcut to your next journey. Times are calculated when you reopen.</p></div><div id="saved-routes"></div><details><summary>Manage saved places</summary><div id="saved-companion"></div></details></section>
    <section id="view-preferences" class="view" hidden aria-labelledby="preferences-heading"><div class="view-heading"><p class="eyebrow">MAKE IT YOUR JOURNEY</p><h1 id="preferences-heading">How do you like to travel?</h1><p>Start with a travel style. Make every setting your own.</p></div><div id="preferences-content"></div></section>
    <section id="view-demo" class="view" hidden aria-labelledby="demo-heading"><div class="view-heading"><p class="eyebrow">A PLACE TO EXPLORE</p><h1 id="demo-heading">Demo & coverage</h1></div><div class="notice">Demonstration incidents and indoor paths are fictional. They do not describe current conditions.</div><a class="style-card" href="/replay.html">${icon('demo',32)}<div><h2>Try the corridor demo</h2><p>Rehearse disruption decisions and the original three-station story.</p></div>${icon('arrow-right')}</a><button class="secondary" id="demo-facilities">Explore the labelled station fixture</button><p>Real verified accessible indoor paths and real toilet-routing coverage are not available. Ask station staff for assistance.</p><p>Live reports, geographic sharing and Web Push require their configured online services. External delivery and physical-phone behaviour have not been verified.</p><button class="secondary" id="demo-selected-route">Rehearse the route I just planned</button><p class="field-note">Creates a separate, labelled demo journey for fictional train incidents. Finish or cancel your current trip first.</p><div id="demo-routing"></div></section>
  </div></main>
  <button id="trip-peek" class="trip-peek" hidden></button>
  <nav class="app-nav" aria-label="Main navigation">${[['plan','plan','Plan'],['current','trip','Current trip'],['saved','saved','Saved routes'],['preferences','preferences','Preferences']].map(([id,i,label])=>`<button data-view="${id}" ${id==='plan'?'aria-current="page"':''}>${icon(i)}<span>${label}</span></button>`).join('')}</nav>
  <div id="app-message" class="app-toast" role="status" aria-live="polite"></div></div>`;

function message(text){$('app-message').textContent=text;$('app-message').classList.add('is-visible');clearTimeout(message.timer);message.timer=setTimeout(()=>$('app-message').classList.remove('is-visible'),6000);}
function showView(next,{focus=true}={}) {view=next;document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==`view-${next}`);document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===next)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(next==='saved')renderSaved();updateCurrent(companion?.getActive());if(focus){const heading=$(`view-${next}`).querySelector('h1');heading.tabIndex=-1;heading.focus({preventScroll:true});document.querySelector('.panel-scroll').scrollTop=0;}document.body.dataset.view=next;map?.invalidateSize();drawMap();}
window.addEventListener('copilot:message',e=>message(e.detail.text));
window.addEventListener('copilot:open-section',()=>showView('current'));
window.addEventListener('copilot:prepared',()=>{$('review-companion').hidden=false;showView('plan');$('review-companion').scrollIntoView({block:'start'});});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$('edit-preferences').onclick=()=>showView('preferences');$('open-demo').onclick=()=>showView('demo');$('trip-peek').onclick=()=>showView('current');$('demo-facilities').onclick=()=>{showView('current');document.getElementById('map-layout')?.click();};
$('demo-selected-route').onclick=()=>{try{if(!selected||!input)throw Error('Find a route in Plan first, then return here to rehearse it.');const plan=routeFromLegacy(selected,input,{name,mode:'real',source:'LABELLED DEMO: real timetable route with fictional incidents'});plan.mode='replay';companion.setPrepared(plan,{routingContext:acceptJourney(selected,{...input,fixture:'demo'},build.applicationSha256)});$('review-companion').hidden=false;showView('plan');$('review-companion').scrollIntoView({block:'start'});}catch(e){message(e.message);}};
function invalidate(){searchEpoch++;selected=null;routes=[];input=null;$('route-results').innerHTML='';$('review-companion').hidden=true;$('planner-status').textContent='Ready to find a fresh route. Your accepted trip stays unchanged.';drawMap();}
function currentCatalog(){return endpointCatalog(router.network,bus,personal.read().state);}
function closeSuggestions(key){$(`${key}-suggestions`).hidden=true;$(key).setAttribute('aria-expanded','false');$(key).removeAttribute('aria-activedescendant');}
function choose(key,point){resolved[key]=point.id;$(key).value=`${point.label}${point.kind==='saved'?'':` (${point.codes?.join(" / ")??point.routingId})`}`;closeSuggestions(key);invalidate();}
function showSuggestions(key){if(!router)return;catalog=currentCatalog();const list=suggestEndpoints(catalog,$(key).value);suggestionState[key]={items:list,index:-1};const box=$(`${key}-suggestions`);box.innerHTML=list.length?list.map((p,i)=>`<button type="button" class="suggestion-option" id="${key}-option-${i}" role="option" aria-selected="false" data-index="${i}" tabindex="-1">${icon(p.kind==='saved'?'saved':p.kind,22)}<span><strong>${esc(p.label)}</strong><small>${esc(p.routingId??'')} · ${esc(p.detail)}</small></span></button>`).join(''):'<p class="notice">No supported match. Try a station code or a listed bus stop. Addresses are not automatically resolved.</p>';box.hidden=false;$(key).setAttribute('aria-expanded','true');box.querySelectorAll('[data-index]').forEach(b=>{b.onpointerdown=e=>e.preventDefault();b.onclick=()=>choose(key,list[Number(b.dataset.index)]);});}
for(const key of ['origin','destination']){const field=$(key);field.oninput=()=>{resolved[key]=null;invalidate();showSuggestions(key);};field.onfocus=()=>{if(!resolved[key])showSuggestions(key);};field.onblur=()=>setTimeout(()=>closeSuggestions(key),120);field.onkeydown=e=>{const s=suggestionState[key];if(e.key==='Escape'){closeSuggestions(key);return;}if(!s||$(`${key}-suggestions`).hidden)return;if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();if(!s.items.length)return;s.index=(s.index+(e.key==='ArrowDown'?1:-1)+s.items.length)%s.items.length;document.querySelectorAll(`#${key}-suggestions [role=option]`).forEach((b,i)=>b.setAttribute('aria-selected',String(i===s.index)));field.setAttribute('aria-activedescendant',`${key}-option-${s.index}`);$(`${key}-option-${s.index}`).scrollIntoView({block:'nearest'});}else if(e.key==='Enter'&&s.index>=0){e.preventDefault();choose(key,s.items[s.index]);}};}
$('swap').onclick=()=>{[resolved.origin,resolved.destination]=[resolved.destination,resolved.origin];[$('origin').value,$('destination').value]=[$('destination').value,$('origin').value];invalidate();};
const form=$('plan-form');mountTimePickers(form);const now=singaporeNow();form.elements.date.value=now.departureDate;form.elements.departureTime.value=now.departureTime;form.elements.deadlineDate.value=now.departureDate;
function setTimeMode(mode){form.elements.timeMode.value=mode;document.querySelectorAll('[data-time]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.time===mode)));$('departure-fields').hidden=mode==='leave-now';$('deadline-fields').hidden=mode!=='arrive-by';$('time-note').textContent=mode==='leave-now'?'Uses the current date and time in Singapore (SGT).':mode==='arrive-by'?'Singapore time (SGT). Filters journeys from your chosen departure against this deadline; does not find a latest departure.':'Choose a date and time in Singapore (SGT). Tap the time control or enter it with your keyboard.';}
document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{setTimeMode(b.dataset.time);invalidate();});form.addEventListener('change',e=>{if(e.target.name)invalidate();});
function renderPreferences(){const p=preferences;const style=TRAVEL_STYLES.find(s=>s.id===p.travelStyle);$('edit-preferences').innerHTML=`<span>${icon(p.stepFree?'accessibility':'heart',20)} ${esc(style?.label??'Your travel preferences')}</span><small>${p.walkingLimitMinutes} min walking · ${esc(p.preference.replaceAll('-',' '))}</small>${icon('chevron-right',18)}`;
  $('preferences-content').innerHTML=`<div class="style-grid">${TRAVEL_STYLES.map(s=>`<button class="style-card ${s.id===p.travelStyle?'is-selected':''}" data-preset="${s.id}" aria-pressed="${s.id===p.travelStyle}">${icon(s.id==='rachel'?'work':s.id==='arjun'?'heart':'accessibility',30)}<span><strong>${esc(s.label)}</strong><small>${esc(s.explanation)}</small></span></button>`).join('')}</div><form id="preferences-form"><div class="field-pair"><label>Walking limit (minutes)<input type="number" min="0" max="240" name="walkingLimitMinutes" value="${p.walkingLimitMinutes}" required></label><label>Extra time allowed (minutes)<input type="number" min="0" max="120" name="maxExtraMinutes" value="${p.maxExtraMinutes}" required></label></div><label>Route priority<select name="preference">${[['fastest','Fastest arrival'],['fewer-transfers','Fewer transfers'],['less-walking','Less walking'],['quieter','Quieter (data unavailable)']].map(([id,label])=>`<option value="${id}" ${p.preference===id?'selected':''}>${label}</option>`).join('')}</select></label><label class="check-row"><input type="checkbox" name="stepFree" ${p.stepFree?'checked':''}> Require a verified step-free route</label><label class="check-row"><input type="checkbox" name="assistanceRequested" ${p.assistanceRequested?'checked':''}> Prefer assistance and advance planning</label><label>Fare category<select name="fareCategory">${[['adult','Adult card'],['senior','Senior concession card'],['pwd','Disability concession card'],['student','Student concession card']].map(([id,label])=>`<option value="${id}" ${p.fareCategory===id?'selected':''}>${label}</option>`).join('')}</select></label><p class="notice">These are editable planning choices, not calibrated walking speeds. Train times stay set by the timetable. Step-free paths, crowding and shelter are not verified.</p><button class="primary">Save preferences</button><p class="field-note">Applies to future searches. An accepted route changes only after your review.</p></form>`;
  document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{try{preferences=preferencesStore.applyPreset(b.dataset.preset);renderPreferences();invalidate();message('Travel style applied. Review and edit its settings below.');}catch(e){message(e.message);}});
  $('preferences-form').onsubmit=e=>{e.preventDefault();try{const f=e.target;preferences=preferencesStore.update({travelStyle:'custom',walkingLimitMinutes:Number(f.elements.walkingLimitMinutes.value),maxExtraMinutes:Number(f.elements.maxExtraMinutes.value),preference:f.elements.preference.value,stepFree:f.elements.stepFree.checked,assistanceRequested:f.elements.assistanceRequested.checked,fareCategory:f.elements.fareCategory.value});renderPreferences();invalidate();message('Preferences saved on this device.');}catch(e){message(e.message);}};
}
function routeLines(r){return [...new Set(r.legs.filter(l=>l.type==='ride').map(l=>l.mode==='bus'?`Bus ${l.serviceNo}`:l.routeId))].map(label=>`<span class="line-pill">${icon(label.startsWith('Bus')?'route':'train',16)}${esc(label)}</span>`).join('');}
function renderResults(){const selectedIndex=routes.findIndex(r=>r.id===selected?.id);$('route-results').innerHTML=`<div class="section-label"><h2>Let’s find your fit.</h2><span>${routes.length} option${routes.length===1?'':'s'}</span></div><p class="field-note">${esc(input.date)} · depart ${esc(input.departureTime)} SGT. ${input.deadlineTime?`Arrival deadline ${esc(input.deadlineDate)} ${esc(input.deadlineTime)}.`:''}</p>${routes.map((r,i)=>`<button type="button" class="route-card ${r.id===selected?.id?'is-selected':''}" data-route="${i}" aria-pressed="${r.id===selected?.id}"><div class="route-card-top"><strong>${mins(r.totalSeconds)}</strong><span>${i===0?'Suggested route':`Option ${i+1}`}</span>${r.id===selected?.id?icon('check',22):''}</div><div class="route-lines">${routeLines(r)}</div><div class="route-metrics"><span>Arrive ${clock(r.arrivalSeconds)}</span><span>${r.transfers} transfer${r.transfers===1?'':'s'}</span><span>${icon('walk',16)}${mins(r.walkingSeconds)}</span></div></button>`).join('')}<div class="field-pair"><button class="secondary" id="save-route">${icon('saved',20)} Save Route</button><button class="primary" id="review-route">Review route ${icon('arrow-right',18)}</button></div><form class="save-route-form" id="save-route-form" hidden><label>Route name<input name="label" maxlength="80" required value="${esc(name(input.originId)+' to '+name(input.destinationId))}"></label><button class="secondary">Save Route on this device</button></form><details class="review-details"><summary>Journey steps & assumptions</summary><ol>${(selected?.legs??[]).map(l=>`<li><strong>${esc(l.type==='ride'?l.mode==='bus'?`Bus ${l.serviceNo} · direction ${l.directionId}`:`${l.routeId} train`:l.type)}</strong><p>${esc(name(l.fromStopId))} → ${esc(name(l.toStopId))}</p><small>${clock(l.startSeconds)}–${clock(l.endSeconds)} · ${mins(l.durationSeconds)}</small></li>`).join('')}</ol>${(selected?.assumptions??[]).map(a=>`<p class="field-note">${esc(a)}</p>`).join('')}</details>`;
  document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{selected=routes[Number(b.dataset.route)];$('review-companion').hidden=true;renderResults();drawMap();});
  $('save-route').onclick=()=>{$('save-route-form').hidden=!$('save-route-form').hidden;if(!$('save-route-form').hidden)$('save-route-form').elements.label.focus();};
  $('save-route-form').onsubmit=e=>{e.preventDefault();try{const from=resolveEndpoint(catalog,resolved.origin,router.network),to=resolveEndpoint(catalog,resolved.destination,router.network);personal.saveRoute({label:e.target.elements.label.value,origin:from,destination:to,preferences,...input});companion.refresh();renderSaved();$('save-route-form').hidden=true;message('Route saved. Reopen it any time for fresh journey times.');}catch(error){message(error.message);}};
  $('review-route').onclick=()=>{try{$('review-companion').hidden=false;companion.review();$('review-companion').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}catch(e){message(e.message);}};
}
form.onsubmit=async e=>{e.preventDefault();const epoch=++searchEpoch;try{catalog=currentCatalog();const origin=resolveEndpoint(catalog,resolved.origin,router.network),destination=resolveEndpoint(catalog,resolved.destination,router.network);const timing=timeInput(Object.fromEntries(new FormData(form)));input={...preferences,...timing,originId:origin.routingId,destinationId:destination.routingId,mode:'mixed'};if(input.originId===input.destinationId)throw Error('Choose different starting and destination stations.');$('planner-status').textContent='Finding your next connection…';$('find-routes').disabled=true;await new Promise(resolve=>requestAnimationFrame(resolve));const result=router.route(input);if(epoch!==searchEpoch)return;routes=result.routes?.filter(r=>r.deadlineMet!==false)??[];selected=routes.find(r=>r.id===result.recommended?.id)??routes[0]??null;$('review-companion').hidden=true;if(!selected){$('route-results').innerHTML='';$('planner-status').textContent=(result.errors??[]).map(e=>e.message??e).join(' ')||'No feasible journey in the supported service window. Try another time or adjust preferences.';}else{$('planner-status').textContent=preferences.stepFree?'Timetable options only. No continuous step-free path is verified; starting as accessible guidance is unavailable.':preferences.preference==='quieter'?'Crowding information is unavailable. Options use timetable timing instead.':'Choose a route, then review before starting.';renderResults();}drawMap();}catch(error){selected=null;routes=[];$('route-results').innerHTML='';$('planner-status').textContent=error.message;}finally{$('find-routes').disabled=!router;}};
function restoreTiming(plan){const fresh=singaporeNow();form.elements.date.value=plan.departureDate??fresh.departureDate;form.elements.departureTime.value=plan.departureTime??fresh.departureTime;form.elements.deadlineDate.value=plan.deadlineDate??fresh.departureDate;form.elements.deadlineTime.value=plan.deadlineTime??plan.deadline??'';setTimeMode(plan.timeMode??'leave-now');}
function reopen(templateId){try{const plan=instantiateTemplate(personal.read().state,templateId);preferences=preferencesStore.update(plan.preferences);renderPreferences();catalog=currentCatalog();for(const role of ['origin','destination']){resolved[role]=plan[role].id;$(role).value=plan[role].label;}restoreTiming(plan);invalidate();showView('plan');message('Saved route reopened with fresh departure timing. Review any saved arrival deadline before searching.');}catch(e){message(e.message);}}
function renderSaved(){const result=personal.read();$('saved-routes').innerHTML=!result.ok?`<p class="notice">${esc(result.error)}</p>`:result.state.templates.length?result.state.templates.map(t=>`<article class="saved-route-card"><span class="saved-icon">${icon('saved',26)}</span><div><h2>${esc(t.label)}</h2><p>${esc(result.state.places.find(p=>p.id===t.originId)?.label??'Deleted place')} → ${esc(result.state.places.find(p=>p.id===t.destinationId)?.label??'Deleted place')}</p><div class="chip-row"><button class="secondary" data-open="${esc(t.id)}">Plan again ${icon('arrow-right',16)}</button><button class="quiet" data-delete="${esc(t.id)}">Remove</button></div></div></article>`).join(''):`<div class="empty-state">${icon('saved',44)}<h2>Your regular routes belong here.</h2><p>Choose Save Route after finding a journey. Reopening it recalculates the times.</p><button class="secondary" data-go-plan>Find a route</button></div>`;document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>reopen(b.dataset.open));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{try{personal.deleteTemplate(b.dataset.delete);renderSaved();companion.refresh();}catch(e){message(e.message);}});document.querySelector('[data-go-plan]')?.addEventListener('click',()=>showView('plan'));}
function guidanceLabel(step){if(!step)return null;const l=step.source;if(!l)return step.text;const from=name(l.fromStopId),to=name(l.toStopId);if(l.type==='access')return 'Confirm your starting platform at '+to;if(l.type==='wait')return 'Wait at '+from+' for your connection';if(l.type==='ride')return 'Ride '+(l.mode==='bus'?'Bus '+l.serviceNo:l.routeId)+' to '+to;if(l.type==='transfer')return 'Change from '+from+' to '+to;if(l.type==='exit')return 'Exit at '+from+' and confirm your arrival';return step.text;}
function updateCurrent(active){const card=journeyCard(active,{online:navigator.onLine,visible:!document.hidden});$('trip-peek').hidden=!card||['completed','cancelled'].includes(active.status)||view==='current';if(card){if(active.status==='started'&&!active.detour&&!active.facilityBlocked&&!active.facilityReview){card.current=guidanceLabel(active.route.steps[active.progress.stepIndex])??card.current;card.next=guidanceLabel(active.route.steps[active.progress.stepIndex+1])??card.next;}$('current-summary').className='current-route-summary';$('current-summary').innerHTML=`<div class="journey-metrics"><span>${icon('trip',28)}<strong>${esc(active.plan.destination.label)}</strong></span><strong>${clock(card.arrivalSeconds)} <small>estimated</small></strong></div><h2>${esc(card.current)}</h2><p>Next: ${esc(card.next)}</p>${active.status==='started'?'<button class="secondary" id="manual-correction">Confirm or correct my position</button>':''}${card.warnings.map(w=>`<p class="field-note">${esc(w)}</p>`).join('')}`;$('trip-peek').innerHTML=`${icon('trip',24)}<span><strong>${esc(card.current)}</strong><small>Current trip · estimated arrival ${clock(card.arrivalSeconds)}</small></span>${icon('chevron-right')}`;$('manual-correction')?.addEventListener('click',()=>{$('checkpoint-step')?.scrollIntoView({block:'center'});$('checkpoint-step')?.focus({preventScroll:true});});}drawMap();}
window.addEventListener('copilot:state-changed',e=>{const before=window.__copilotActiveId;updateCurrent(e.detail.active);window.__copilotActiveId=e.detail.active?.id;if(e.detail.active?.status==='started'&&before!==e.detail.active.id)showView('current');});
function drawMap(){if(!mapLayers)return;mapLayers.clearLayers();const active=companion?.getActive(),r=view==='current'?active?.route?.legacyRoute:selected;const points=[];const stops=new Map((router?.network.stops??[]).map(s=>[s.id,s]));for(const leg of r?.legs??[]){const path=walking.links.find(p=>p.id===leg.pathId);let coords=path?.path.waypoints.map(p=>[p.lat,p.lon??p.lng]);if(!coords)coords=(leg.stopIds??[leg.fromStopId,leg.toStopId]).map(id=>stops.get(id)).filter(s=>Number.isFinite(s?.lat)&&Number.isFinite(s?.lon)).map(s=>[s.lat,s.lon]);if(coords?.length>1){L.polyline(coords,{color:path?'#54867a':leg.mode==='bus'?'#977440':'#4575bc',weight:6,opacity:.9,dashArray:path?null:'8 6'}).addTo(mapLayers);points.push(...coords);}}
  const endpoints=view==='current'&&active?[active.plan.origin,active.plan.destination]:['origin','destination'].map(k=>catalog.find(p=>p.id===resolved[k]));endpoints.forEach((p,i)=>{if(!Number.isFinite(p?.lat)||!Number.isFinite(p?.lng))return;points.push([p.lat,p.lng]);L.marker([p.lat,p.lng],{title:p.label,icon:L.divIcon({className:`route-pin ${i?'destination-pin':''}`,html:`<span>${i?'B':'A'}</span>`,iconSize:[34,40],iconAnchor:[17,38]})}).bindPopup(document.createTextNode(p.label)).addTo(mapLayers);});if(view==='current'&&active?.location){const p=active.location;L.circle([p.latitude,p.longitude],{radius:p.accuracy,color:'#657dc0',fillOpacity:.13}).addTo(mapLayers);}
  drawMap.points=points;$('map-caption').innerHTML=`${icon('layers',16)} ${r?'Dashed lines: stop-to-stop schematic · solid: reviewed exterior path':'Network schematic · no indoor or step-free directions'}`;if(points.length&&drawMap.last!==r?.id){drawMap.last=r?.id;fitMap();}}
function fitMap(){if(drawMap.points?.length){const desktop=innerWidth>=960;map.fitBounds(drawMap.points,{paddingTopLeft:desktop?[500,95]:[32,90],paddingBottomRight:desktop?[60,65]:[32,50],maxZoom:14});}else map?.setView([1.335,103.86],12);}
$('recenter-map').onclick=fitMap;
async function initMap(){try{map=L.map('commute-map',{zoomControl:false,scrollWheelZoom:false}).setView([1.335,103.86],12);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>',maxZoom:19}).addTo(map);L.control.zoom({position:'topright'}).addTo(map);drawNetworkOverview(map,rail);mapLayers=L.layerGroup().addTo(map);drawMap();}catch{$('map-caption').textContent='Map unavailable. Text routes and saved guidance remain usable.';}}
function connection(){$('network-status').innerHTML=`${icon(navigator.onLine?'online':'offline',16)} ${navigator.onLine?'Online':'Offline'}`;updateCurrent(companion?.getActive());}window.addEventListener('online',connection);window.addEventListener('offline',connection);
async function boot(){try{[rail,bus,walking,build]=await Promise.all(['rail-network','bus-network','walking-links','application-build'].map(async n=>{const r=await fetch(`/data/${n}.json`);if(!r.ok)throw Error('Routing data could not be loaded. Reconnect to prepare this device.');return r.json();}));router=createMultimodalRouter(rail,bus,walking);for(const s of router.network.stations)names.set(s.id,s.name);for(const s of router.network.stops)names.set(s.id,`${s.name} (${s.id})`);try{personal.migrateLegacy();personal.migratePlannerSnapshots(id=>endpointCatalog(router.network,bus).find(p=>p.routingId===id));}catch(e){message(e.message);}catalog=currentCatalog();$('coverage-copy').innerHTML=`<p>Rail timetable: ${rail.coverage.startDate}–${rail.coverage.endDate}. All times are in Asia/Singapore. Dates outside coverage stay unavailable.</p><p>Bus services 2, 23 and 28: ordinary weekdays ${bus.coverage.validFrom}–${bus.coverage.validThrough}, 09:30–16:30. Bus timings are bounded estimates, not live vehicle arrivals.</p><p>Reviewed exterior connections only. Indoor accessibility, door-to-door paths, crowding, shelter and real toilet paths remain unverified.</p>`;
  initMap();companion=mountCompanion({host:$('companion-host'),showHeader:false,showDock:false,sectionHosts:{review:$('review-companion'),saved:$('saved-companion')},getMap:()=>map,getSelected:()=>selected&&input?{route:selected,input,routingContext:acceptJourney(selected,input,build.applicationSha256)}:null,getPlaces:()=>catalog.filter(p=>p.kind!=='saved'),name,getFareOptions:()=>({busNetwork:bus}),onSelectPlan:p=>{preferences=preferencesStore.update(p.preferences);renderPreferences();catalog=currentCatalog();for(const role of ['origin','destination']){resolved[role]=p[role].id;$(role).value=p[role].label;}restoreTiming(p);invalidate();showView('plan');},onEndpoint:(role,p)=>{catalog=currentCatalog();choose(role,p);showView('plan');}});
  for(const [key,label] of [['facilities','Station guidance & toilets'],['sharing','Caregiver sharing'],['spending','Journey spending']]){const section=companion.sections[key],details=document.createElement('details'),summary=document.createElement('summary');summary.textContent=label;section.before(details);details.append(summary,section);}
  mountRerouting({host:$('rerouting-host'),demoHost:$('demo-routing'),companion,router,build:build.applicationSha256,name,message});
  renderPreferences();renderSaved();updateCurrent(companion.getActive());window.__copilotActiveId=companion.getActive()?.id;$('find-routes').disabled=false;$('planner-status').textContent='Ready for your next connection.';
  if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>message('Offline setup is unavailable. This device is not ready for offline guidance.'));
}catch(e){$('planner-status').textContent=e.message;renderPreferences();}}
renderPreferences();boot();
