import {createMultimodalRouter} from './multimodal-engine.js';
import {mountCompanion} from './copilot-ui.js';
import {createPersonalStore,singaporeNow,instantiateTemplate,visiblePersonalState} from './personal.js';
import {createPreferencesStore,TRAVEL_STYLES} from './preferences.js';
import {endpointCatalog,suggestEndpoints,resolveEndpoint,timeInput,clock,plannerFeedback,busStopDetails} from './planner-model.js';
import {acceptJourney} from './journey-state.js';
import {journeyCard,routeFromLegacy} from './journey-v2.js';
import {mountRerouting} from './rerouting-ui.js';
import {icon} from './icons.js';
import {publicLineName,publicStationLabel,publicInstruction,itineraryGuidance,renderItineraryTimeline} from './itinerary-display.js';
import {mountTimePickers} from './time-picker.js';
import {drawNetworkOverview,addStreetMap} from './network-map.js';
import {journeyMapSegments,drawRouteSegments,routeLegendHTML} from './route-map.js';
import {railBadgeStyle} from './rail-service-style.js';
import {createPlannerClient} from './planner-client.js';
import {createCommuteShortcuts} from './commute-shortcuts.js';
import {mountBusArrivals,currentBusArrivalContext} from './arrivals-ui.js';
import {departureChoices,departureBenefit,FARE_FLEX_SOURCE} from './departure-flexibility.js';
import {createAddressRouter} from './address-routing.js';
import {createOneMapAddressSearch} from './address-search.js';
import {createPresentationPreferences,reducedGuidanceMotion} from './presentation-preferences.js';
import {resolveCurrentExecution} from './current-execution.js';
import {mountStaffCard} from './staff-card.js';
import {mountMapStationPages,indoorNoticeHTML} from './station-guide.js';
import {mountJourneySheet} from './journey-sheet.js';
import {mountBusStopMap} from './bus-stop-map.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=id=>document.getElementById(id);
const mins=s=>`${Math.ceil(s/60)} min`;
let storage;try{storage=window.localStorage;}catch{storage={getItem:()=>null,setItem:()=>{throw Error('Storage blocked');},removeItem:()=>{throw Error('Storage blocked');}};}
const personal=createPersonalStore(storage),preferencesStore=createPreferencesStore(storage);
let preferences=preferencesStore.read().preferences,rail,bus,walking,router,build,catalog=[],routes=[],selected=null,input=null,companion,map,mapLayers,view='plan',resolved={origin:null,destination:null},suggestionState={},searchEpoch=0,mapStatus='',streetMap,mapFailed=false;
const shortcuts=createCommuteShortcuts(storage),presentationStore=createPresentationPreferences(storage),addressRouter=createAddressRouter(),addressSearch=createOneMapAddressSearch();
let presentation=presentationStore.read(),plannerClient,planArrivals,currentArrivals,staffCard,mapPages,journeySheet,externalPoints=[],flexEpoch=0,baseCatalog=null;
const reducedMotion=()=>reducedGuidanceMotion(presentation,{systemReducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches});
const names=new Map();
const name=id=>names.get(id)??id??'station';
document.body.className='commute-app';document.body.classList.toggle('simple-guidance',presentation.simpleGuidance);document.title='Commute Copilot · Your way, together';
document.querySelector('.skip')?.setAttribute('href','#main');
$('app').innerHTML=`<div class="app-shell">
  <div class="map-pages" id="map-pages"><div class="app-map" id="commute-map" aria-label="Singapore journey map"></div><section id="map-station-page" class="map-station-page" hidden></section></div>
  <header class="app-topbar"><button class="brand-mark" type="button" id="home-plan" aria-label="Commute Copilot home">${icon('compass',28)}</button><div class="brand-copy"><strong>Commute Copilot</strong><span>A little help along the way.</span></div><div class="topbar-actions"><span id="network-status" class="status-pill">${icon('online',16)} Online</span><button class="icon-button" id="open-demo" aria-label="Open demo and coverage">${icon('info')}</button></div></header>
  <div class="map-caption" id="map-caption" hidden></div>
  <button class="icon-button map-recenter" id="recenter-map" aria-label="Show whole route">${icon('location')}</button>
  <main id="main" class="app-panel" tabindex="-1"><div id="journey-sheet-dock" class="journey-sheet-dock"></div><button class="sheet-handle" id="journey-sheet-handle" type="button" aria-controls="journey-panel-content" aria-expanded="true" aria-describedby="journey-sheet-help"><span>Expand journey panel</span></button><span class="sheet-help" id="journey-sheet-help">Drag up or down, or tap to resize. Arrow keys move one position; Home expands, End collapses, Escape restores normal height.</span><div class="panel-scroll" id="journey-panel-content">
    <section id="view-plan" class="view" aria-labelledby="plan-heading"><div class="view-heading"><p class="eyebrow">LET’S GET YOU THERE</p><h1 id="plan-heading">Where are we going?</h1><p>Your everyday journeys, planned around you.</p></div>
    <div id="commute-shortcuts"></div><form id="plan-form"><div class="endpoint-card">
      ${['origin','destination'].map((k,i)=>`<div class="endpoint-field"><span class="field-icon">${icon(i?'location':'compass')}</span><div class="field-content"><label for="${k}">${i?'Where to?':'Starting from'}</label><input id="${k}" autocomplete="off" placeholder="Station, bus stop or saved place" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-controls="${k}-suggestions" required><div id="${k}-suggestions" class="search-options suggestions" role="listbox" aria-label="${i?'Destination':'Origin'} suggestions" hidden></div><div id="${k}-stop-details" class="selected-stop-details" hidden></div></div></div>`).join('')}
      <button class="icon-button endpoint-swap" type="button" id="swap" aria-label="Swap origin and destination">${icon('swap')}</button></div>
      <p id="endpoint-help" class="field-note">Type a station name or code. Select a suggestion to confirm it.</p><details class="address-search-disclosure"><summary>Find a street address</summary><p class="field-note">Search OneMap explicitly. Address searches go to OneMap; private saved-place labels stay on this device. Routing sends selected coordinates and travel settings.</p><label>Use address as<select id="address-role"><option value="origin">Starting point</option><option value="destination" selected>Destination</option></select></label><label>Address or postal code<input id="address-query" maxlength="160" autocomplete="off"></label><div class="button-row"><button type="button" class="secondary" id="address-search">Search addresses</button><button type="button" class="quiet" id="cancel-address-search">Cancel search</button></div><div id="address-results" role="status"></div></details>
      <div class="time-options segmented" role="group" aria-label="Journey timing"><button type="button" data-time="leave-now" aria-pressed="true">${icon('clock',18)} Leave now</button><button type="button" data-time="depart-later" aria-pressed="false">Depart later</button><button type="button" data-time="arrive-by" aria-pressed="false">Arrive by</button></div>
      <input type="hidden" name="timeMode" value="leave-now"><div id="departure-fields" class="field-pair" hidden><label>Departure date<input type="date" name="date" required></label><label>Depart at<input type="time" name="departureTime" required></label></div>
      <div id="deadline-fields" class="field-pair" hidden><label>Arrival date<input type="date" name="deadlineDate"></label><label>Arrive by<input type="time" name="deadlineTime"></label></div><p id="time-note" class="field-note">Uses the current date and time in Singapore (SGT).</p>
      <button class="preference-summary" type="button" id="edit-preferences"></button><button class="primary" id="find-routes" disabled>${icon('route',20)} Find my route ${icon('arrow-right',20)}</button>
    </form><div class="planner-status" id="planner-status" role="status" aria-live="polite">Loading supported routes…</div>
    <details id="flexible-departure" class="flexible-departure"><summary>Flexible departure</summary><p>Compare a little earlier or later. Your destination, walking allowance and arrival deadline stay the same.</p><label>Departure window<select id="flex-window"><option value="15">15 minutes either way</option><option value="30">30 minutes either way</option><option value="60">1 hour either way</option></select></label><button type="button" class="secondary" id="compare-departures">Compare departures</button><div id="flex-results" role="status"></div></details><div id="route-results"></div><div id="plan-arrivals"></div><div id="review-companion" hidden></div>
    <details class="coverage-details"><summary>Where can I travel?</summary><div id="coverage-copy"></div></details></section>
    <section id="view-current" class="view" hidden aria-labelledby="current-heading"><div class="view-heading"><p class="eyebrow">ONE STEP AT A TIME</p><h1 id="current-heading">Your current trip</h1><p>Keep your next connection close.</p></div><div id="current-summary" class="empty-state">${icon('trip',42)}<h2>Ready when you are.</h2><p>Find a route, review it, then Start Journey.</p><button class="secondary" data-go="plan">Plan a journey</button></div><div id="current-arrivals"></div><div id="companion-host"></div><div id="rerouting-host"></div></section>
    <section id="view-saved" class="view" hidden aria-labelledby="saved-heading"><div class="view-heading"><p class="eyebrow">YOUR EVERYDAY JOURNEYS</p><h1 id="saved-heading">Saved routes</h1><p>Save a route after searching in Plan, or add a place below. Reopen a route to check fresh travel times.</p></div><div id="saved-routes"></div><div id="saved-companion"></div></section>
    <section id="view-caregiver" class="view" hidden aria-labelledby="caregiver-heading"><div class="view-heading"><p class="eyebrow">STAY CONNECTED</p><h1 id="caregiver-heading">Caregiver sharing</h1><p>Share a trip with someone you trust. You choose what they can see.</p></div><div id="caregiver-companion"></div></section>
    <section id="view-spending" class="view" hidden aria-labelledby="spending-heading"><div class="view-heading"><p class="eyebrow">YOUR TRAVEL COSTS</p><h1 id="spending-heading">Journey spending</h1><p>Review completed journeys and enter the fare you actually paid.</p></div><div id="spending-companion"></div></section>
    <section id="view-preferences" class="view" hidden aria-labelledby="preferences-heading"><div class="view-heading"><p class="eyebrow">MAKE IT YOUR JOURNEY</p><h1 id="preferences-heading">How do you like to travel?</h1><p>Start with a travel style. Make every setting your own.</p></div><div id="preferences-content"></div></section>
    <section id="view-staff" class="view staff-page" hidden aria-labelledby="staff-heading"><div class="view-heading"><p class="eyebrow">ASK FOR A HAND</p><h1 id="staff-heading">Show to staff</h1></div><div id="staff-content"></div></section>
    <section id="view-demo" class="view" hidden aria-labelledby="demo-heading"><div class="view-heading"><p class="eyebrow">A PLACE TO EXPLORE</p><h1 id="demo-heading">Demo & coverage</h1></div><div class="notice">Demonstration incidents and indoor paths are fictional. They do not describe current conditions.</div><a class="style-card" href="/replay.html">${icon('demo',32)}<div><h2>Try the corridor demo</h2><p>Rehearse disruption decisions and the original three-station story.</p></div>${icon('arrow-right')}</a><button class="secondary" id="demo-facilities">Explore the labelled station fixture</button><p>Real verified accessible indoor paths and real toilet-routing coverage are not available. Ask station staff for assistance.</p><p>Live reports, geographic sharing and Web Push require their configured online services. External delivery and physical-phone behaviour have not been verified.</p><button class="secondary" id="demo-selected-route">Rehearse the route I just planned</button><p class="field-note">Creates a separate, labelled demo journey for fictional train incidents. Finish or cancel your current trip first.</p><div id="demo-routing"></div></section>
  </div></main>
  <button id="trip-peek" class="trip-peek" hidden></button>
  <nav class="app-nav" aria-label="Main navigation">${[['plan','plan','Plan'],['current','trip','Current trip'],['saved','saved','Saved routes'],['caregiver','heart','Caregiver'],['spending','wallet','Spending'],['preferences','preferences','Settings'],['staff','info','Show to staff']].map(([id,i,label])=>`<button data-view="${id}" ${id==='plan'?'aria-current="page"':''}>${icon(i)}<span>${label}</span></button>`).join('')}</nav>
  <div id="app-message" class="app-toast" role="status" aria-live="polite"></div></div>`;

function message(text){$('app-message').textContent=text;$('app-message').classList.add('is-visible');clearTimeout(message.timer);message.timer=setTimeout(()=>$('app-message').classList.remove('is-visible'),6000);}
function showView(next,{focus=true}={}) {view=next;document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==`view-${next}`);document.querySelectorAll('.app-nav [data-view]').forEach(b=>{if(b.dataset.view===next)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});document.body.dataset.view=next;if(['plan','current'].includes(next)&&mapPages?.getPage()!=='map')mapPages?.show('map');journeySheet?.reset();if(next==='saved')renderSaved();updateCurrent(companion?.getActive());if(focus){const heading=$(`view-${next}`).querySelector('h1');heading.tabIndex=-1;heading.focus({preventScroll:true});document.querySelector('.panel-scroll').scrollTop=0;}map?.invalidateSize();drawMap();}
journeySheet=mountJourneySheet({shell:document.querySelector('.app-shell'),panel:$('main'),dock:$('journey-sheet-dock'),handle:$('journey-sheet-handle'),content:$('journey-panel-content'),mapPanel:$('commute-map'),nav:document.querySelector('.app-nav'),header:document.querySelector('.app-topbar'),getView:()=>view,onResize:()=>map?.invalidateSize()});
window.addEventListener('copilot:message',e=>message(e.detail.text));
window.addEventListener('copilot:open-section',e=>showView(({sharing:'caregiver',spending:'spending',saved:'saved',review:'plan',staff:'staff'})[e.detail.section]??'current'));
window.addEventListener('copilot:personal-changed',()=>{catalog=currentCatalog();renderSaved();});
$('home-plan').onclick=()=>showView('plan');
window.addEventListener('copilot:prepared-cleared',()=>{$('review-companion').hidden=true;});
window.addEventListener('copilot:prepared',()=>{$('review-companion').hidden=false;showView('plan');$('review-companion').scrollIntoView({block:'start'});});
document.querySelectorAll('.app-nav [data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$('edit-preferences').onclick=()=>showView('preferences');$('open-demo').onclick=()=>showView('demo');$('trip-peek').onclick=()=>showView('current');$('demo-facilities').onclick=()=>{showView('current');companion?.openFacilities('layout');};
$('demo-selected-route').onclick=()=>{try{if(!selected||!input)throw Error('Find a route in Plan first, then return here to rehearse it.');const plan=routeFromLegacy(selected,input,{name,mode:'real',source:'LABELLED DEMO: real timetable route with fictional incidents'});plan.mode='replay';companion.setPrepared(plan,{routingContext:acceptJourney(selected,{...input,fixture:'demo'},build.applicationSha256)});$('review-companion').hidden=false;showView('plan');$('review-companion').scrollIntoView({block:'start'});}catch(e){message(e.message);}};
function invalidate(){searchEpoch++;flexEpoch++;plannerClient?.cancel();addressRouter.cancel();$('find-routes').disabled=!router;$('flex-results')?.replaceChildren();companion?.clearPrepared?.();selected=null;routes=[];input=null;$('route-results').innerHTML='';$('review-companion').hidden=true;setPlannerStatus('Ready to find a fresh route. Your accepted trip stays unchanged.');planArrivals?.refresh();renderEndpointDetails();drawMap();}
function currentCatalog(){const state=personal.read().state,visible=visiblePersonalState(state),routePlaces=state.places.filter(p=>visible.templates.some(t=>t.originId===p.id||t.destinationId===p.id));baseCatalog??=endpointCatalog(router.network,bus);const places=[...new Map([...visible.places,...routePlaces].map(p=>[p.id,p])).values()].map(p=>({...p,kind:'saved',routingId:p.routingId??p.stationId,detail:`Saved place � ${baseCatalog.find(s=>s.id===(p.routingId??p.stationId))?.label??'online address routing required'}`}));return [...externalPoints,...places,...baseCatalog];}
function closeSuggestions(key){$(`${key}-suggestions`).hidden=true;$(key).setAttribute('aria-expanded','false');$(key).removeAttribute('aria-activedescendant');}
function renderEndpointDetails(){
  if(!router)return;
  const points=currentCatalog(),operators={SBST:'SBS Transit',SMRT:'SMRT',TTS:'Tower Transit',GAS:'Go-Ahead Singapore'};
  for(const key of ['origin','destination']){
    const host=$(`${key}-stop-details`),point=points.find(p=>p.id===resolved[key]),stopId=point?.routingId??point?.stationId??point?.id;
    const selection=point?JSON.stringify([point.id,stopId]):'';
    if(host.dataset.selection===selection)continue;
    host.dataset.selection=selection;
    const stop=busStopDetails(bus,stopId),field=$(key).closest('.endpoint-field');
    field.classList.toggle('has-bus-stop',!!stop);
    field.querySelector('.field-icon').innerHTML=icon(stop?'bus':key==='origin'?'compass':'location');
    host.hidden=!stop;
    if(!stop){host.replaceChildren();continue;}
    const numbers=[...new Set(stop.services.map(s=>s.serviceNo))].join(', ');
    host.innerHTML=`<p class="bus-service-numbers" aria-label="Bus services">${esc(numbers||'Service numbers unavailable')}</p><details class="bus-stop-details"><summary>Bus stop details</summary><p class="bus-stop-address"><strong>${esc(stop.stopCode)} · ${esc(stop.name)}</strong>${stop.roadName?`<br>${esc(stop.roadName)}`:''}</p><h3>Bus services and directions</h3><ul>${stop.services.map(service=>`<li><strong>${esc(service.directionLabel)}</strong><small>${esc([service.direction!=null?`Direction ${service.direction}`:'',operators[service.operator]??service.operator].filter(Boolean).join(' · '))}</small>${service.visits.length>1?`<small>${service.visits.map(visit=>`Visit ${esc(visit.visitNumber)}${visit.terminatesHere?' · terminates here':''}`).join('; ')}</small>`:service.visits[0]?.terminatesHere?'<small>Terminates here</small>':''}${service.timingSupported===false?'<small>Not available in this route planner.</small>':''}</li>`).join('')||'<li>Service details are unavailable for this stop.</li>'}</ul><p class="field-note">Listed services from the saved stop data. Check live arrivals for upcoming buses.</p></details>`;
  }
}
function choose(key,point){resolved[key]=point.id;$(key).value=`${point.label}${point.kind==='saved'||point.kind==='bus'||!point.routingId?'':` (${point.codes?.join(" / ")??point.routingId})`}`;closeSuggestions(key);invalidate();}
function showSuggestions(key){if(!router)return;catalog=currentCatalog();const list=suggestEndpoints(catalog,$(key).value);suggestionState[key]={items:list,index:-1};const box=$(`${key}-suggestions`);box.innerHTML=list.length?list.map((p,i)=>`<button type="button" class="suggestion-option" id="${key}-option-${i}" role="option" aria-selected="false" data-index="${i}" tabindex="-1">${icon(p.kind==='saved'?'saved':p.kind,22)}<span><strong>${esc(p.label)}</strong><small>${esc(p.detail)}</small></span></button>`).join(''):'<p class="notice">No local match. Try Find a street address below.</p>';box.hidden=false;$(key).setAttribute('aria-expanded','true');box.querySelectorAll('[data-index]').forEach(b=>{b.onpointerdown=e=>e.preventDefault();b.onclick=()=>choose(key,list[Number(b.dataset.index)]);});}
for(const key of ['origin','destination']){const field=$(key);field.oninput=()=>{resolved[key]=null;invalidate();showSuggestions(key);};field.onfocus=()=>{if(!resolved[key])showSuggestions(key);};field.onblur=()=>setTimeout(()=>closeSuggestions(key),120);field.onkeydown=e=>{const s=suggestionState[key];if(e.key==='Escape'){closeSuggestions(key);return;}if(!s||$(`${key}-suggestions`).hidden)return;if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();if(!s.items.length)return;s.index=(s.index+(e.key==='ArrowDown'?1:-1)+s.items.length)%s.items.length;document.querySelectorAll(`#${key}-suggestions [role=option]`).forEach((b,i)=>b.setAttribute('aria-selected',String(i===s.index)));field.setAttribute('aria-activedescendant',`${key}-option-${s.index}`);$(`${key}-option-${s.index}`).scrollIntoView({block:'nearest'});}else if(e.key==='Enter'&&s.index>=0){e.preventDefault();choose(key,s.items[s.index]);}};}
$('swap').onclick=()=>{[resolved.origin,resolved.destination]=[resolved.destination,resolved.origin];[$('origin').value,$('destination').value]=[$('destination').value,$('origin').value];invalidate();};
const form=$('plan-form');const now=singaporeNow();form.elements.date.value=now.departureDate;form.elements.departureTime.value=now.departureTime;form.elements.deadlineDate.value=now.departureDate;const timePickers=mountTimePickers(form);
function setTimeMode(mode){form.elements.timeMode.value=mode;document.querySelectorAll('[data-time]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.time===mode)));$('departure-fields').hidden=mode==='leave-now';$('deadline-fields').hidden=mode!=='arrive-by';$('time-note').textContent=mode==='leave-now'?'Uses the current date and time in Singapore (SGT).':mode==='arrive-by'?'Singapore time (SGT). Filters journeys from your chosen departure against this deadline; does not find a latest departure.':'Choose a date and time in Singapore (SGT). Open the clock to scroll, or use arrow keys in the picker.';}
document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{setTimeMode(b.dataset.time);invalidate();});form.addEventListener('change',e=>{if(e.target.name)invalidate();});
function renderPreferences(){const p=preferences;const style=TRAVEL_STYLES.find(s=>s.id===p.travelStyle);$('edit-preferences').innerHTML=`<span>${icon(p.stepFree?'accessibility':'heart',20)} ${esc(style?.label??'Your travel preferences')}</span><small>${p.walkingLimitMinutes} min walking · ${esc(p.preference.replaceAll('-',' '))}</small>${icon('chevron-right',18)}`;
  $('preferences-content').innerHTML=`<section class="presentation-setting"><h2>Guidance display</h2><label class="check-row"><input id="simple-guidance-toggle" type="checkbox" ${presentation.simpleGuidance?'checked':''}> Simple guidance</label><p>One current instruction, larger controls and less movement. Your trip and travel preferences stay the same.</p></section><div class="style-grid">${TRAVEL_STYLES.map(s=>`<button class="style-card ${s.id===p.travelStyle?'is-selected':''}" data-preset="${s.id}" aria-pressed="${s.id===p.travelStyle}">${icon(s.id==='rachel'?'work':s.id==='arjun'?'heart':'accessibility',30)}<span><strong>${esc(s.label)}</strong><small>${esc(s.explanation)}</small></span></button>`).join('')}</div><form id="preferences-form"><div class="field-pair"><label>Walking limit (minutes)<input type="number" min="0" max="240" name="walkingLimitMinutes" value="${p.walkingLimitMinutes}" required></label><label>Extra time allowed (minutes)<input type="number" min="0" max="120" name="maxExtraMinutes" value="${p.maxExtraMinutes}" required></label></div><label>Route priority<select name="preference">${[['fastest','Fastest arrival'],['fewer-transfers','Fewer transfers'],['less-walking','Less walking'],['quieter','Quieter (data unavailable)']].map(([id,label])=>`<option value="${id}" ${p.preference===id?'selected':''}>${label}</option>`).join('')}</select></label><label class="check-row"><input type="checkbox" name="stepFree" ${p.stepFree?'checked':''}> Require a verified step-free route</label><label class="check-row"><input type="checkbox" name="assistanceRequested" ${p.assistanceRequested?'checked':''}> Prefer assistance and advance planning</label><label>Fare category<select name="fareCategory">${[['adult','Adult card'],['senior','Senior concession card'],['pwd','Disability concession card'],['student','Student concession card']].map(([id,label])=>`<option value="${id}" ${p.fareCategory===id?'selected':''}>${label}</option>`).join('')}</select></label><aside class="wip-banner"><h3>Work in progress — travel information</h3><p>Step-free paths, crowding and shelter are not verified. Preferences cannot establish an accessible path or a quieter train.</p></aside><button class="primary">Save preferences</button><p class="field-note">Applies to future searches. An accepted route changes only after your review.</p></form>`;
  $('simple-guidance-toggle').onchange=e=>{const result=presentationStore.setSimple(e.target.checked);presentation=result.preferences;document.body.classList.toggle('simple-guidance',presentation.simpleGuidance);if(!result.ok)message(result.error);window.dispatchEvent(new CustomEvent('copilot:presentation-changed',{detail:presentation}));companion?.refresh();updateCurrent(companion?.getActive());renderPreferences();};
  document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{try{preferences=preferencesStore.applyPreset(b.dataset.preset);renderPreferences();invalidate();message('Travel style applied. Review and edit its settings below.');}catch(e){message(e.message);}});
  $('preferences-form').onsubmit=e=>{e.preventDefault();try{const f=e.target;preferences=preferencesStore.update({travelStyle:'custom',walkingLimitMinutes:Number(f.elements.walkingLimitMinutes.value),maxExtraMinutes:Number(f.elements.maxExtraMinutes.value),preference:f.elements.preference.value,stepFree:f.elements.stepFree.checked,assistanceRequested:f.elements.assistanceRequested.checked,fareCategory:f.elements.fareCategory.value});renderPreferences();invalidate();message('Preferences saved on this device.');}catch(e){message(e.message);}};
}
function routeLines(r){const services=new Map(r.legs.filter(l=>l.type==='ride').map(leg=>[leg.mode==='bus'?`Bus ${leg.serviceNo}`:publicLineName(leg.routeId),leg]));return [...services].map(([label,leg])=>`<span class="line-pill${leg.mode==='bus'?'':' rail-service-fill'}"${leg.mode==='bus'?'':` style="${railBadgeStyle(leg.routeId,rail?.routes)}"`}>${icon(leg.mode==='bus'?'bus':'train',16)}${esc(label)}</span>`).join('');}
function renderResults(){const selectedIndex=routes.findIndex(r=>r.id===selected?.id);$('route-results').innerHTML=`<div class="section-label"><h2>Let’s find your fit.</h2><span>${routes.length} option${routes.length===1?'':'s'}</span></div><p class="field-note">${esc(input.date)} · depart ${esc(input.departureTime)} SGT. ${input.deadlineTime?`Arrival deadline ${esc(input.deadlineDate)} ${esc(input.deadlineTime)}.`:''}</p>${routes.map((r,i)=>`<button type="button" class="route-card ${r.id===selected?.id?'is-selected':''}" data-route="${i}" aria-pressed="${r.id===selected?.id}"><div class="route-card-top"><strong>${mins(r.totalSeconds)}</strong><span>${i===0?'Suggested route':`Option ${i+1}`}</span>${r.id===selected?.id?icon('check',22):''}</div><div class="route-lines">${routeLines(r)}</div><div class="route-metrics"><span>Arrive ${clock(r.arrivalSeconds)}</span><span>${r.transfers} transfer${r.transfers===1?'':'s'}</span><span>${icon('walk',16)}${mins(r.walkingSeconds)}</span></div></button>`).join('')}<div class="field-pair"><button class="secondary" id="save-route" aria-expanded="false" aria-controls="save-route-form">${icon('saved',20)} Save route</button><button class="primary" id="review-route">Continue ${icon('arrow-right',18)}</button></div><p class="field-note">Save this journey’s start, destination and preferences for next time.</p><div id="route-save-status" role="status"></div><form class="save-route-form" id="save-route-form" hidden><h3>Save to Saved routes</h3><p class="field-note">Choose a name you will recognise. Travel times are checked again when you use it.</p><label>Route name<input name="label" maxlength="80" required value="${esc((catalog.find(p=>p.id===resolved.origin)?.label??name(input.originId))+' to '+(catalog.find(p=>p.id===resolved.destination)?.label??name(input.destinationId)))}"></label><button class="secondary">Save Route on this device</button></form><details class="review-details"><summary>Route details</summary>${renderItineraryTimeline(selected.plan?.route??selected,{name})}<details><summary>Timing assumptions &amp; sources</summary>${(selected?.assumptions??[]).map(a=>`<p class="field-note">${esc(a)}</p>`).join('')}</details></details>`;
  document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{selected=routes[Number(b.dataset.route)];companion?.clearPrepared?.();$('review-companion').hidden=true;renderResults();drawMap();});
  $('save-route').onclick=()=>{$('save-route-form').hidden=!$('save-route-form').hidden;$('save-route').setAttribute('aria-expanded',String(!$('save-route-form').hidden));if(!$('save-route-form').hidden)$('save-route-form').elements.label.focus();};
  $('save-route-form').onsubmit=e=>{e.preventDefault();try{const from=selectedEndpoint('origin'),to=selectedEndpoint('destination');const saved=personal.saveRoute({label:e.target.elements.label.value,origin:from,destination:to,preferences,...input});const route=saved.templates.at(-1);companion.refresh();renderSaved();$('save-route-form').hidden=true;$('save-route').setAttribute('aria-expanded','false');$('route-save-status').innerHTML=`<div class="saved-confirmation"><strong>${icon('check',18)} Saved: ${esc(route.label)}</strong><button class="quiet" type="button" id="view-saved-route">View saved routes ${icon('arrow-right',16)}</button></div>`;$('view-saved-route').onclick=()=>showView('saved');message('Route saved on this device. Find it in Saved routes.');}catch(error){message(error.message);}};
  planArrivals?.refresh();
  $('review-route').onclick=()=>{try{$('review-companion').hidden=false;companion.review();$('review-companion').scrollIntoView({block:'start',behavior:reducedMotion()?'instant':'smooth'});}catch(e){message(e.message);}};
}
function setPlannerStatus(feedback) {
  const status=$('planner-status');
  status.className='planner-status';
  if(typeof feedback==='string'){status.textContent=feedback;return;}
  status.classList.add(feedback.kind==='coverage'?'wip-banner':'route-feedback');
  status.innerHTML=`<h3>${esc(feedback.title)}</h3><p>${esc(feedback.message)}</p>`;
}
function selectedEndpoint(role){const point=currentCatalog().find(p=>p.id===resolved[role]);if(!point||!Number.isFinite(point.lat)||!Number.isFinite(point.lng))throw Error('Select a station, bus stop or resolved address for both endpoints.');return point;}
function externalOption(plan){const route=plan.route,legs=route.steps.map(s=>({...s.source,type:s.type}));return {...route,plan,legs,totalSeconds:route.arrivalSeconds-route.departureSeconds,transfers:Math.max(0,legs.filter(l=>l.type==='ride').length-1),assumptions:[route.provenance],deadlineMet:true};}
async function calculate(timing){const origin=selectedEndpoint('origin'),destination=selectedEndpoint('destination');if(origin.id===destination.id||origin.lat===destination.lat&&origin.lng===destination.lng)throw Error('Choose different starting and destination places.');const query={...preferences,...timing,originId:origin.routingId??origin.id,destinationId:destination.routingId??destination.id,mode:'mixed'};if(!origin.routingId||!destination.routingId){const result=await addressRouter.route({...query,origin,destination,preferences});if(!result)return null;return {...result,input:query,routes:result.plans.map(externalOption)};}return {...await plannerClient.route(query),input:query};}
form.onsubmit=async e=>{e.preventDefault();plannerClient?.cancel();addressRouter.cancel();const epoch=++searchEpoch;flexEpoch++;$('flex-results').replaceChildren();companion?.clearPrepared?.();$('review-companion').hidden=true;selected=null;routes=[];input=null;$('route-results').replaceChildren();planArrivals?.refresh();try{setPlannerStatus('Finding your next connection…');$('find-routes').disabled=true;const result=await calculate(timeInput(Object.fromEntries(new FormData(form))));if(epoch!==searchEpoch||!result)return;input=result.input;routes=result.routes?.filter(r=>r.deadlineMet!==false)??[];selected=routes.find(r=>r.id===result.recommended?.id)??routes[0]??null;if(!selected)setPlannerStatus(result.message??plannerFeedback(result,input,{railCoverage:rail.coverage,busCoverage:bus.coverage}));else{setPlannerStatus(result.message??(preferences.stepFree?{kind:'coverage',title:'Work in progress — step-free coverage',message:'These are timetable options. A continuous step-free path is not verified, so accessible guidance cannot start. Review your needs in Settings or ask station staff for assistance.'}:preferences.preference==='quieter'?{kind:'coverage',title:'Work in progress — crowding information',message:'Crowding data is unavailable. These options use timetable timing and do not identify a quieter train.'}:'Choose a route, then confirm before starting.'));renderResults();}drawMap();}catch(error){if(epoch===searchEpoch&&error.name!=='AbortError')setPlannerStatus(error.message);}finally{if(epoch===searchEpoch)$('find-routes').disabled=!router;}};
function restoreTiming(plan){const fresh=singaporeNow();form.elements.date.value=plan.departureDate??fresh.departureDate;form.elements.departureTime.value=plan.departureTime??fresh.departureTime;form.elements.deadlineDate.value=plan.deadlineDate??fresh.departureDate;form.elements.deadlineTime.value=plan.deadlineTime??plan.deadline??'';setTimeMode(plan.timeMode??'leave-now');timePickers.refresh();}
function reopen(templateId,{quick=false,reverse=false}={}){try{const plan=instantiateTemplate(personal.read().state,templateId,quick?{...singaporeNow(),timeMode:'leave-now',deadlineTime:null,deadlineDate:null}:singaporeNow());if(reverse)[plan.origin,plan.destination]=[plan.destination,plan.origin];preferences=preferencesStore.update(plan.preferences);renderPreferences();catalog=currentCatalog();for(const role of ['origin','destination']){resolved[role]=plan[role].id;$(role).value=plan[role].label;}restoreTiming(plan);invalidate();showView('plan');shortcuts.used(templateId);renderShortcuts();if(quick){message('Checking this commute for Leave now. Review and Start are still required.');form.requestSubmit();}else message(plan.deadlineTime&&Date.parse(`${plan.deadlineDate}T${plan.deadlineTime}:00+08:00`)<Date.now()?'This saved deadline has passed. Choose a new deadline before searching.':'Saved route reopened with fresh departure timing. Review any saved arrival deadline before searching.');}catch(e){message(e.message);}}
function renderSaved(){const result=personal.read(),templates=visiblePersonalState(result.state).templates;$('saved-routes').innerHTML=!result.ok?`<p class="notice">${esc(result.error)}</p>`:templates.length?templates.map(t=>`<article class="saved-route-card"><span class="saved-icon">${icon('saved',26)}</span><div><h2>${esc(t.label)}</h2><p>${esc(result.state.places.find(p=>p.id===t.originId)?.label??'Deleted place')} → ${esc(result.state.places.find(p=>p.id===t.destinationId)?.label??'Deleted place')}</p><div class="chip-row"><button class="secondary" data-open="${esc(t.id)}">Plan again ${icon('arrow-right',16)}</button><button class="quiet" data-pin="${esc(t.id)}">${shortcuts.read().pinned.includes(t.id)?'Unpin':'Pin commute'}</button><button class="quiet" data-delete="${esc(t.id)}">Remove</button></div></div></article>`).join(''):`<div class="empty-state">${icon('saved',44)}<h2>No saved routes yet</h2><p>Find a journey in Plan, choose Save route, then give it a name.</p><button class="secondary" data-go-plan>Find a route</button></div>`;$('saved-routes').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>reopen(b.dataset.open));$('saved-routes').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{try{personal.deleteTemplate(b.dataset.delete);shortcuts.remove(b.dataset.delete);renderSaved();companion.refresh();}catch(e){message(e.message);}});document.querySelector('[data-go-plan]')?.addEventListener('click',()=>showView('plan'));$('saved-routes').querySelectorAll('[data-pin]').forEach(b=>b.onclick=()=>{try{shortcuts.pin(b.dataset.pin,templates.map(t=>t.id));renderSaved();}catch(e){message(e.message);}});renderShortcuts();}
function renderShortcuts(){const state=personal.read().state,cards=shortcuts.cards(visiblePersonalState(state).templates);$('commute-shortcuts').innerHTML=cards.length?`<section aria-label="Saved commute shortcuts"><div class="section-label"><h2>Your commutes</h2><span>Leave now</span></div><div class="commute-card-list">${cards.map(t=>`<article class="commute-shortcut"><strong>${t.pinned?'Pinned · ':''}${esc(t.label)}</strong><p>${esc(state.places.find(p=>p.id===t.originId)?.label??'Deleted place')} → ${esc(state.places.find(p=>p.id===t.destinationId)?.label??'Deleted place')}</p><div class="button-row"><button type="button" class="secondary" data-commute="${esc(t.id)}">Check routes</button><button type="button" class="quiet" data-reverse-commute="${esc(t.id)}">Reverse</button></div></article>`).join('')}</div></section>`:'';for(const b of $('commute-shortcuts').querySelectorAll('[data-commute]'))b.onclick=()=>reopen(b.dataset.commute,{quick:true});for(const b of $('commute-shortcuts').querySelectorAll('[data-reverse-commute]'))b.onclick=()=>reopen(b.dataset.reverseCommute,{quick:true,reverse:true});}
function currentBusContext(){return currentBusArrivalContext(companion?.getActive());}
function mountR5Pages(){
 const execution=()=>resolveCurrentExecution(companion.getActive(),{prepared:companion.getPrepared(),name});
 mapPages=mountMapStationPages({host:$('map-pages'),controlsHost:$('journey-sheet-dock'),mapPanel:$('commute-map'),stationPanel:$('map-station-page'),getExecution:execution,onShowMap:()=>{map?.invalidateSize();},onPageChange:page=>{if(page==='station')journeySheet?.revealSurface();}});
 staffCard=mountStaffCard($('staff-content'),{getActive:companion.getActive,getPrepared:companion.getPrepared,name,onBack:()=>{mapPages.show('map');showView('current');},onStationGuide:()=>{showView('current');mapPages.show('station',{focus:true});}});
 planArrivals=mountBusArrivals($('plan-arrivals'),{getContext:()=>selected?{leg:selected.legs.find(l=>l.type==='ride'&&l.mode==='bus'),date:input.date}:null,getNetwork:()=>bus,name});
 currentArrivals=mountBusArrivals($('current-arrivals'),{getContext:currentBusContext,getNetwork:()=>bus,name});
 document.addEventListener('click',e=>{if(e.target.closest('[data-open-station-guide]'))mapPages.show('station',{focus:true});});
}
$('address-search').onclick=async()=>{const button=$('address-search');button.disabled=true;$('address-results').textContent='Searching OneMap…';try{const results=await addressSearch.search($('address-query').value);if(!results)return;$('address-results').innerHTML=results.length?results.map((p,i)=>`<button type="button" class="address-result secondary" data-address-index="${i}">${esc(p.address)}</button>`).join(''):'No matching address was returned. Try a postal code.';for(const b of $('address-results').querySelectorAll('[data-address-index]'))b.onclick=()=>{const p={...results[Number(b.dataset.addressIndex)],kind:'address',detail:'OneMap address · online routing required'};externalPoints=[p,...externalPoints.filter(x=>x.id!==p.id)].slice(0,12);catalog=currentCatalog();choose($('address-role').value,p);$('address-results').textContent='Address selected. Find routes to check its connection.';};}catch(e){$('address-results').textContent=e.message;}finally{button.disabled=false;}};
$('cancel-address-search').onclick=()=>{addressSearch.cancel();$('address-search').disabled=false;$('address-results').textContent='Search cancelled. Your selected places are unchanged.';};
$('address-query').addEventListener('input',()=>{addressSearch.cancel();$('address-results').replaceChildren();});
$('compare-departures').onclick=async()=>{const token=++flexEpoch,button=$('compare-departures');button.disabled=true;$('flex-results').textContent='Checking alternative connections…';try{const baseline=timeInput(Object.fromEntries(new FormData(form))),choices=departureChoices(baseline,{windowMinutes:Number($('flex-window').value)}),options=[];for(const timing of choices){const result=await calculate(timing);if(token!==flexEpoch)return;const route=result?.routes?.find(r=>r.deadlineMet!==false);if(route)options.push({route,input:result.input});}if(token!==flexEpoch)return;$('flex-results').innerHTML=options.length?options.map(({route,input:q},i)=>{const benefit=departureBenefit(route,q,{holidays:bus.coverage.holidays,calendarStart:bus.coverage.holidayCalendar?.validFrom,calendarEnd:bus.coverage.holidayCalendar?.validThrough});return `<article class="flex-option"><strong>${esc(q.date)} · ${esc(q.departureTime)} SGT</strong><p>Arrive ${clock(route.arrivalSeconds)} · ${mins(route.walkingSeconds)} walking</p><p class="field-note">${esc(benefit.message)}</p><button type="button" class="secondary" data-flex-option="${i}">Use this departure</button></article>`;}).join('')+`<p class="field-note">Connections are recalculated; times remain estimates. No crowding or arrival guarantee. Fare rules reviewed 19 September 2026: <a href="${FARE_FLEX_SOURCE}" target="_blank" rel="noopener noreferrer">Official fare scheme</a>. Discounts are not combined or deducted from spending.</p>`:'No supported alternative fits this window and your constraints. Your current choice is unchanged.';for(const b of $('flex-results').querySelectorAll('[data-flex-option]'))b.onclick=()=>{const option=options[Number(b.dataset.flexOption)];if(Date.parse(`${option.input.date}T${option.input.departureTime}:00+08:00`)<Date.now()){message('This departure has passed. Compare again for fresh choices.');return;}input=option.input;selected=option.route;routes=[selected];restoreTiming({...input,departureDate:input.date});companion?.clearPrepared();$('review-companion').hidden=true;renderResults();drawMap();setPlannerStatus('Alternative departure selected. Review and Start to accept a journey.');};}catch(e){if(token===flexEpoch&&e.name!=='AbortError')$('flex-results').textContent=e.message;}finally{button.disabled=false;}};
function updateCurrent(active){const card=journeyCard(active,{online:navigator.onLine,visible:!document.hidden,name});staffCard?.refresh();mapPages?.refresh();currentArrivals?.refresh();$('trip-peek').hidden=!card||['completed','cancelled'].includes(active.status)||view==='current';if(card){const ended=['completed','cancelled'].includes(active.status);if(ended){$('current-summary').className='current-route-summary';$('current-summary').innerHTML=`<span class="status-pill">${icon(active.status==='completed'?'check':'close',18)} ${active.status==='completed'?'Trip completed':'Trip cancelled'}</span><h2>${esc(publicStationLabel(active.plan.origin.label))} → ${esc(publicStationLabel(active.plan.destination.label))}</h2><p>${active.status==='completed'?'Your trip has ended. Review its fare in Journey spending.':'Guidance and location collection have stopped. You can plan a new trip whenever you are ready.'}</p><button class="secondary" id="plan-after-trip">Plan another journey</button>`;$('plan-after-trip').onclick=()=>showView('plan');drawMap();return;}card.current=publicInstruction(card.current);card.next=publicInstruction(card.next);$('current-summary').className='current-route-summary';$('current-summary').innerHTML=`<div class="journey-metrics"><span>${icon('trip',28)}<strong>${esc(publicStationLabel(active.plan.destination.label))}</strong></span><strong>${clock(card.arrivalSeconds)} <small>estimated</small></strong></div><h2>${esc(card.current)}</h2><p class="guidance-next">Next: ${esc(card.next)}</p>${indoorNoticeHTML(card)}${active.status==='started'?'<div class="current-actions"><button class="secondary" id="manual-correction">Confirm or correct my position</button></div>':''}${card.warnings.map(w=>`<p class="field-note">${esc(w)}</p>`).join('')}`;$('trip-peek').innerHTML=`${icon('trip',24)}<span><strong>Current trip</strong><small>${esc(publicStationLabel(active.plan.destination.label))} · est. ${clock(card.arrivalSeconds)}</small></span>${icon('chevron-right')}`;$('cancel-current-trip-shortcut')?.addEventListener('click',()=>{$('journey-cancel')?.click();$('cancel-trip-confirmation')?.scrollIntoView({block:'center',behavior:'instant'});});$('manual-correction')?.addEventListener('click',()=>{for(let el=$('checkpoint-step')?.parentElement;el;el=el.parentElement)if(el.tagName==='DETAILS')el.open=true;$('checkpoint-step')?.scrollIntoView({block:'center'});$('checkpoint-step')?.focus({preventScroll:true});});}drawMap();}
window.addEventListener('copilot:state-changed',e=>{const before=window.__copilotActiveId;updateCurrent(e.detail.active);window.__copilotActiveId=e.detail.active?.id;if(e.detail.active?.status==='started'&&before!==e.detail.active.id){$('review-companion').hidden=true;const button=$('review-route');if(button)button.hidden=true;showView('current');}});
function drawMap(){if(!mapLayers)return;mapLayers.clearLayers();const active=companion?.getActive(),r=['current','staff'].includes(view)?active?.route?.legacyRoute??active?.route:selected?.plan?.route??selected;const segments=journeyMapSegments(r,{network:router?.network,walking});const drawn=drawRouteSegments(mapLayers,segments),points=drawn.points;
  const endpoints=['current','staff'].includes(view)&&active?[active.plan.origin,active.plan.destination]:['origin','destination'].map(k=>catalog.find(p=>p.id===resolved[k]));endpoints.forEach((p,i)=>{if(!Number.isFinite(p?.lat)||!Number.isFinite(p?.lng))return;points.push([p.lat,p.lng]);L.marker([p.lat,p.lng],{title:p.label,icon:L.divIcon({className:`route-pin ${i?'destination-pin':''}`,html:`<span>${i?'B':'A'}</span>`,iconSize:[34,40],iconAnchor:[17,38]})}).bindPopup(document.createTextNode(p.label)).addTo(mapLayers);});if(['current','staff'].includes(view)&&active?.location){const p=active.location;L.circle([p.latitude,p.longitude],{radius:p.accuracy,color:'#657dc0',fillOpacity:.13}).addTo(mapLayers);}
  drawMap.points=points;
  const note=r?.provider==='onemap'?`© OneMap / SLA · approximate street geometry${drawn.schematic?'; some paths connect stops schematically':''} · indoor guidance unverified`:segments.length?'Transit paths connect stops schematically; they do not show exact roads or tracks. Dotted paths show walking, including reviewed exterior links where available. Indoor guidance remains unverified.':'';
  const caption=routeLegendHTML(segments)+(note?`<details class="map-route-note"><summary>Route details${drawn.schematic?' · approximate paths':''}</summary><p>${esc(note)}</p></details>`:'')+(mapFailed?`<div class="map-status">${icon('layers',16)} ${esc(mapStatus)}<button type="button" class="map-retry" id="retry-street-map">Retry street map</button></div>`:'');
  $('map-caption').hidden=!caption;
  const detailsOpen=$('map-caption').querySelector('details')?.open;
  $('map-caption').innerHTML=caption;
  if(detailsOpen&&$('map-caption').querySelector('details'))$('map-caption').querySelector('details').open=true;
  $('retry-street-map')?.addEventListener('click',()=>streetMap?.retry());if(points.length&&drawMap.last!==r?.id){drawMap.last=r?.id;fitMap();}}
function fitMap(){if(drawMap.points?.length){const desktop=innerWidth>=960;map.fitBounds(drawMap.points,{paddingTopLeft:desktop?[500,95]:[32,90],paddingBottomRight:desktop?[60,65]:[32,50],maxZoom:14,animate:!reducedMotion()});}else map?.setView([1.335,103.86],12,{animate:!reducedMotion()});}
$('recenter-map').onclick=fitMap;
async function initMap(){try{map=L.map('commute-map',{zoomControl:false,scrollWheelZoom:false}).setView([1.335,103.86],12);streetMap=addStreetMap(map,{onStatus:status=>{mapFailed=['unavailable','offline'].includes(status.status);mapStatus=mapFailed?'Street map unavailable':status.status==='loading'?'Loading street map':'';drawMap();}});L.control.zoom({position:'topright'}).addTo(map);drawNetworkOverview(map,rail);mountBusStopMap(map,bus.stops,{onChoose:(role,code)=>{catalog=currentCatalog();const point=catalog.find(p=>p.id===`bus:${code}`);if(point){showView('plan');choose(role,point);}}});mapLayers=L.layerGroup().addTo(map);drawMap();}catch{$('map-caption').hidden=false;$('map-caption').textContent='Map unavailable. Text routes and saved guidance remain usable.';}}
function connection(){$('network-status').innerHTML=`${icon(navigator.onLine?'online':'offline',16)} ${navigator.onLine?'Online':'Offline'}`;updateCurrent(companion?.getActive());}window.addEventListener('online',connection);window.addEventListener('offline',connection);
async function boot(){try{[rail,bus,walking,build]=await Promise.all(['rail-network','bus-network','walking-links','application-build'].map(async n=>{const r=await fetch(`/data/${n}.json`);if(!r.ok)throw Error('Routing data could not be loaded. Reconnect to prepare this device.');return r.json();}));router=createMultimodalRouter(rail,bus,walking);plannerClient=createPlannerClient([rail,bus,walking]);for(const s of router.network.stations)names.set(s.id,s.name);for(const s of router.network.stops)names.set(s.id,`${s.name} (${s.id})`);catalog=currentCatalog();$('coverage-copy').innerHTML=`<p>Rail timetable: ${rail.coverage.startDate}–${rail.coverage.endDate}. All times are in Asia/Singapore. Dates outside coverage stay unavailable.</p><p>All ${bus.stops.length.toLocaleString('en-SG')} source bus stops are searchable. The directory includes ${bus.patterns.length} route directions across ${bus.availability.registryServiceNumberCount} service numbers. Zoom in on the map to select a bus stop.</p><p>${bus.availability.routablePatternCount} bus patterns across ${bus.availability.routableServiceNumberCount} services have at least one supported service day, ${bus.coverage.validFrom}–${bus.coverage.validThrough}. Per-stop weekday, Saturday and Sunday service windows apply where supported. Holiday routing needs a separately verified operator calendar; services without usable frequency data remain listed without journey estimates. Bus timings are bounded estimates, not live vehicle arrivals.</p><aside class="wip-banner"><h3>Work in progress — station connections</h3><p>Same-terminal bus changes use an estimated five-minute walking allowance; confirm the boarding bay. Bus/rail walking links require reviewed exterior connections. Indoor accessibility, door-to-door paths, crowding, shelter and real toilet paths remain unverified.</p></aside>`;
  initMap();companion=mountCompanion({host:$('companion-host'),showHeader:false,showDock:false,sectionHosts:{review:$('review-companion'),saved:$('saved-companion'),sharing:$('caregiver-companion'),spending:$('spending-companion')},getMap:()=>map,getSelected:()=>selected&&input?(selected.plan?{plan:selected.plan}:{route:selected,input,routingContext:acceptJourney(selected,input,build.applicationSha256)}):null,getPlaces:()=>catalog.filter(p=>p.kind!=='saved'),name,getFareOptions:()=>({busNetwork:bus}),onSelectPlan:p=>{preferences=preferencesStore.update(p.preferences);renderPreferences();catalog=currentCatalog();for(const point of [p.origin,p.destination])if(!catalog.some(existing=>existing.id===point.id)&&Number.isFinite(point.lat)&&Number.isFinite(point.lng)){externalPoints=[{...point,routingId:null,kind:'address',detail:'Saved public endpoint · online routing required'},...externalPoints.filter(existing=>existing.id!==point.id)].slice(0,12);}catalog=currentCatalog();for(const role of ['origin','destination']){resolved[role]=p[role].id;$(role).value=p[role].label;}restoreTiming(p);invalidate();showView('plan');},onEndpoint:(role,p)=>{catalog=currentCatalog();choose(role,p);showView('plan');}});
  for(const [key,label] of [['facilities','Station layout & toilets']]){const section=companion.sections[key],details=document.createElement('details'),summary=document.createElement('summary');details.id='station-tools';summary.textContent=label;section.before(details);details.append(summary,section);}
  mountRerouting({host:$('rerouting-host'),demoHost:$('demo-routing'),companion,router,build:build.applicationSha256,name,message});
  mountR5Pages();renderPreferences();renderSaved();updateCurrent(companion.getActive());window.__copilotActiveId=companion.getActive()?.id;$('find-routes').disabled=false;$('planner-status').textContent='Ready for your next connection.';
  if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>message('Offline setup is unavailable. This device is not ready for offline guidance.'));
}catch(e){$('planner-status').textContent=e.message;renderPreferences();}}
new ResizeObserver(entries=>{const nav=entries[0].target,box=nav.getBoundingClientRect();document.body.style.setProperty('--nav-height',`${box.height}px`);document.body.style.setProperty('--nav-columns',box.width<parseFloat(getComputedStyle(document.documentElement).fontSize)*23?'3':'7');}).observe(document.querySelector('.app-nav'));
renderPreferences();boot();
