import {FIXTURE_LAYOUT,fixtureStatuses} from './facility-data.js';
import {findFacilityPath,pathInstructions} from './facility-engine.js';
import {validateJourney as validateV1} from './journey-state.js';
import {JOURNEY_KEY,startJourney,transition,confirmCheckpoint,setPermissions,setApproximateLocation,acceptDetour,stopAction,journeyCard,restoreActive,migrateActive,saveActive,routeFromLegacy,makePlan,validatePlan,proposeRoute,acceptRoute} from './journey-v2.js';
import {SharingClient,enablePush,disablePush} from './sharing-client.js';
import {mountFacilities} from './facility-ui.js';
import {mountPersonal} from './personal-ui.js';
import {mountExpenditure,fareEstimateHTML} from './fare-ui.js';
import {estimatePlanFare} from './fares.js';
import {createLocationAssistance,locationDescription} from './location-assistance.js';
import {createOfflineReadiness,OFFLINE_LIMITS} from './offline-readiness.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=s=>`${String(Math.floor(s/3600)%24).padStart(2,'0')}:${String(Math.floor(s%3600/60)).padStart(2,'0')}${s>=86400?' (+1 day)':''}`;
export function mountCompanion({getSelected=()=>null,getPlaces=()=>[],onSelectPlan=()=>{},onEndpoint=()=>{},name=id=>id,getMap=()=>null,getFareOptions=()=>({}),getRoutingContext=()=>null,mode='real',host:mountHost=null,sectionHosts={},showHeader=true,showDock=true}={}){
  if(document.querySelector('#companion'))return;
  const style=document.createElement('link');style.rel='stylesheet';style.href='/src/copilot.css';document.head.append(style);
  const host=document.createElement('section');host.id='companion';host.className='copilot';host.setAttribute('aria-label','Journey companion');if(mountHost)mountHost.append(host);else document.querySelector('#app').after(host);
  host.innerHTML=`<p class="eyebrow">YOUR JOURNEY COMPANION</p><h2>Prepare, travel, stay connected.</h2><p>Use the journey you selected above. Saved places, assistance, sharing and spending stay together.</p><nav aria-label="Companion tools"><a href="#companion-plan">Prepare</a><a href="#companion-facilities">Station &amp; toilets</a><a href="#companion-sharing">Caregiver</a><a href="#companion-places">Saved places</a><a href="#companion-fares">Spending</a></nav><p id="companion-message" role="status" aria-live="polite"></p>
  <section id="companion-plan" class="companion-panel"><h3>Review your trip</h3><button id="review-selected" class="primary">Review selected journey</button><label><input type="checkbox" id="need-step-free"> Require a verified step-free path</label><p class="muted">Station-level timing allowances do not verify lifts or indoor accessibility.</p><label>Fare category<select id="fare-category"><option value="adult">Adult card</option><option value="senior">Senior concession card</option><option value="pwd">Persons with disabilities concession card</option><option value="student">Student concession card</option></select></label><div id="companion-preview"></div><div id="companion-active"></div></section>
  <section id="companion-map-panel" class="companion-panel"><h3>Journey map &amp; nearby facilities</h3><button id="map-find-toilet" class="primary">Find a toilet</button><button id="map-layout">Station layout</button><div id="companion-map" aria-label="OpenStreetMap journey and toilet locations"></div><p id="companion-map-note">Geographic overview. Indoor diagrams have a separate coverage label.</p></section>
  <section id="companion-facilities" class="companion-panel"></section><section id="companion-sharing" class="companion-panel"></section><section id="companion-places" class="companion-panel"></section><section id="companion-fares" class="companion-panel"></section>`;
  const dock=document.createElement('aside');dock.className='ongoing-card';dock.hidden=true;dock.setAttribute('aria-label','Ongoing journey');document.body.append(dock);
  const $=id=>document.getElementById(id);
  const sections={review:$('companion-plan'),current:$('companion-active'),map:$('companion-map-panel'),facilities:$('companion-facilities'),sharing:$('companion-sharing'),saved:$('companion-places'),spending:$('companion-fares')};
  // Move the existing controllers, never mount a second copy for another screen.
  if(sectionHosts.review){host.prepend(sections.current);sections.current.classList.add('companion-panel');}
  for(const [key,target]of Object.entries(sectionHosts))if(sections[key]&&target)target.append(sections[key]);
  if(!showHeader)for(const node of [...host.children])if(node.matches('p.eyebrow,h2,nav')||node.tagName==='P'&&node.id!=='companion-message')node.remove();
  let deviceStorage;try{deviceStorage=window.localStorage;}catch{deviceStorage={getItem:()=>null,setItem:()=>{throw Error('Browser storage unavailable');},removeItem:()=>{throw Error('Browser storage unavailable');}};}
  let active=migrateActive(deviceStorage,validateV1,name).state,prepared=null,preparedContext=null,shareView=null,map=null,mapLayers=null,externalMap=false,facilities,personal,spending,toiletMarkers=[],storageEnabled=true,locationState={collecting:false,reason:''};
  const sharing=new SharingClient(deviceStorage);const incoming=sharing.useFragment();
  function message(text){$('companion-message').textContent=text;window.dispatchEvent(new CustomEvent('copilot:message',{detail:{text}}));}
  function revealSection(section){const element=sections[section];for(let node=element?.parentElement;node;node=node.parentElement)if(node.tagName==='DETAILS')node.open=true;window.dispatchEvent(new CustomEvent('copilot:open-section',{detail:{section}}));element?.scrollIntoView({block:'start'});}
  const locationAssistance=createLocationAssistance({geolocation:navigator.geolocation,canCollect:()=>active?.status==='started',isVisible:()=>!document.hidden,onState:state=>{locationState=state;renderLocationStatus();},onPosition:position=>{try{commit(setApproximateLocation(active,position),{locationOnly:true});}catch(error){message(error.message);}}});
  const offline=createOfflineReadiness({storage:deviceStorage,key:JOURNEY_KEY,serviceWorker:navigator.serviceWorker,onChange:renderOffline});
  const run=fn=>async()=>{try{await fn();}catch(error){message(error.message);}};
  let privacySync=null;
  function localPrivacy(changes){if(active)commit({...active,revision:active.revision+1,updatedAt:Date.now(),location:null,permissions:{...active.permissions,...changes,geolocation:'stopped'}},{upload:false});}
  function pendingPrivacy(action){if(!sharing.session?.travellerToken)return;if(sharing.session.pendingPrivacyAction==='revoke'&&action!=='revoke')return;sharing.session={...sharing.session,pendingPrivacyAction:action};sharing.persist();}
  async function syncPrivacy(){
    if(privacySync)return privacySync;
    privacySync=(async()=>{
      while(sharing.session?.pendingPrivacyAction){
        const action=sharing.session.pendingPrivacyAction,id=sharing.session.id;
        try{
          const result=action==='revoke'?await sharing.revoke():await sharing.permissions({progress:active?.permissions.progress===true,location:false},active?.permissions.paused===true);
          if(sharing.session?.id!==id)return;
          if(sharing.session.pendingPrivacyAction===action){delete sharing.session.pendingPrivacyAction;sharing.persist();}
          shareView={...result,viewedAt:Date.now()};renderSharing();
          message(action==='revoke'?'Caregiver access removed on the server. Old queued locations cannot restart sharing.':'Location collection and geographic sharing stopped. Enable local assistance and caregiver geographic sharing separately if needed.');
        }catch(error){renderSharing();throw Error(`${action==='revoke'?'Caregiver revocation':'Location-sharing stop'} is pending on the server. Collection is stopped on this device. Reconnect or use Retry. ${error.message}`);}
      }
    })();
    try{return await privacySync;}finally{privacySync=null;}
  }
  async function stopLocation(){stopGeo();localPrivacy({location:false});pendingPrivacy('stop-location');renderSharing();if(sharing.session?.pendingPrivacyAction)await syncPrivacy();else message('Location collection stopped on this device.');}
  async function revokeAccess(){stopGeo();localPrivacy({revoked:true,progress:false,location:false,paused:true});pendingPrivacy('revoke');renderSharing();await syncPrivacy();}
  function commit(next,{upload=true,locationOnly=false}={}){
    // Generic checkpoints lack the confirmed civil time/walking budget needed by
    // the timetable comparator. A previous routing seed must not outlive them.
    if(!locationOnly&&active?.id===next?.id&&active?.routingContext&&JSON.stringify(next.routingContext)===JSON.stringify(active.routingContext)){
      const routeShape=route=>JSON.stringify({id:route.id,steps:route.steps,legacyRoute:route.legacyRoute,accessibility:route.accessibility});
      if(routeShape(next.route)!==routeShape(active.route))next={...next,routingContext:null};
      else if(JSON.stringify(next.progress)!==JSON.stringify(active.progress)||next.status!==active.status)next={...next,routingContext:{...next.routingContext,revision:next.routingContext.revision+1,progress:{...next.routingContext.progress,kind:'unknown'},proposal:null}};
    }
    const started=next?.id!==active?.id;active=next;if(started)storageEnabled=true;
    locationAssistance.lifecycleChanged();
    if(storageEnabled&&!saveActive(deviceStorage,active))message('Device storage unavailable. Keep this tab open; guidance has not been saved.');
    if(locationOnly){renderLocationStatus();drawMap();}else{renderActive();facilities?.refresh();}
    offline.setTrip(active);
    window.dispatchEvent(new CustomEvent('copilot:state-changed',{detail:{active,started,locationOnly}}));
    if(upload&&active&&sharing.session?.travellerToken)sharing.update(active).catch(e=>message(`Sharing not updated: ${e.message}. Reconnect and refresh before retrying.`));
  }
  function selectedPlan(){const selected=getSelected();if(!selected?.route&&!selected?.plan)throw Error('Choose a feasible journey in the planner first.');const p=selected.plan?structuredClone(selected.plan):routeFromLegacy(selected.route,selected.input,{name,mode,source:mode==='replay'?'Labelled replay assumptions':'Imported timetable / estimated station access; see source coverage'});preparedContext=selected.routingContext??getRoutingContext();if(!showHeader){$('need-step-free').checked=p.preferences.stepFree;$('fare-category').value=p.preferences.fareCategory??'adult';}else{p.preferences.stepFree=$('need-step-free').checked;p.preferences.fareCategory=$('fare-category').value;}const places=getPlaces();for(const key of ['origin','destination']){const found=places.find(x=>x.id===p[key].id);if(found)p[key]={...p[key],...found};}return p;}
  function renderLocationStatus(){const status=$('location-status');if(status)status.textContent=locationDescription(active?.location,locationState);const button=$('locate-once');if(button){button.disabled=active?.status!=='started'||locationState.collecting;button.textContent=locationState.collecting?'Location assistance on':'Enable location assistance';}}
  function renderOffline(state){const box=$('trip-offline');if(!box)return;box.innerHTML=`<p id="offline-readiness" role="status" data-ready="${state.ready}"><strong>${esc(state.reason)}</strong>${state.savedAt?` · Saved ${esc(new Date(state.savedAt).toLocaleString('en-SG',{timeZone:'Asia/Singapore'}))} SGT`:''}</p><p class="muted">${esc(OFFLINE_LIMITS)}</p>${active?`${state.durable?'<button id="remove-offline-trip">Remove saved trip from this device</button>':'<button id="save-offline-trip">Save current trip on this device</button>'}<button id="check-offline-trip">Check offline availability</button>`:''}`;
    $('check-offline-trip')?.addEventListener('click',()=>offline.verify());
    $('save-offline-trip')?.addEventListener('click',()=>{storageEnabled=true;commit(active,{upload:false});offline.verify();});
    $('remove-offline-trip')?.addEventListener('click',()=>{try{deviceStorage.removeItem(JOURNEY_KEY);deviceStorage.removeItem('commute-copilot-active-journey-v1');if(deviceStorage.getItem(JOURNEY_KEY)!==null)throw Error();storageEnabled=false;offline.setTrip(active);message('Saved trip removed. Guidance remains in this tab until it closes; Saved Routes and caregiver permissions are unchanged.');}catch{message('The saved trip could not be removed. Check browser storage access and retry.');offline.storageChanged();}});
  }
  function fareText(plan){try{const fare=estimatePlanFare(plan);return fare?.totalCents!=null?`Estimated SGD ${(fare.totalCents/100).toFixed(2)} · ${fare.explanation??fare.reason??'see fare assumptions'}`:fare?.reason??'Fare unavailable: official distance required; enter actual charged amount after completion.';}catch{return 'Fare unavailable for this itinerary; official distance and transfer validation required.';}}
  function renderPreview(){const p=prepared;if(!p){$('companion-preview').innerHTML='';return;}$('companion-preview').innerHTML=`<article class="c-route"><h4>${esc(p.origin.label??p.origin.id)} → ${esc(p.destination.label??p.destination.id)}</h4><p>${esc(p.mode==='replay'?'LABELLED REPLAY · ':'')}${esc(p.departureDate)} ${esc(p.departureTime)} SGT · planned arrival ${time(p.route.arrivalSeconds)}</p><p>${esc(p.route.provenance)}. Accessibility: ${esc(p.route.accessibility)}.</p>${fareEstimateHTML(p,getFareOptions())}<p>${p.stops.length?`${p.stops.length} planned stop(s); recheck their usable paths before departure.`:'No intermediate stops.'}</p><details><summary>Full journey for review</summary><ol>${p.route.steps.map(s=>`<li>${esc(s.text)}</li>`).join('')}</ol></details><label class="location-choice"><input type="checkbox" id="enable-local-assistance"> Use foreground location assistance during this trip</label><p class="muted">Optional approximate position while this page is visible. It does not confirm platforms, boarding or arrival. Caregiver sharing stays off unless separately enabled. Manual correction is always available.</p><button id="start-companion" class="primary">Start Journey</button><button id="prepare-link">Create recipient link</button><button id="prepare-toilet">Plan a toilet stop</button></article>`;
    $('start-companion').onclick=run(async()=>{if(active&&!['completed','cancelled'].includes(active.status))throw Error('Finish or cancel your current journey before starting another.');const useLocation=$('enable-local-assistance').checked;const next=startJourney(prepared);if(preparedContext)next.routingContext=structuredClone(preparedContext);commit(next);if(useLocation)locationAssistance.start();message('Journey started. Confirm each checkpoint yourself; times do not establish arrival.');});
    $('prepare-link').onclick=run(async()=>{await sharing.create(prepared);shareView=await sharing.read();renderSharing();message('Recipient link created. The recipient must review and accept; progress and location permissions start off.');revealSection('sharing');});
    $('prepare-toilet').onclick=()=>openFacilities('toilets');
  }
  function openFacilities(view){facilities?.open(active?.progress?.checkpoint?.stationId??active?.plan.origin.stationId??prepared?.origin?.stationId??prepared?.origin?.id??null,view);revealSection('facilities');}
  $('review-selected').onclick=run(()=>{prepared=selectedPlan();renderPreview();});$('need-step-free').onchange=()=>{if(prepared){prepared.preferences.stepFree=$('need-step-free').checked;renderPreview();}};
  $('fare-category').onchange=()=>{if(prepared){prepared.preferences.fareCategory=$('fare-category').value;renderPreview();}};
  $('map-find-toilet').onclick=()=>openFacilities('toilets');$('map-layout').onclick=()=>openFacilities('layout');
  function renderActive(){
    const card=journeyCard(active,{online:navigator.onLine,visible:!document.hidden});dock.hidden=!card||!showDock;document.body.classList.toggle('has-companion-trip',!!card&&showDock);
    if(!card){$('companion-active').innerHTML='<p>No journey has been started.</p>';return;}
    const ended=['completed','cancelled'].includes(active.status),d=active.detour;
    $('companion-active').innerHTML=`<h3>${esc(active.status)} · ${esc(active.plan.destination.label??active.plan.destination.id)}</h3><p>${active.plan.mode==='replay'?'<strong>LABELLED REHEARSAL · separate from personal spending</strong>':''} Route revision ${active.revision}. ${esc(active.route.provenance)}</p>${fareEstimateHTML(active,getFareOptions())}<p>Last confirmed: ${esc(active.progress.checkpoint?.label??'unknown')} ${active.progress.confirmedAt?'at '+new Date(active.progress.confirmedAt).toLocaleTimeString('en-SG',{timeZone:'Asia/Singapore'}):''}. GPS never establishes a floor.</p>
    ${!ended?`<label>Correct my position - current action (manual confirmation)<select id="checkpoint-step">${active.route.steps.map((s,i)=>`<option value="${i}" ${active.progress.stepIndex===i?'selected':''}>${esc(s.text)}</option>`).join('')}</select></label><button id="confirm-step">I am here</button><button id="journey-pause">${active.status==='paused'?'Resume':'Pause'} journey</button><button id="journey-cancel">Cancel journey</button><button id="journey-finish">I have arrived · Finish journey</button><p>Finish only at your original destination. Estimated arrival does not finish a trip.</p><button id="locate-once">Enable location assistance</button><button id="clear-location">Stop location collection</button><p id="location-status">${active.location?`Approximate · accuracy ±${Math.round(active.location.accuracy)} m · ${esc(new Date(active.location.timestamp).toISOString())}`:`Location ${esc(active.permissions.geolocation)}. Manual checkpoints work without location permission.`}</p>`:'<p>Location collection has stopped. Completed personal journeys can be reconciled in Spending.</p>'+ (active.status==='completed'?'<button id="retry-fare">Record completed fare / retry saving</button>':'')}
    <div id="trip-offline"></div>${d?`<div class="c-note"><strong>Intermediate toilet stop: ${esc(d.toiletId)} · ${esc(d.status)}</strong><p>Assumed break ${d.breakMinutes} minutes; original destination ${esc(active.plan.destination.label)}. ${esc(d.fareImpact?.message??d.fareImpact)}</p>${!ended&&!['resumed','cancelled'].includes(d.status)?'<button id="stop-reached">Reached toilet</button><button id="stop-resume">Resume journey</button><button id="stop-cancel">Cancel stop</button>':''}</div>`:''}
    ${active.proposal?`<div class="c-note"><h4>Proposed route change</h4><p>${esc(active.proposal.reason)}. Arrival ${time(active.route.arrivalSeconds)} → ${time(active.proposal.route.arrivalSeconds)}; walking change ${Math.round((active.proposal.route.walkingSeconds-active.route.walkingSeconds)/60)} min.</p><button id="accept-proposal">Accept revised route</button><button id="decline-proposal">Keep current route</button></div>`:''}`;
    const expanded=dock.querySelector('details')?.open;
    dock.innerHTML=`<details ${expanded?'open':''}><summary><span class="arrival">${ended?esc(active.status):'Est. '+time(card.arrivalSeconds)}</span><strong>${esc(card.current)}</strong><span class="next">Next: ${esc(card.next)}</span></summary><p>Step ${active.progress.stepIndex+1} of ${active.route.steps.length} · route revision ${card.revision}${active.routeRevisions.length?' · journey updated':''}</p>${card.warnings.map(w=>`<p class="freshness">${esc(w)}</p>`).join('')}<button data-layout>Station layout</button><button data-toilet>Find a toilet</button><button data-details>Journey actions</button></details>`;
    dock.querySelector('[data-layout]').onclick=()=>openFacilities('layout');dock.querySelector('[data-toilet]').onclick=()=>openFacilities('toilets');dock.querySelector('[data-details]').onclick=()=>$('companion-active').scrollIntoView();
    if(!ended){$('confirm-step').onclick=run(()=>commit(confirmCheckpoint(active,{stepIndex:Number($('checkpoint-step').value),kind:active.route.steps[Number($('checkpoint-step').value)].type==='ride'?'onboard':'checkpoint'})));
      $('journey-pause').onclick=run(()=>{stopGeo();commit(transition(active,active.status==='paused'?'resume':'pause'));});
      $('journey-cancel').onclick=run(()=>{stopGeo();commit(transition(active,'cancel'));renderSharing();});
      $('journey-finish').onclick=run(()=>{stopGeo();commit(transition(active,'finish'));const result=spending?.complete(active);renderSharing();message(result?.ok?'Arrival confirmed once. Fare remains an estimate until you confirm the charge.':'Arrival confirmed, but spending could not be saved: '+result?.error);});
      $('locate-once').onclick=run(()=>locationAssistance.start());$('clear-location').onclick=run(stopLocation);
    }
    $('retry-fare')?.addEventListener('click',()=>{const r=spending?.complete(active);message(r?.ok?'Completed journey recorded once.':r?.error);});
    for(const [id,action]of [['stop-reached','reached'],['stop-resume','resume'],['stop-cancel','cancel']])$(id)?.addEventListener('click',run(()=>commit(stopAction(active,action))));
    $('accept-proposal')?.addEventListener('click',run(()=>commit(acceptRoute(active))));$('decline-proposal')?.addEventListener('click',()=>commit({...active,proposal:null}));renderLocationStatus();renderOffline(offline.getState());drawMap();
  }
  function stopGeo(){locationAssistance.stop();if(active)active={...active,permissions:{...active.permissions,geolocation:'stopped'}};}
  function renderSharing(){const s=sharing.session,p=active?.permissions;const ended=!active||['completed','cancelled'].includes(active.status);$('companion-sharing').innerHTML=`<h3>Caregiver preparation &amp; sharing</h3><p>Create a link after reviewing a planned trip. Addresses included in that trip will be sent to the sharing service. Links expire; the recipient must explicitly accept.</p><p class="muted">Latest checkpoint and optional latest position only. Sharing data is removed within 24 hours of completion or expiry. Background location is unavailable; the page must be visible. The hosted site's audience restriction still applies.</p>
    ${s?`<p>Role: ${esc(s.role)} · ${esc(shareView?.status??'awaiting refresh')} · server revision ${esc(s.revision)}.</p><button id="refresh-share">Refresh shared trip</button><button id="delete-share">Delete shared data</button>${s.editorToken?'<button id="propose-plan">Propose currently reviewed plan</button>':''}<div id="share-links"></div><div id="shared-view"></div>${s.role==='traveller'?`<div class="permissions"><p><strong>Separate permissions</strong> · ${s.accessRevoked?'ACCESS REMOVED ON SERVER':s.pendingPrivacyAction==='revoke'?'REVOCATION PENDING · collection stopped on this device':s.pendingPrivacyAction==='stop-location'?'LOCATION STOP PENDING ON SERVER · collection stopped on this device':p?.paused?'SHARING PAUSED':'sharing controlled below'}</p>${s.pendingPrivacyAction?'<button id="retry-privacy">Retry pending privacy change</button>':''}<label><input id="share-progress" type="checkbox" ${p?.progress?'checked':''} ${ended||p?.revoked?'disabled':''}> Share progress and accepted route changes</label><label><input id="share-location" type="checkbox" ${p?.location?'checked':''} ${ended||p?.revoked?'disabled':''}> Share geographic location (accuracy and timestamp)</label><button id="apply-sharing" ${ended||p?.revoked?'disabled':''}>Apply permissions</button><button id="pause-sharing" ${ended||p?.revoked?'disabled':''}>${p?.paused?'Resume':'Pause'} sharing</button><button id="revoke-sharing" ${s.accessRevoked?'disabled':''}>${s.pendingPrivacyAction==='revoke'?'Retry removing':'Remove'} caregiver access</button></div>`:''}<button id="enable-push">Enable journey notifications</button><button id="disable-push">Disable notifications</button>`:'<p>No shared trip on this device. Review the selected journey, then create a recipient link.</p>'}
    <p>Ordinary Web Push is optional and delivery is not guaranteed. iPhone/iPad requires a supported Home Screen web app and permission. Native Dynamic Island is not implemented.</p>`;
    if(!s)return;const links=sharing.links();$('share-links').innerHTML=Object.entries(links).filter(([,url])=>url).map(([key,url])=>`<p><button data-copy="${key}">Copy ${key==='invite'?'recipient':'caregiver view'} link</button><button data-share="${key}">Share ${key} link</button><button data-qr="${key}">Show ${key} QR</button></p>`).join('')+'<div class="qr" id="share-qr"></div>';
    sections.sharing.querySelectorAll('[data-copy]').forEach(b=>b.onclick=run(async()=>{await navigator.clipboard.writeText(links[b.dataset.copy]);message('Link copied. Keep recipient and caregiver links separate.');}));
    sections.sharing.querySelectorAll('[data-share]').forEach(b=>b.onclick=run(async()=>{if(navigator.share)await navigator.share({title:'Commute Copilot trip',url:links[b.dataset.share]});else{await navigator.clipboard.writeText(links[b.dataset.share]);message('System share unavailable; link copied.');}}));
    sections.sharing.querySelectorAll('[data-qr]').forEach(b=>b.onclick=run(async()=>{const {default:qrcode}=await import('/vendor/qrcode.mjs');const qr=qrcode(0,'M');qr.addData(links[b.dataset.qr]);qr.make();$('share-qr').innerHTML=qr.createSvgTag({cellSize:3,margin:4,scalable:true});}));
    $('refresh-share').onclick=run(refreshShare);$('delete-share').onclick=run(async()=>{await sharing.delete();stopGeo();if(active)commit({...active,permissions:{...active.permissions,revoked:true,progress:false,location:false},location:null},{upload:false});shareView=null;renderSharing();});
    $('propose-plan')?.addEventListener('click',run(async()=>{if(!prepared)throw Error('Review a proposed plan first.');await sharing.propose(prepared);await refreshShare();message('Proposed edit saved. Traveller must review and accept it.');}));
    $('apply-sharing')?.addEventListener('click',run(async()=>{const consent={progress:$('share-progress').checked,location:$('share-location').checked};if(sharing.session.pendingPrivacyAction)await syncPrivacy();await sharing.permissions(consent,false);commit(setPermissions(active,{...consent,paused:false},Date.now(),{preserveLocalLocation:locationState.collecting}));renderSharing();}));
    $('pause-sharing')?.addEventListener('click',run(async()=>{const paused=!active.permissions.paused;await sharing.permissions({progress:active.permissions.progress,location:active.permissions.location},paused);commit(setPermissions(active,{paused},Date.now(),{preserveLocalLocation:locationState.collecting}));renderSharing();}));
    $('revoke-sharing')?.addEventListener('click',run(revokeAccess));$('retry-privacy')?.addEventListener('click',run(syncPrivacy));
    $('enable-push').onclick=run(async()=>{await enablePush(s);message('Notification subscription registered. External delivery depends on server configuration and browser support.');});$('disable-push').onclick=run(async()=>{await disablePush(s);message('Notifications disabled.');});renderSharedView();
  }
  function renderSharedView(){if(!shareView||!$('shared-view'))return;const p=shareView.acceptedPlan??shareView.proposedPlan;const recipient=sharing.session.role==='recipient';$('shared-view').innerHTML=`${p?`<h4>${esc(p.origin?.label??p.origin?.id)} → ${esc(p.destination?.label??p.destination?.id)}</h4><p>${esc(p.departureDate)} ${esc(p.departureTime)} · ${p.mode==='replay'?'LABELLED REHEARSAL':'planned journey'}</p><ol>${(p.route?.steps??[]).map(s=>`<li>${esc(s.text)}</li>`).join('')}</ol>`:'<p>Progress and route details are not currently authorised.</p>'}<p>Last checked ${shareView.viewedAt?esc(new Date(shareView.viewedAt).toISOString()):'unknown'} · ${esc(shareView.locationState??'location not shared')}. Foreground refresh only; this is the last received state.</p><p>Consent: progress ${shareView.consent?.progress?'on':'off'}; location ${shareView.consent?.location?'on':'off'}${shareView.sharingPaused?' · paused':''}.</p>${shareView.progress?`<p>Latest authorised update: ${esc(shareView.progress.status)} · checkpoint ${esc(shareView.progress.checkpoint?.label??'not confirmed')} · route revision ${esc(shareView.progress.routeRevision)} · estimated arrival ${typeof shareView.progress.eta==='number'?time(shareView.progress.eta):esc(shareView.progress.eta??'unavailable')} · updated ${esc(new Date(shareView.progress.updatedAt).toISOString())}</p>`:''}${shareView.location?`<p>Latest approximate location: ${esc(shareView.location.latitude)}, ${esc(shareView.location.longitude)} · ±${esc(shareView.location.accuracy)} m · ${esc(new Date(shareView.location.timestamp).toISOString())}. Last known; no underground floor inference.</p>`:''}${recipient?'<button id="accept-invite" class="primary">Accept this trip · sharing stays off</button>':''}${sharing.session.role==='traveller'&&shareView.proposedPlan&&JSON.stringify(shareView.proposedPlan.route)!==JSON.stringify(active?.plan.route)?'<button id="review-edit">Review caregiver proposal</button>':''}`;
    $('accept-invite')?.addEventListener('click',run(async()=>{if(active&&!['completed','cancelled'].includes(active.status))throw Error('Finish or cancel the current journey before accepting this invitation.');if(!validatePlan(p))throw Error('Unsupported shared plan.');const next=startJourney(p);const paired=await sharing.accept();next.sharing={shareId:paired.id,planId:p.id};commit(next,{upload:false});await refreshShare();message('Trip accepted. Progress and geographic sharing are both off.');}));
    const recoveryPlan=shareView.acceptedPlan,s=sharing.session;
    if(s.role==='traveller'&&shareView.id===s.id&&validatePlan(recoveryPlan)&&!['completed','cancelled'].includes(shareView.status)&&!s.accessRevoked&&(!active||['completed','cancelled'].includes(active.status))&&active?.plan.id!==recoveryPlan.id){
      const button=document.createElement('button');button.id='start-accepted-trip';button.className='primary';button.textContent='Start accepted trip';$('shared-view').append(button);
      button.onclick=run(async()=>{if(sharing.session.id!==shareView.id||sharing.session.role!=='traveller'||shareView.acceptedPlan?.id!==recoveryPlan.id)throw Error('The paired trip changed; refresh and review it again.');if(active&&!['completed','cancelled'].includes(active.status))throw Error('Finish or cancel the current journey first.');const next=startJourney(recoveryPlan);await sharing.permissions({progress:false,location:false},false);next.sharing={shareId:sharing.session.id,planId:recoveryPlan.id};commit(next,{upload:false});renderSharing();message('Accepted trip started on this device. Progress and geographic sharing are both off.');});
    }
    $('review-edit')?.addEventListener('click',run(()=>{const p=shareView.proposedPlan;if(!validatePlan(p))throw Error('Invalid proposed plan.');if(p.destination.id!==active.plan.destination.id)throw Error('The proposed destination differs. Finish or cancel this trip before accepting a new destination.');commit(proposeRoute(active,p.route,'Caregiver proposal · review before accepting'),{upload:false});$('companion-active').scrollIntoView();}));
  }
  async function refreshShare(){try{shareView=await sharing.read();if(shareView)shareView.viewedAt=Date.now();renderSharing();}catch(e){if(e.status===404||e.status===403){shareView=null;renderSharing();}throw e;}}
  function fixtureStart(layout){preparedContext=null;if(active&&!['completed','cancelled'].includes(active.status))throw Error('Finish or cancel the current journey before starting the rehearsal.');const id=layout?.layoutId??layout?.id??'fixture-interchange';const fixturePath=findFacilityPath(FIXTURE_LAYOUT,{from:FIXTURE_LAYOUT.defaultFrom,to:FIXTURE_LAYOUT.defaultTo,profile:{stepFree:true},statuses:fixtureStatuses('none'),allowFixtures:true});const fixtureSteps=pathInstructions(FIXTURE_LAYOUT,fixturePath).map((text,i)=>({id:'fixture-step-'+i,text,durationSeconds:fixturePath.edges[i].seconds,facilityId:fixturePath.edges[i].facilityId}));const now=new Date(),date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore'}).format(now);prepared=makePlan({origin:{id:'fixture-origin',label:'Rehearsal entrance',stationId:id},destination:{id:'fixture-destination',label:'Rehearsal destination entrance',stationId:id},date,departureTime:'10:00',mode:'replay',preferences:{stepFree:true,walkingLimitMinutes:60},route:{id:'fixture-corridor',departureSeconds:36000,arrivalSeconds:36000+fixturePath.seconds,walkingSeconds:fixturePath.walkingSeconds,facilityPathSeconds:fixturePath.seconds,facilityPathWalkingSeconds:fixturePath.walkingSeconds,accessibility:'fixture',provenance:'Synthetic connected graph for workflow testing; not a real floor plan',steps:fixtureSteps}});renderPreview();window.dispatchEvent(new CustomEvent('copilot:prepared',{detail:{plan:prepared}}));message('Rehearsal prepared. Review and start it, or create a recipient link for a second browser.');}
  facilities=mountFacilities({host:$('companion-facilities'),getJourney:()=>(active&&!['completed','cancelled'].includes(active.status)?active:null)??(prepared?{plan:prepared,route:prepared.route,progress:{kind:'unknown',checkpoint:null},stops:prepared.stops}:null),onStartFixture:fixtureStart,onAcceptDetour:preview=>{try{if(active&&!['completed','cancelled'].includes(active.status)){commit(acceptDetour(active,preview));message('Toilet detour accepted. The original destination is retained.');}else if(prepared){prepared.stops=[{type:'toilet',facilityId:preview.toiletId,preview}];renderPreview();message('Planned toilet stop saved. Recheck conditions and accept its path when starting.');}else throw Error('Review a trip first.');}catch(e){message(e.message);}},onCheckpoint:checkpoint=>{try{if(active&&!['completed','cancelled'].includes(active.status))commit(confirmCheckpoint(active,{...checkpoint,nodeId:checkpoint.nodeId??checkpoint.id}));}catch(e){message(e.message);}},onStopAction:action=>{try{commit(stopAction(active,action));}catch(e){message(e.message);}},onFacilityChange:change=>{if(active){const blocked=change.detourAssessment?!change.detourAssessment.feasible:active.detour?.blocked;let next={...active,revision:active.revision+1,facilityScenario:change.scenario,facilityBlocked:change.comparison?.revised?.feasible===false,detour:active.detour?{...active.detour,blocked}:null};const path=change.comparison?.revised;if(change.fixture&&active.route.facilityPathSeconds!=null&&path?.feasible&&change.comparison.changed&&!active.detour){const route={...active.route,steps:pathInstructions(FIXTURE_LAYOUT,path).map((text,i)=>({id:'revised-facility-'+i,text,durationSeconds:path.edges[i].seconds,facilityId:path.edges[i].facilityId})),arrivalSeconds:active.route.arrivalSeconds-active.route.facilityPathSeconds+path.seconds,walkingSeconds:active.route.walkingSeconds-active.route.facilityPathWalkingSeconds+path.walkingSeconds,facilityPathSeconds:path.seconds,facilityPathWalkingSeconds:path.walkingSeconds};next=proposeRoute(next,route,'Labelled facility incident · alternative uses '+path.facilityIds.join(', '));next.facilityReview=true;}commit(next);if(blocked)message('The accepted toilet path is no longer usable. Cancel it and review a replacement; the original destination is retained.');}},onMarkers:markers=>drawMap(markers)});
  personal=mountPersonal({host:$('companion-places'),storage:deviceStorage,getPlan:()=>prepared??active?.plan,places:getPlaces(),onSelectPlan:plan=>{$('need-step-free').checked=plan.preferences?.stepFree??false;$('fare-category').value=plan.preferences?.fareCategory??'adult';prepared=null;renderPreview();onSelectPlan(plan);message('Saved endpoints selected with a current date/time. Recalculate and review the route and facilities before starting.');},onEndpoint});
  spending=mountExpenditure({host:$('companion-fares'),storage:deviceStorage,getJourney:()=>active,getFareOptions});
  async function initMap(){const supplied=getMap();if(supplied&&!showHeader){map=supplied;externalMap=true;$('companion-map').hidden=true;$('companion-map-note').hidden=true;sections.map.querySelector('h3').textContent='Station & toilet assistance';mapLayers=L.layerGroup().addTo(map);drawMap();return;}if(!showHeader){$('companion-map').hidden=true;$('companion-map-note').textContent='Use the main map when available. Text guidance remains usable.';return;}if(!window.L){await new Promise((resolve,reject)=>{const css=document.createElement('link');css.rel='stylesheet';css.href='/vendor/leaflet.css';document.head.append(css);const script=document.createElement('script');script.src='/vendor/leaflet.js';script.onload=resolve;script.onerror=reject;document.head.append(script);});}map=L.map($('companion-map'),{scrollWheelZoom:false}).setView([1.315,103.87],12);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>',maxZoom:19}).addTo(map);mapLayers=L.layerGroup().addTo(map);drawMap();}
  function drawMap(markers){if(markers)toiletMarkers=markers;if(!mapLayers)return;mapLayers.clearLayers();const points=[];const add=(lat,lng,label,onSelect)=>{if(!Number.isFinite(lat)||!Number.isFinite(lng))return;points.push([lat,lng]);const marker=L.marker([lat,lng],{title:label,alt:label,icon:L.divIcon({className:'companion-marker',html:'<span aria-hidden="true">●</span>',iconSize:[28,28],iconAnchor:[14,14]})}).bindPopup(document.createTextNode(label)).addTo(mapLayers);if(onSelect)marker.on('click',onSelect);};for(const point of externalMap?[]:[active?.plan.origin,active?.plan.destination])if(point)add(point.lat,point.lng,point.label??point.id);for(const point of toiletMarkers??[])add(point.lat??point.position?.lat??point.coordinates?.[1],point.lng??point.position?.lng??point.lon??point.coordinates?.[0],point.label??point.name??point.id,point.onSelect);if(active?.location&&!externalMap){const l=active.location;L.circle([l.latitude,l.longitude],{radius:l.accuracy,color:'#a57111'}).bindPopup('Approximate browser position; floor unknown').addTo(mapLayers);points.push([l.latitude,l.longitude]);}if(points.length&&!externalMap)map.fitBounds(points,{padding:[25,25],maxZoom:17});}
  initMap().catch(()=>{$('companion-map-note').textContent='Map unavailable. Text journey and facility instructions remain usable.';});
  window.addEventListener('hashchange',()=>{if(sharing.useFragment())refreshShare().then(()=>revealSection('sharing')).catch(e=>message('Shared trip unavailable: '+e.message));});
  window.addEventListener('offline',()=>{renderActive();offline.verify();message('Offline. Location assistance can still receive a browser fix. Sharing and live reports cannot update; check offline availability below.');});window.addEventListener('online',()=>{renderActive();offline.verify();if(sharing.session)refreshShare().then(()=>syncPrivacy()).then(()=>active&&sharing.update(active)).catch(e=>message('Reconnect sharing: '+e.message));});
  document.addEventListener('visibilitychange',()=>{locationAssistance.visibilityChanged();if(document.hidden&&active){active={...active,permissions:{...active.permissions,geolocation:'stopped'}};if(storageEnabled)saveActive(deviceStorage,active);}renderActive();if(!document.hidden)offline.verify();});
  window.addEventListener('pagehide',()=>locationAssistance.stop('Page closed.'));
  window.addEventListener('storage',event=>{if(event.key===JOURNEY_KEY||event.key===null)offline.storageChanged();});
  window.visualViewport?.addEventListener('resize',()=>dock.classList.toggle('keyboard-open',visualViewport.height<window.innerHeight*.7));
  window.addEventListener('copilot:legacy-accepted',e=>{try{if((!active||['completed','cancelled'].includes(active.status))&&e.detail?.action!=='accept')return;prepared=routeFromLegacy(e.detail.route,e.detail.input,{name,mode:e.detail.input.fixture?'replay':mode});let next;if(active&&!['completed','cancelled'].includes(active.status)){if(active.plan.destination.id!==prepared.destination.id)throw Error('Finish or cancel the active trip before replacing its destination.');next=active.route.id===prepared.route.id?{...active}:acceptRoute(proposeRoute(active,prepared.route,'Accepted from route comparison'));}else next=startJourney(prepared);const p=e.detail.state?.progress;next.routingContext=e.detail.state;if(p)next=confirmCheckpoint(next,{stepIndex:Math.min(p.legIndex,next.route.steps.length-1),kind:p.kind,label:'Manually confirmed '+p.kind});commit(next);renderPreview();}catch(err){message(err.message);}});
  navigator.serviceWorker?.addEventListener('message',event=>{if(event.data?.type==='push-subscription-expired')message('Notification subscription expired. Enable notifications again to register a new subscription.');if(event.data?.type==='journey-notification')refreshShare().catch(e=>message(e.message));});
  renderActive();renderSharing();offline.setTrip(active);offline.verify();if(incoming||sharing.session)refreshShare().then(()=>{if(incoming)revealSection('sharing');if(navigator.onLine)return syncPrivacy();}).catch(e=>message('Shared trip unavailable: '+e.message));
  // Foreground refresh only; this is not background location or push delivery.
  setInterval(()=>{if(!document.hidden){renderLocationStatus();offline.storageChanged();if(navigator.onLine&&sharing.session?.role==='caregiver')refreshShare().catch(()=>{});}},15000);
  return {sections,getActive:()=>active,getCard:()=>journeyCard(active,{online:navigator.onLine,visible:!document.hidden}),update:commit,setPrepared:(plan,{routingContext=null}={})=>{prepared=structuredClone(plan);preparedContext=routingContext?structuredClone(routingContext):null;renderPreview();window.dispatchEvent(new CustomEvent('copilot:prepared',{detail:{plan:prepared}}));},refresh:()=>{personal?.refresh();renderActive();map?.invalidateSize();offline.storageChanged();},review:()=>{prepared=selectedPlan();renderPreview();return prepared;}};
}
