import {COVERAGE_REGISTRY,FIXTURE_LAYOUT,FACILITY_SCENARIOS,stationLayout,fixtureStatuses} from './facility-data.js';
import {findFacilityPath,pathInstructions,mapMaintenanceNotices,compareFacilityPaths,facilityStatus} from './facility-engine.js';
import {getAppLocation,locationDescription} from './location-assistance.js';
import {rankToilets,previewToiletDetour,detourStillFeasible} from './toilet-engine.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mins=s=>s==null?'unknown':`${Math.round(s/6)/10} min`;
const when=value=>value?new Date(value).toLocaleString('en-SG',{timeZone:'Asia/Singapore'}):'not supplied';
const FEED_KEY='commute-copilot-facilities-v1';
const symbols={platform:'P',lift:'L',stairs:'S',escalator:'E',gate:'G',exit:'↗',toilet:'WC',landmark:'i',passage:'·'};

export function mountFacilities({host,getJourney=()=>null,onAcceptDetour=()=>{},onCheckpoint=()=>{},onStopAction=()=>{},onStartFixture=()=>{},onFacilityChange=()=>{},onMarkers=()=>{}}={}){
  if(!host)throw Error('A station-layout host is required.');
  if(!document.querySelector('link[data-facility-css]')){const style=document.createElement('link');style.rel='stylesheet';style.href='/src/facility.css';style.dataset.facilityCss='true';document.head.append(style);}
  host.classList.add('facility-panel');
  const locationService=getAppLocation();
  const locationNote=()=>{const state=locationService.getState();return state.usable?locationDescription(state.position,state):'Indoor location needs a signposted checkpoint; use the station selector and ask staff when uncertain.';};
  let layout=stationLayout('bugis'),floor='B2',manual=null,scenario='none',view='layout',preview=null,message='',feed=null,pending=false,zoom=1,breakMinutes=5,walkingProfile=true,needSeated=false,needRails=false,lastComparison=null,lastRenderJourney=null;
  try{const saved=JSON.parse(localStorage.getItem(FEED_KEY));if(saved?.schemaVersion===1&&Array.isArray(saved.records))feed={...saved,status:'unavailable',stale:true,error:'saved_snapshot'};}catch{}
  function journey(){return getJourney();}
  function checkpoint(){const j=journey(),cp=j?.progress?.checkpoint;return cp?.stationId===layout.id&&cp.nodeId?{...cp,confirmedAt:j.progress.confirmedAt}:manual?.stationId===layout.id?manual:null;}
  function states(){return layout.fixture?fixtureStatuses(scenario):mapMaintenanceNotices(feed,layout.facilities??[]).statuses;}
  function config(){const j=journey(),cp=checkpoint(),limit=(j?.plan?.preferences?.walkingLimitMinutes??30)*60-(j?.route?.walkingSeconds??0),stepFree=j?.plan?.preferences?.stepFree===true||walkingProfile,plannedStart=!j?.id&&j?.plan?Date.parse(`${j.plan.departureDate}T${j.plan.departureTime}:00+08:00`):NaN;return {from:cp?.nodeId,onward:cp?.nodeId,profile:{stepFree,wheelchairToilet:stepFree,seated:needSeated,grabRails:needRails},statuses:states(),allowFixtures:layout.fixture,walkingLimitSeconds:Math.max(0,limit),now:Date.now(),arrivalBaseMs:Number.isFinite(plannedStart)?plannedStart:Date.now(),breakMinutes,offline:!navigator.onLine&&!layout.fixture,positionKind:j?.progress?.kind==='onboard'?'onboard':'manual',upcomingStationIds:upcomingStations(j)};}
  function upcomingStations(j){return (j?.route?.steps??[]).slice(j?.progress?.stepIndex??0).flatMap(s=>[s.stationId,...(s.stopIds??[])]).filter(Boolean);}
  function action(callback,...args){try{const result=callback(...args);if(result?.then)result.then(()=>render()).catch(e=>{message=e.message;render();});else render();}catch(error){message=error.message;render();}}
  function setLayout(id){layout=stationLayout(id)??{id,name:id,coverage:'unknown',nodes:[],edges:[],facilities:[],toilets:[],floors:[],warning:COVERAGE_REGISTRY.limitation};floor=layout.floors?.[0]?.id??'';preview=null;manual=null;zoom=1;lastComparison=null;}
  function activeStop(){const d=journey()?.detour;return d&&d.stationId===layout.id&&!['cancelled'].includes(d.status)?d:null;}
  function assessStop(stop,options){const reserved=['reached','returning'].includes(stop.status)?stop.returnPath?.walkingSeconds??0:stop.walkingSeconds??0;return detourStillFeasible(layout,stop,{...options,walkingLimitSeconds:options.walkingLimitSeconds+reserved});}
  function render(){
    const j=journey(),cp=checkpoint(),options=config(),status=states(),path=layout.nodes.length?findFacilityPath(layout,{...options,to:layout.defaultTo}):null,results=rankToilets(layout,options),stop=activeStop();
    const selectedPath=preview?.outbound??(stop?.status==='accepted'?stop.outbound:['returning','resumed'].includes(stop?.status)?stop.returnPath:path);
    const assessment=stop&&['accepted','reached','returning'].includes(stop.status)?assessStop(stop,options):null;
    host.innerHTML=`<header class="facility-heading"><div><p class="facility-kicker">STATION GUIDANCE</p><h2>Station layout & toilets</h2></div></header>
    <p>Confirm a platform, gate or exit to prepare guidance. An approximate GPS position cannot identify an underground floor or a lift.</p>
    <div class="facility-controls"><label>Station<select data-field="station">${COVERAGE_REGISTRY.stations.map(s=>`<option value="${s.id}" ${s.id===layout.id?'selected':''}>${esc(s.name)} · incomplete coverage</option>`).join('')}<option value="fixture-interchange" ${layout.fixture?'selected':''}>Training interchange · fictional</option></select></label><label>Travel profile<select data-field="profile"><option value="step-free" ${walkingProfile?'selected':''}>Step-free; wheelchair toilet</option><option value="walking" ${!walkingProfile?'selected':''}>Stairs and escalators acceptable</option></select></label></div>
    <p class="facility-notice wip-banner ${layout.fixture?'fixture':''}" ${layout.fixture?'':'data-instruction-card="facility-station-coverage"'}><strong>${layout.fixture?'TRAINING FIXTURE · not real station directions':'Work in progress — station coverage'}</strong> ${esc(layout.warning??COVERAGE_REGISTRY.limitation)}</p>
    <p class="facility-position"><strong>${cp?'Last manually confirmed checkpoint: '+esc(cp.label??cp.nodeId):'Indoor position unknown'}</strong>${cp?.confirmedAt?' · '+esc(when(cp.confirmedAt)):''}. <span data-facility-location>${esc(locationNote())}</span></p>
    <p class="facility-message" role="status" aria-live="polite">${esc(message)}</p>
    ${lastComparison?`<details class="facility-change" open><summary>Original and revised station paths</summary><p>${esc(lastComparison.message)} ${lastComparison.addedSeconds!=null?'Arrival change '+mins(lastComparison.addedSeconds)+'; walking change '+mins(lastComparison.addedWalkingSeconds)+'.':''} Fare: check gate re-entry against the current trip rules.</p><h4>Original path · before injected condition</h4><ol>${pathInstructions(layout,lastComparison.original).map(t=>`<li>${esc(t)}</li>`).join('')}</ol><h4>Revised supported path</h4><ol>${pathInstructions(layout,lastComparison.revised).map(t=>`<li>${esc(t)}</li>`).join('')}</ol><p>An accepted toilet route changes only after you review and accept another stop.</p></details>`:''}
    ${layout.fixture?`<details ${scenario!=='none'?'open':''}><summary>Labelled incident rehearsal</summary><p>These are authored test incidents, including escalator outages. No live escalator feed or future maintenance dates are available.</p><button data-action="start-fixture" class="secondary">Prepare training journey</button><label>Injected condition<select data-field="scenario">${FACILITY_SCENARIOS.map(s=>`<option value="${s.id}" ${scenario===s.id?'selected':''}>${esc(s.label)}</option>`).join('')}</select></label>${scenario==='ambiguous'?'<p>Unresolved training notice: lift ID missing; description matches no reviewed mapping. No arbitrary lift is selected.</p>':''}</details>`:''}
    <div class="facility-tabs" role="group" aria-label="Station tools"><button data-action="layout" aria-pressed="${view==='layout'}" class="secondary">Station layout</button><button data-action="toilets" aria-pressed="${view==='toilets'}" class="secondary">Find a toilet</button></div>
    ${!stop&&(j?.plan?.stops??[]).some(s=>s.type==='toilet')?`<section class="facility-planned"><h3>Planned toilet stops</h3><p>Confirm your current checkpoint, then recheck the entrance path and opening schedule. A prepared stop does not confirm your location or activate old directions.</p>${j.plan.stops.filter(s=>s.type==='toilet').map(s=>`<button data-planned="${esc(s.facilityId??s.toiletId??s.preview?.toiletId)}" class="secondary">Planned stop ${esc(s.preview?.name??s.facilityId??s.toiletId)} — Recheck and preview</button>`).join('')}</section>`:''}
    ${view==='layout'?renderLayout(cp,path,selectedPath,status):renderToilets(results,cp)}
    ${stop?`<section class="facility-stop"><h3>Accepted stop · ${esc(stop.name??stop.toiletId)}</h3><p>Original destination: ${esc(j.plan?.destination?.label??j.plan?.destination?.id)}. Stop status: ${esc(stop.status)}. Assumed break ${stop.breakMinutes} min; only your confirmation resumes the journey.</p>${assessment&&!assessment.feasible?'<p class="facility-alert">The accepted stop is affected. Its old instructions are retained for comparison, not safe guidance. Review another suitable result and explicitly accept a replacement.</p>':''}${stop.status==='accepted'?'<button data-action="reached" class="primary">Reached toilet</button>':''}${stop.status==='reached'?'<button data-action="resume" class="primary">Resume journey</button>':''}${!['resumed','cancelled'].includes(stop.status)?'<button data-action="cancel-stop" class="secondary">Cancel stop</button>':''}${['returning','resumed'].includes(stop.status)?`<h4>Return to your onward checkpoint</h4><ol>${pathInstructions(layout,stop.returnPath).map(t=>`<li>${esc(t)}</li>`).join('')}</ol><p>Use the checkpoint control to confirm when you are back. Resuming does not confirm your location.</p>`:''}</section>`:''}
    <details class="facility-source"><summary>Coverage, source age & assistance</summary><p>${esc(COVERAGE_REGISTRY.limitation)}</p><p>One OSM toilet candidate near Bugis is retained under ODbL; no real toilet entrance route is verified. Training records are separate. All facilities in the loaded dataset appear in the layout list; the real dataset is incomplete.</p><p>Live lift feed: ${esc(feed?.status??'not checked')}; fetched ${esc(when(feed?.fetchedAt))}; source time ${esc(when(feed?.sourceTime))}. ${feed?.error?'Error: '+esc(feed.error)+'. ':''}${!navigator.onLine?'Offline: last known report retained; no new closures can be fetched. ':''}No maintenance report is not proof of operation.</p><button data-action="refresh" class="secondary" ${pending||!navigator.onLine?'disabled':''}>${pending?'Checking…':'Check live lift reports'}</button>${(feed?.records??[]).length?'<ul>'+feed.records.map(r=>`<li>${esc(r.stationName??r.stationCode)} · ${esc(r.liftId??'Lift ID not supplied')} · ${esc(r.liftDesc??'Description unknown')} · unresolved until a reviewed mapping exists.</li>`).join('')+'</ul>':''}<p><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors · ODbL</a>. Layout diagrams here are original schematics; no operator artwork is copied.</p><button data-action="assistance" class="secondary">Station assistance / check in</button></details>`;
    bind(results,path);
    onMarkers(results.filter(r=>r.toilet.position).map(r=>({id:r.toilet.id,lat:r.toilet.position.lat,lng:r.toilet.position.lng,label:r.toilet.name,status:r.status,description:r.reasons.join(' '),onSelect:()=>{view='toilets';message=r.toilet.name+': '+r.reasons.join(' ');render();host.scrollIntoView({block:'start'});}})));
  }
  function renderLayout(cp,path,selectedPath,status){
    if(!layout.nodes.length)return '<section><h3>Indoor layout unavailable</h3><p>No checked floors or connections are published for this station in the retained dataset. There is no precise position marker or invented path. Select another station or use the clearly labelled rehearsal.</p><button class="secondary" data-action="confirm-station">Confirm I am at this station · floor unknown</button><button class="secondary" data-action="assistance">Ask station staff for assistance</button></section>';
    const visible=layout.nodes.filter(n=>n.floor===floor),ids=new Set(visible.map(n=>n.id)),pathIds=new Set(selectedPath?.edges?.map(e=>e.id)??[]),cpNode=layout.nodes.find(n=>n.id===cp?.nodeId);
    return `<section><div class="facility-controls"><label>Floor<select data-field="floor">${layout.floors.map(f=>`<option value="${f.id}" ${f.id===floor?'selected':''}>${esc(f.label)}</option>`).join('')}</select></label><label>Choose a visible checkpoint<select data-field="checkpoint">${layout.nodes.map(n=>`<option value="${n.id}" ${n.id===cp?.nodeId?'selected':''}>${esc(n.floor+' · '+n.label)}</option>`).join('')}</select></label><button data-action="confirm" class="primary">I am here</button></div><div class="facility-controls"><button data-action="zoom-in" aria-label="Zoom in station layout" class="secondary">Zoom +</button><button data-action="zoom-out" aria-label="Zoom out station layout" class="secondary">Zoom −</button><button data-action="recenter" class="secondary">Recentre</button></div>
    <div class="facility-diagram" tabindex="0" aria-label="Scrollable schematic station layout"><svg role="img" aria-label="${esc(layout.name+' '+floor+' schematic; use the equivalent instructions below')}" viewBox="0 0 630 420" style="width:${zoom*100}%;min-width:${zoom*560}px"><title>${esc(layout.name+' · '+floor)}</title><rect width="630" height="420" fill="#f5faf7"/>${layout.edges.filter(e=>ids.has(e.from)&&ids.has(e.to)).map(e=>{const a=visible.find(n=>n.id===e.from),b=visible.find(n=>n.id===e.to);return `<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="${pathIds.has(e.id)?'#087862':'#8ea8a0'}" stroke-width="${pathIds.has(e.id)?8:4}" ${e.kind==='gate'?'stroke-dasharray="7 4"':''}/>`;}).join('')}${visible.map(n=>`<g><circle cx="${n.x}" cy="${n.y}" r="${n.id===cpNode?.id?23:18}" fill="${n.id===cpNode?.id?'#124f97':n.type==='toilet'?'#bce2d8':'#fff'}" stroke="#174b42" stroke-width="2"/><text x="${n.x}" y="${n.y+5}" text-anchor="middle" fill="${n.id===cpNode?.id?'white':'#153638'}" font-size="13" font-weight="700">${esc(symbols[n.type]??'·')}</text><text x="${n.x}" y="${n.y+39}" text-anchor="middle" fill="#153638" font-size="12">${esc(n.label)}</text></g>`).join('')}</svg></div>
    <p class="facility-legend">P platform · L lift · E escalator · S stairs · G gate · WC toilet · i assistance · ↗ exit. Blue = last manually confirmed checkpoint; green line = intended path. Vertical links appear in the instructions, not as a geographical projection.</p>
    <h3>${selectedPath===path?'Path to destination exit':'Prepared toilet path'}</h3>${selectedPath?.feasible?`<p>${layout.fixture?'Training estimates: ':''}${mins(selectedPath.seconds)} total, ${mins(selectedPath.walkingSeconds)} walking. ${esc(selectedPath.reason)}.</p><ol>${pathInstructions(layout,selectedPath).map(t=>`<li>${esc(t)}</li>`).join('')}</ol>`:`<p>${esc(path?.reason??'Confirm a checkpoint to prepare a path.')}</p><button data-action="assistance" class="secondary">Station assistance / check in</button>`}
    <details><summary>All facilities in this dataset</summary><ul>${layout.nodes.map(n=>`<li>${esc(n.floor+' · '+n.label+' · '+(n.paidArea?'paid':'unpaid')+' area')}</li>`).join('')}</ul><ul>${layout.facilities.map(f=>`<li>${esc(f.label)}: ${esc(facilityStatus(status[f.id]).label)}</li>`).join('')}</ul></details></section>`;
  }
  function renderToilets(results,cp){
    const suitable=results.filter(r=>r.status==='suitable');
    return `<section><h3>Toilet options</h3><p>${journey()?.progress?.kind==='onboard'?'On a train: only confirmed reachable upcoming stations are considered; street GPS proximity is ignored.':'Choose a station and manually confirm a checkpoint if GPS is denied or unreliable.'}</p><div class="facility-controls"><label class="facility-check"><input type="checkbox" data-field="seated" ${needSeated?'checked':''}> Seated toilet required</label><label class="facility-check"><input type="checkbox" data-field="rails" ${needRails?'checked':''}> Grab rails required</label><label>Assumed break (minutes)<input type="number" min="0" max="120" step="1" value="${breakMinutes}" data-field="break"></label></div>${!cp&&layout.nodes.length?'<p>Confirm your checkpoint in Station layout to calculate usable paths.</p><button data-action="layout" class="secondary">Choose manual checkpoint</button>':''}${!suitable.length?'<p class="facility-notice">No verified suitable option can be recommended from the current checkpoint and available coverage. Unknown candidates below require staff confirmation; no exact walking time is claimed.</p><button data-action="assistance" class="secondary">Station assistance / check in</button>':''}
    <div class="facility-results">${results.length?results.map(r=>`<article class="facility-result"><h4>${esc(r.toilet.name)}</h4><p><strong>${r.status==='suitable'?(layout.fixture?'Suitable in training graph':'Supported suitable option'):r.status==='unknown'?'Unknown suitability':'Excluded from directions'}</strong> · ${esc(r.toilet.venue)}</p><p>Floor ${esc(r.toilet.floor??'unknown')} · entrance ${esc(r.toilet.entrance??'unknown')} · ${r.toilet.paidArea==null?'fare-gate side unknown':r.toilet.paidArea?'inside fare gates':'outside fare gates'}.</p><p>Wheelchair toilet ${attribute(r.toilet.wheelchair)}; seated ${attribute(r.toilet.seated)}; grab rails ${attribute(r.toilet.grabRails)}. Access ${esc(r.toilet.access??'unknown')}; fee ${r.toilet.feeCents==null?'unknown':'SGD '+(r.toilet.feeCents/100).toFixed(2)}.</p><p>${esc(r.availability?.label??'Availability unknown')}. ${r.availability?.stale?'Last-known report is stale. ':''}No occupancy or queue data.</p>${r.status==='suitable'?`<p>${mins(r.outbound.seconds)} to entrance, ${mins(r.seconds)} out and onward; ${mins(r.walkingSeconds)} total walking. ${r.outbound.crossesFareGate||r.returnPath.crossesFareGate?'Fare-gate crossing required; re-entry charges need checking.':'No fare-gate crossing on this detour.'}</p><button data-preview="${esc(r.toilet.id)}" class="primary">Preview directions & onward journey</button>`:`<ul>${r.reasons.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`}<details><summary>Source and verification</summary><p>${esc(r.toilet.source?.name??'unknown')} · ${esc(r.toilet.source?.license??'reuse terms unknown')} · reviewed ${esc(r.toilet.reviewedAt??'unknown')}; field verification ${esc(r.toilet.verifiedAt??'not performed')}; source time ${esc(when(r.toilet.source?.sourceTime))}; fetched ${esc(when(r.toilet.source?.fetchedAt))}.</p>${r.toilet.source?.url?`<a href="${esc(r.toilet.source.url)}" rel="noreferrer" target="_blank">Source record</a>`:''}</details></article>`).join(''):'<p>No toilet records are retained for this station. Lack of data does not mean the station has no toilets.</p>'}</div>
    ${preview?`<section class="facility-preview" tabindex="-1"><h3>Review toilet detour</h3><p>${esc(preview.name)}. Original destination stays ${esc(journey()?.plan?.destination?.label??'unchanged')}. Adds ${mins(preview.addedSeconds)}, including an editable ${preview.breakMinutes}-minute break; walking ${mins(preview.walkingSeconds)}.</p><p>${esc(preview.fareImpact.message)}</p><ol>${preview.steps.map(s=>`<li>${esc(s.text)}</li>`).join('')}</ol><button data-action="accept-detour" class="primary">${journey()?.id?'Accept toilet detour':'Add planned toilet stop'}</button><button data-action="dismiss-preview" class="secondary">Keep current journey</button><p>Acceptance updates this journey only. It does not grant caregiver progress or location permission.</p></section>`:''}</section>`;
  }
  function attribute(value){return value===true?'yes':value===false?'no':'unknown';}
  function bind(results,path){
    const field=name=>host.querySelector(`[data-field="${name}"]`);
    field('station').onchange=e=>{setLayout(e.target.value);render();};
    field('profile').onchange=e=>{walkingProfile=e.target.value==='step-free';if(journey()?.plan?.preferences?.stepFree===true&&!walkingProfile){walkingProfile=true;message='This accepted/prepared plan requires step-free access. Its directions continue to exclude stairs and escalators.';}preview=null;render();};
    if(field('floor'))field('floor').onchange=e=>{floor=e.target.value;render();};
    if(field('scenario'))field('scenario').onchange=e=>{const old=states();scenario=e.target.value;preview=null;const opts=config(),comparison=compareFacilityPaths(layout,{...opts,to:layout.defaultTo},old,states()),stop=activeStop(),detourAssessment=stop?assessStop(stop,opts):null;lastComparison=comparison;message=comparison.message+(comparison.addedSeconds!=null?` Arrival impact ${mins(comparison.addedSeconds)}; added walking ${mins(comparison.addedWalkingSeconds)}.`:'');onFacilityChange({scenario,fixture:true,statuses:states(),comparison,detourAssessment});render();};
    for(const [name,set] of [['seated',v=>needSeated=v],['rails',v=>needRails=v]])if(field(name))field(name).onchange=e=>{set(e.target.checked);preview=null;render();};
    if(field('break'))field('break').onchange=e=>{const value=Number(e.target.value);if(Number.isFinite(value)&&value>=0&&value<=120)breakMinutes=value;else message='Choose a break from 0 to 120 minutes.';preview=null;render();};
    for(const b of host.querySelectorAll('[data-preview]'))b.onclick=()=>{const opts=config(),fresh=rankToilets(layout,opts).find(r=>r.toilet.id===b.dataset.preview);try{preview=previewToiletDetour(layout,fresh,{originalDestination:journey()?.plan?.destination,onward:opts.onward,breakMinutes});render();host.querySelector('.facility-preview')?.focus();}catch(e){message=e.message;render();}};
    for(const b of host.querySelectorAll('[data-planned]'))b.onclick=()=>{view='toilets';const opts=config(),fresh=rankToilets(layout,opts).find(r=>r.toilet.id===b.dataset.planned);if(fresh?.status==='suitable'){preview=previewToiletDetour(layout,fresh,{originalDestination:journey()?.plan?.destination,onward:opts.onward,breakMinutes});message='Planned stop rechecked. Review and accept the prepared directions.';}else{preview=null;message=!checkpoint()?'Confirm a manual checkpoint first. The planned stop has not been activated.':'The planned stop cannot currently be recommended. Review the current results for a suitable replacement or ask station staff.';}render();host.querySelector('.facility-preview')?.focus();};
    for(const b of host.querySelectorAll('[data-action]'))b.onclick=()=>{
      const a=b.dataset.action;
      if(a==='layout'||a==='toilets'){view=a;render();}
      else if(a==='confirm'){
        const n=layout.nodes.find(n=>n.id===field('checkpoint').value);if(!n)return;
        manual={nodeId:n.id,stationId:layout.id,floor:n.floor,label:n.label,confirmedAt:Date.now()};floor=n.floor;preview=null;message='Checkpoint manually confirmed. The clock did not move your position.';action(onCheckpoint,manual);
      }else if(a==='confirm-station')action(onCheckpoint,{nodeId:null,stationId:layout.id,floor:null,label:layout.name+' · floor and exact position unknown'});
      else if(a==='zoom-in'){zoom=Math.min(3,zoom+.25);render();}else if(a==='zoom-out'){zoom=Math.max(1,zoom-.25);render();}else if(a==='recenter'){zoom=1;floor=checkpoint()?.floor??layout.floors[0].id;render();}
      else if(a==='start-fixture'){setLayout('fixture-interchange');scenario='none';manual={nodeId:'platform',stationId:layout.id,floor:'B2',label:'Training platform',confirmedAt:Date.now()};action(onStartFixture,{layoutId:layout.id,checkpoint:manual,layout:structuredClone(FIXTURE_LAYOUT)});}
      else if(a==='accept-detour'){
        if(!preview)return;const fresh=rankToilets(layout,config()).find(r=>r.toilet.id===preview.toiletId);if(fresh?.status!=='suitable'){preview=null;message='Conditions changed; review a currently suitable option.';render();return;}
        const accepted=previewToiletDetour(layout,fresh,{originalDestination:journey()?.plan?.destination,onward:config().onward,breakMinutes});action(onAcceptDetour,accepted);preview=null;render();
      }else if(a==='dismiss-preview'){preview=null;render();}
      else if(['reached','resume','cancel-stop'].includes(a))action(onStopAction,a==='cancel-stop'?'cancel':a);
      else if(a==='refresh')refreshFeed();
      else if(a==='assistance'){message='Ask station staff at the passenger service centre for a checked step-free route and toilet entrance. Confirm a signposted checkpoint when safe. No unverified alternative is drawn.';render();}
    };
  }
  async function refreshFeed(){
    if(pending||!navigator.onLine)return;pending=true;render();
    try{const response=await fetch('/api/facilities',{cache:'no-store',signal:AbortSignal.timeout(8000)});if(!response.ok)throw Error('Facility feed unavailable');const value=await response.json();if(value?.schemaVersion!==1||!Array.isArray(value.records))throw Error('Malformed facility feed');feed=value;try{localStorage.setItem(FEED_KEY,JSON.stringify(feed));}catch{message='Facility snapshot could not be saved on this device.';}if(!layout.fixture)onFacilityChange({fixture:false,statuses:states(),unresolved:mapMaintenanceNotices(feed,layout.facilities??[]).unresolved});}
    catch(error){feed={...feed,schemaVersion:1,records:feed?.records??[],status:'unavailable',stale:true,error:error.message};message='Live facility report unavailable; last known data retained. No training data is substituted.';}
    finally{pending=false;render();}
  }
  const networkChange=()=>{preview=null;render();};window.addEventListener('online',networkChange);window.addEventListener('offline',networkChange);
  function syncJourney(){const j=journey();if(j?.id!==lastRenderJourney){lastRenderJourney=j?.id;walkingProfile=j?.plan?.preferences?.stepFree!==false;const id=j?.progress?.checkpoint?.stationId??j?.detour?.stationId??j?.plan?.origin?.stationId;if(id&&stationLayout(id))setLayout(id);}if(j?.facilityScenario&&FACILITY_SCENARIOS.some(s=>s.id===j.facilityScenario))scenario=j.facilityScenario;}
  syncJourney();render();
  const unsubscribeLocation=locationService.subscribe(()=>{const note=host.querySelector('[data-facility-location]');if(note)note.textContent=locationNote();});
  return {refresh(){syncJourney();render();},open(id,mode='layout'){if(id&&stationLayout(id))setLayout(id);view=mode;syncJourney();render();host.scrollIntoView({block:'start'});host.querySelector('h2')?.setAttribute('tabindex','-1');host.querySelector('h2')?.focus();},destroy(){unsubscribeLocation();window.removeEventListener('online',networkChange);window.removeEventListener('offline',networkChange);onMarkers([]);}};
}
