import {createLedger,parseCents,recordAmount} from './fare-ledger.js';
import {formatSGD,estimatePlanFare,FARE_VERSION} from './fares.js';
import {singaporeNow} from './personal.js';
import {spendingPeriods} from './fare-periods.js';
import {createBudgetStore,budgetProgress} from './commute-budget.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const browserStorage=()=>{try{return globalThis.localStorage;}catch{return undefined;}};
export function fareEstimateHTML(value,options={}){const f=value?.status&&Object.hasOwn(value,'totalCents')?value:estimatePlanFare(value,options);return `<div class="fare-estimate"><strong>Planned fare: ${f.status==='estimate'?esc(formatSGD(f.totalCents))+' estimate':'unavailable'}</strong><p>${esc(f.reason??f.assumptions)}</p>${(f.breakdown??[]).map(b=>`<p>${esc(b.label)} · ${esc(formatSGD(b.cents))}${b.officialDistanceMetres?' · official fare distance '+(b.officialDistanceMetres/1000).toFixed(1)+' km':''}</p>`).join('')}<small>Fare version ${esc(f.version)} · <a href="${esc(FARE_VERSION.source)}" target="_blank" rel="noopener noreferrer">Official fare source</a>. ${f.status!=='estimate'?'Enter the charged amount after completion.':'An estimate does not establish payment.'}</small></div>`;}

export function mountExpenditure({host,storage=browserStorage(),getJourney=()=>null,getFareOptions=()=>({})}={}){
  const ledger=createLedger(storage),demoLedger=createLedger(storage,{demo:true}),budgets=createBudgetStore(storage),expanded=new Map([['today',true]]);
  let message='',edit=null,showDemo=false;
  const run=fn=>{try{fn();}catch(e){message=e.message;}render();};
  const disclosure=id=>expanded.get(id)?'open':'';

  function recordHTML(r,period){
    const editing=edit?.recordId===r.id&&edit?.period===period;
    const stamp=new Intl.DateTimeFormat('en-SG',{timeZone:'Asia/Singapore',dateStyle:'medium',timeStyle:'short'}).format(new Date(r.completedAt));
    return `<li class="spending-record" data-transaction="${esc(r.id)}" data-period="${esc(period)}">
      <div class="spending-record-heading"><strong>${esc(r.label)}</strong><strong class="spending-amount">${esc(formatSGD(recordAmount(r)))}</strong></div>
      <p class="spending-record-status">${esc(stamp)} · ${r.actualCents!==null?'User-confirmed charge':r.estimatedCents!==null?'Recorded estimate':'Awaiting amount'}</p>
      ${r.adjustments.map(a=>`<p class="spending-adjustment">${esc(a.note)}: ${formatSGD(a.cents)} <button data-adjustment="${esc(a.id)}" data-record="${esc(r.id)}">Remove adjustment</button></p>`).join('')}
      ${editing?`<div class="spending-editor"><form data-confirm="${esc(r.id)}"><label>Actual charged amount (SGD) <input name="amount" inputmode="decimal" required value="${((r.actualCents??r.estimatedCents??0)/100).toFixed(2)}"></label><button class="primary">Save confirmed charge</button></form><form data-adjust="${esc(r.id)}"><label>Adjustment SGD (negative for refund) <input name="amount" inputmode="decimal" required></label><label>Reason <input name="note" required maxlength="200"></label><button>Add adjustment</button></form><button data-close-edit>Close editing</button></div>`:''}
      <details class="spending-record-tools"><summary>Trip record options</summary><p>Fare version ${esc(r.fareVersion??'unavailable')}${r.estimatedCents!==null?` · Original estimate ${esc(formatSGD(r.estimatedCents))}`:''}</p><div class="spending-record-actions"><button data-edit="${esc(r.id)}" data-period="${esc(period)}">Enter/edit charge or adjustment</button><button data-delete="${esc(r.id)}">Delete record</button></div></details>
    </li>`;
  }
  const recordsHTML=(records,period)=>`<ol class="spending-records">${records.map(r=>recordHTML(r,period)).join('')||'<li class="spending-empty">No completed trips in this period.</li>'}</ol>`;
  function budgetHTML(records,available=true){
    const loaded=budgets.read(),budget=loaded.budget,p=available?budgetProgress(records,budget):null;
    return `<section class="commute-budget" aria-labelledby="budget-heading"><h3 id="budget-heading">Your commute budget</h3>${loaded.error?`<p role="status">${esc(loaded.error)}</p>`:''}${p?`<p>${p.period==='week'?'Calendar week':'Calendar month'} · ${p.start} – ${p.end} (SGT)</p><p class="budget-amount"><strong>${formatSGD(p.totalCents)}</strong> recorded of ${formatSGD(p.budgetCents)}</p><progress max="100" value="${p.percent}" aria-label="Recorded spending against commute budget" aria-valuetext="${p.actualPercent.toFixed(1)} percent: ${formatSGD(p.totalCents)} of ${formatSGD(p.budgetCents)}"></progress><p><strong>${p.overBudgetCents?`${formatSGD(p.overBudgetCents)} over budget`:`${formatSGD(p.remainingCents)} remaining`}</strong> · ${p.actualPercent.toFixed(1)}%</p><p class="field-note">${formatSGD(p.confirmedCents)} confirmed + ${formatSGD(p.estimatedCents)} recorded estimates. Estimates count until replaced by a charge; refunds stay with the original trip.</p>${p.unpricedTrips?`<p class="notice">${p.unpricedTrips} ${p.unpricedTrips===1?'trip has':'trips have'} no amount yet. Remaining budget is incomplete.</p>`:''}`:'<p>'+(!available?'Recorded spending is unavailable. Budget progress and remaining amounts cannot be calculated until history can be read.':'Optional: track recorded spending against a weekly or monthly amount.')+'</p>'}<details data-spending-disclosure="budget" ${disclosure('budget')}><summary>${p?'Edit budget':'Set a budget'}</summary><form id="commute-budget-form"><label>Budget period<select name="period"><option value="week" ${budget?.period!=='month'?'selected':''}>Calendar week (Monday–Sunday)</option><option value="month" ${budget?.period==='month'?'selected':''}>Calendar month</option></select></label><label>Budget amount (SGD)<input name="amount" inputmode="decimal" required value="${budget?(budget.cents/100).toFixed(2):''}" placeholder="e.g. 30.00"></label><button class="primary">Save budget</button>${budget?'<button type="button" id="disable-budget" class="secondary">Turn off budget</button>':''}</form><p class="field-note">Stored on this device. Changing the budget keeps all trip records.</p></details></section>`;
  }

  function render(){
    for(const section of host.querySelectorAll('[data-spending-disclosure]'))expanded.set(section.dataset.spendingDisclosure,section.open);
    const current=showDemo?demoLedger:ledger,loaded=current.read(),records=loaded.state.records,groups=spendingPeriods(records),now=singaporeNow();
    const periodsHTML=groups.periods.map(p=>`<details class="spending-period" data-spending-disclosure="${p.id}" ${disclosure(p.id)}><summary><span class="spending-period-heading"><strong>${p.label}: ${formatSGD(p.total.totalCents)}</strong>${p.total.unpricedTrips?`<span class="spending-pending">${p.total.unpricedTrips} ${p.total.unpricedTrips===1?'trip':'trips'} awaiting amount</span>`:''}</span></summary>${recordsHTML(p.records,p.id)}</details>`).join('');
    host.innerHTML=`<section class="spending" aria-labelledby="spend-title"><h2 id="spend-title">Journey spending</h2>
      <p>Estimates and charges stay on this device.</p><p class="spending-message" role="status">${esc(message||loaded.error||'')}</p>
      ${showDemo?'':budgetHTML(records,loaded.ok)}
      <label class="spending-demo"><input type="checkbox" id="show-demo-spend" ${showDemo?'checked':''}> Show separate replay records</label>
      ${showDemo?`<p><strong>Replay records: excluded from every personal total.</strong></p>${recordsHTML(records.slice().sort((a,b)=>Date.parse(b.completedAt)-Date.parse(a.completedAt)),'demo')}`:`<div class="spending-periods">${periodsHTML}</div><p class="spending-period-note">Singapore dates · Weeks start Monday. Adjustments stay with the original trip.</p>${groups.earlier.length?`<details class="spending-period" data-spending-disclosure="earlier" ${disclosure('earlier')}><summary>Other trip dates <span class="spending-pending">${groups.earlier.length} ${groups.earlier.length===1?'trip':'trips'}</span></summary>${recordsHTML(groups.earlier,'earlier')}</details>`:''}`}
      <details class="spending-help" data-spending-disclosure="help" ${disclosure('help')}><summary>How spending is counted</summary><p>Estimates remain labelled until you enter the charged amount. A confirmed charge replaces that trip's estimate in totals; it is counted only once. Trips awaiting an amount are excluded from the amount shown. The same trip can appear under Today, Calendar week and Calendar month.</p></details>
      ${showDemo?'':`<details class="spending-period" data-spending-disclosure="all" ${disclosure('all')}><summary>All spending history (${records.length} trips)</summary>${recordsHTML(records.slice().sort((a,b)=>Date.parse(b.completedAt)-Date.parse(a.completedAt)),'all')}</details>`}
      <details class="spending-manual" data-spending-disclosure="manual" ${disclosure('manual')}><summary>Add a missing trip or manual fare</summary><form id="manual-fare"><label>Trip label <input name="label" required maxlength="200"></label><label>Trip completion (Singapore time) <input name="completedAt" type="datetime-local" required value="${now.departureDate}T${now.departureTime}"></label><label>Amount SGD <input name="amount" required inputmode="decimal"></label><label>Amount type <select name="kind"><option value="actual">User-confirmed charge</option><option value="estimate">Recorded estimate</option></select></label><button>Add ${showDemo?'replay':'personal'} record</button></form></details>
      <button id="export-spending">Export ${showDemo?'replay':'personal'} history</button><details class="spending-delete" data-spending-disclosure="delete" ${disclosure('delete')}><summary>Delete this local fare history</summary><label><input id="confirm-clear-fares" type="checkbox"> Delete all ${showDemo?'replay':'personal'} fare records</label><button id="clear-spending">Delete selected fare history</button></details></section>`;
    host.querySelector('#show-demo-spend').onchange=e=>{showDemo=e.target.checked;edit=null;message='';render();};
    const budgetForm=host.querySelector('#commute-budget-form');if(budgetForm)budgetForm.onsubmit=e=>{e.preventDefault();run(()=>{const data=new FormData(budgetForm);budgets.set({period:data.get('period'),cents:parseCents(data.get('amount'))});message='Budget saved. Spending history is unchanged.';});};
    const disableBudget=host.querySelector('#disable-budget');if(disableBudget)disableBudget.onclick=()=>run(()=>{budgets.remove();message='Budget turned off. Spending history is unchanged.';});
    for(const b of host.querySelectorAll('[data-edit]'))b.onclick=()=>{
      edit={recordId:b.dataset.edit,period:b.dataset.period};render();
      host.querySelector('.spending-editor input')?.focus();
    };
    for(const b of host.querySelectorAll('[data-close-edit]'))b.onclick=()=>{edit=null;render();};
    for(const b of host.querySelectorAll('[data-delete]'))b.onclick=()=>run(()=>{current.delete(b.dataset.delete);edit=null;message='Record deleted. Repeated completion cannot restore it.';});
    for(const b of host.querySelectorAll('[data-adjustment]'))b.onclick=()=>run(()=>{current.deleteAdjustment(b.dataset.record,b.dataset.adjustment);message='Adjustment removed.';});
    for(const f of host.querySelectorAll('[data-confirm]'))f.onsubmit=e=>{e.preventDefault();run(()=>{current.confirm(f.dataset.confirm,parseCents(new FormData(f).get('amount')));edit=null;message='Charged amount confirmed; the estimate is retained for reference and counted only once.';});};
    for(const f of host.querySelectorAll('[data-adjust]'))f.onsubmit=e=>{e.preventDefault();run(()=>{const data=new FormData(f);current.adjust(f.dataset.adjust,{cents:parseCents(data.get('amount'),{signed:true}),note:data.get('note')});edit=null;message='Adjustment applied to the original trip.';});};
    host.querySelector('#manual-fare').onsubmit=e=>{e.preventDefault();run(()=>{const f=new FormData(e.target);current.addManual({label:f.get('label'),completedAt:f.get('completedAt')+':00+08:00',cents:parseCents(f.get('amount')),kind:f.get('kind')});message='Manual record saved.';});};
    host.querySelector('#export-spending').onclick=()=>run(()=>{const url=URL.createObjectURL(new Blob([current.export()],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=showDemo?'commute-demo-fares.json':'commute-personal-fares.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message='History exported.';});
    host.querySelector('#clear-spending').onclick=()=>run(()=>{if(!host.querySelector('#confirm-clear-fares').checked)throw Error('Select the explicit fare-history deletion checkbox first.');current.clear();edit=null;message='Selected fare history deleted.';});
  }
  render();return {refresh:render,ledger,demoLedger,complete(journey=getJourney(),options={}){try{const target=journey?.plan?.mode==='replay'?demoLedger:ledger;const result=target.complete(journey,{...getFareOptions(),...options});message=result.recorded?'Finished journey recorded once. Enter the charged amount when known.':'This completed journey was already recorded or deleted.';render();return {ok:true,...result};}catch(e){message=e.message;render();return {ok:false,error:e.message};}}};
}
