import {estimatePlanFare} from './fares.js';
export const LEDGER_KEY='commute-copilot-expenditure-v2';
export const DEMO_LEDGER_KEY='commute-copilot-demo-expenditure-v2';
const copy=v=>structuredClone(v),uid=()=>crypto.randomUUID();
const empty=()=>({schemaVersion:2,records:[],deletedJourneyIds:[]});
const amount=n=>Number.isSafeInteger(n)&&n>=0&&n<=10000000;
function instant(value){if(typeof value==='string'){const day=value.slice(0,10),stamp=Date.parse(day+'T00:00:00Z');if(!/^\d{4}-\d\d-\d\d$/.test(day)||!Number.isFinite(stamp)||new Date(stamp).toISOString().slice(0,10)!==day)throw Error('A valid trip date is required.');}const n=typeof value==='number'?value:Date.parse(value);if(!Number.isFinite(n)||!Number.isFinite(new Date(n).getTime()))throw Error('A valid trip time is required.');return new Date(n).toISOString();}
export function parseCents(value,{signed=false}={}){const pattern=signed?/^-?\d{1,6}(?:\.\d{1,2})?$/:/^\d{1,6}(?:\.\d{1,2})?$/;if(typeof value!=='string'||!pattern.test(value.trim()))throw Error('Enter an SGD amount with at most two decimal places.');const raw=value.trim(),negative=raw.startsWith('-'),[whole,part='']=raw.replace('-','').split('.');const cents=Number(whole)*100+Number(part.padEnd(2,'0'));if(cents>10000000)throw Error('Amount exceeds the supported limit.');return negative?-cents:cents;}
export function singaporeDate(value){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(instant(value))).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`;}
export function periodBounds(at=Date.now()){const day=singaporeDate(at),d=new Date(day+'T00:00:00Z'),dow=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-dow);return {day,weekStart:d.toISOString().slice(0,10),month:day.slice(0,7),weekStartsOn:'Monday',timezone:'Asia/Singapore'};}
export function recordAmount(record){const base=record.actualCents??record.estimatedCents;if(base===null)return null;return base+record.adjustments.reduce((n,a)=>n+a.cents,0);}
export function expenditureTotals(records,at=Date.now()){const bounds=periodBounds(at),weekEnd=new Date(bounds.weekStart+'T00:00:00Z');weekEnd.setUTCDate(weekEnd.getUTCDate()+7);const end=weekEnd.toISOString().slice(0,10),make=()=>({confirmedCents:0,estimatedCents:0,totalCents:0,unpricedTrips:0,tripCount:0});const result={...bounds,dayTotals:make(),weekTotals:make(),monthTotals:make()};for(const r of records){if(r.demo)continue;const day=singaporeDate(r.completedAt),keys=[];if(day===bounds.day)keys.push('dayTotals');if(day>=bounds.weekStart&&day<end)keys.push('weekTotals');if(day.startsWith(bounds.month))keys.push('monthTotals');for(const key of keys){const total=result[key],value=recordAmount(r);total.tripCount++;if(value===null)total.unpricedTrips++;else {total[r.actualCents!==null?'confirmedCents':'estimatedCents']+=value;total.totalCents+=value;}}}return result;}
function validRecord(r){return r&&typeof r.id==='string'&&typeof r.journeyId==='string'&&typeof r.label==='string'&&r.label.length<=200&&Number.isFinite(Date.parse(r.completedAt))&&typeof r.demo==='boolean'&&(r.estimatedCents===null||amount(r.estimatedCents))&&(r.actualCents===null||amount(r.actualCents))&&Array.isArray(r.adjustments)&&r.adjustments.length<=500&&new Set(r.adjustments.map(a=>a.id)).size===r.adjustments.length&&r.adjustments.every(a=>typeof a.id==='string'&&Number.isSafeInteger(a.cents)&&Math.abs(a.cents)<=10000000&&typeof a.note==='string'&&a.note.length<=200&&Number.isFinite(Date.parse(a.at)))&&(recordAmount(r)===null||amount(recordAmount(r)));}
function validate(v){return v&&v.schemaVersion===2&&Array.isArray(v.records)&&v.records.length<=5000&&v.records.every(validRecord)&&new Set(v.records.map(r=>r.journeyId)).size===v.records.length&&Array.isArray(v.deletedJourneyIds)&&v.deletedJourneyIds.every(s=>typeof s==='string')?v:null;}
export function createLedger(storage,{demo=false}={}){
 const key=demo?DEMO_LEDGER_KEY:LEDGER_KEY;
 function read(){try{const raw=storage.getItem(key);if(raw===null)return {ok:true,state:empty()};const state=validate(JSON.parse(raw));if(!state)throw Error();return {ok:true,state};}catch{return {ok:false,state:empty(),error:'Expenditure data cannot be read. It has been preserved; browser storage needs repair before records can be changed.'};}}
 function mutate(fn){const loaded=read();if(!loaded.ok)throw Error(loaded.error);const next=fn(copy(loaded.state));if(!validate(next))throw Error('Invalid expenditure record.');try{const raw=JSON.stringify(next);storage.setItem(key,raw);if(storage.getItem(key)!==raw)throw Error();}catch{throw Error('Could not save expenditure. Browser storage may be full or blocked.');}return copy(next);}
 const find=(s,id)=>{const r=s.records.find(r=>r.id===id);if(!r)throw Error('Fare record no longer exists.');return r;};
 return {read,
  complete(journey,{estimate,now=Date.now(),busNetwork,category}={}){if(!journey?.id||journey.status!=='completed'||!journey.completedAt)throw Error('Record a fare only after you explicitly finish the journey.');const isDemo=journey.plan?.mode==='replay'||journey.mode==='demo';if(isDemo!==demo)return {recorded:false,reason:isDemo?'Replay remains separate from personal spending.':'Real trips cannot enter the demo ledger.'};const at=instant(journey.completedAt),fare=estimate??estimatePlanFare(journey,{busNetwork,category});let recorded=false,record;const state=mutate(s=>{record=s.records.find(r=>r.journeyId===journey.id);if(record||s.deletedJourneyIds.includes(journey.id))return s;const cents=fare.status==='estimate'&&amount(fare.totalCents)?fare.totalCents:null;record={id:uid(),journeyId:journey.id,label:`${journey.plan?.origin?.label??'Origin'} → ${journey.plan?.destination?.label??'Destination'}`.slice(0,200),completedAt:at,recordedAt:instant(now),estimatedCents:cents,actualCents:null,adjustments:[],fareVersion:fare.version??null,fareEstimate:copy(fare),demo,journey:{schemaVersion:journey.schemaVersion,planId:journey.plan?.id??null,route:copy(journey.route??{}),revision:journey.revision??0,origin:copy(journey.plan?.origin??null),destination:copy(journey.plan?.destination??null)}};s.records.push(record);recorded=true;return s;});return {recorded,record:record?copy(record):null,state};},
  addManual({label,completedAt,cents,kind='actual',journeyId=uid()},now=Date.now()){if(!amount(cents)||!['actual','estimate'].includes(kind)||typeof label!=='string'||!label.trim()||label.length>200)throw Error('Enter a trip name and valid non-negative amount.');return mutate(s=>{if(s.records.some(r=>r.journeyId===journeyId)||s.deletedJourneyIds.includes(journeyId))throw Error('This trip has already been recorded or deleted.');s.records.push({id:uid(),journeyId,label:label.trim(),completedAt:instant(completedAt),recordedAt:instant(now),estimatedCents:kind==='estimate'?cents:null,actualCents:kind==='actual'?cents:null,adjustments:[],fareVersion:'manual',fareEstimate:null,demo,journey:null});return s;});},
  confirm(recordId,cents){if(!amount(cents))throw Error('Enter a valid charged amount.');return mutate(s=>{const r=find(s,recordId);r.actualCents=cents;if(recordAmount(r)<0)throw Error('The charge is smaller than existing refunds. Correct the adjustment first.');return s;});},
  adjust(recordId,{cents,note,id=uid()},now=Date.now()){if(!Number.isSafeInteger(cents)||Math.abs(cents)>10000000||!cents||typeof note!=='string'||!note.trim()||note.length>200)throw Error('Enter a non-zero adjustment and a short reason.');return mutate(s=>{const r=find(s,recordId);if(r.adjustments.some(a=>a.id===id))return s;if(recordAmount(r)===null)throw Error('Enter the original fare before adding a refund.');if(recordAmount(r)+cents<0)throw Error('Refunds cannot exceed the recorded amount.');r.adjustments.push({id,cents,note:note.trim(),at:instant(now)});return s;});},
  deleteAdjustment(recordId,adjustmentId){return mutate(s=>{const r=find(s,recordId);r.adjustments=r.adjustments.filter(a=>a.id!==adjustmentId);return s;});},
  delete(recordId){return mutate(s=>{const r=find(s,recordId);s.deletedJourneyIds.push(r.journeyId);s.records=s.records.filter(r=>r.id!==recordId);return s;});},
  totals(at=Date.now()){const r=read();if(!r.ok)throw Error(r.error);return expenditureTotals(r.state.records,at);},
  export(){const r=read();if(!r.ok)throw Error(r.error);return JSON.stringify({exportedAt:new Date().toISOString(),timezone:'Asia/Singapore',weekStartsOn:'Monday',...r.state},null,2);},
  clear(){return mutate(s=>({schemaVersion:2,records:[],deletedJourneyIds:[...new Set([...s.deletedJourneyIds,...s.records.map(r=>r.journeyId)])]}));}
 };
}
