import {restoreActive} from './journey-v2.js';
import {noticeSnapshot,newerSnapshot} from './feed-health.js';
import {acceptJourney,validateJourney,confirmProgress,compareJourney,ingestEvents,decide,clockTime} from './journey-state.js';
import {getAppLocation} from './location-assistance.js';
import {requiresIndoorConfirmation} from './location-progress.js';
const KEY='commute-copilot-active-journey-v1',FEED_KEY='commute-copilot-notice-health-v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mins=s=>`${Math.round(s/6)/10} min`;
export function mountJourney({host,getSelected,getRouter,getBuild,name}) {
  const locationService=getAppLocation();
  let state,comparison,message='',feed,pending=false,requestEpoch=0,lastAttempt=0,reconnectTimer;
  try{feed=noticeSnapshot(JSON.parse(localStorage.getItem(FEED_KEY)));if(feed)feed.notices={...feed.notices,status:'unavailable',error:'saved_snapshot'};}catch{}
  try{state=validateJourney(restoreActive(localStorage)?.routingContext)??validateJourney(JSON.parse(localStorage.getItem(KEY)));}catch{}
  function save(action='update'){window.dispatchEvent(new CustomEvent('copilot:legacy-accepted',{detail:{route:state.route,input:state.input,state,action}}));try{localStorage.setItem(KEY,JSON.stringify(state));}catch{message='Device storage unavailable; keep this page open. Guidance is not saved.';}}
  function status(text){message=text;render();}
  function reassess(){if(!state)return;if(!getRouter(state?.input)||state.build!==getBuild()){comparison={status:'confirmation',message:'Data version changed. Saved guidance remains; review and accept a new search before recalculating.'};}else comparison=compareJourney(state,getRouter(state?.input),Date.now(),navigator.onLine);render();}
  const legLabel=(l,i)=>`${i+1}. ${l.type==='ride'?l.mode==='bus'?`Bus ${l.serviceNo}, direction ${l.directionId}`:`${l.routeId} train`:l.type} · ${name(l.fromStopId)} → ${name(l.toStopId)} (${clockTime(l.startSeconds)}–${clockTime(l.endSeconds)})`;
  function syncLocationControls(){
    const details=host.querySelector('#legacy-manual-recovery');if(!details)return;
    const index=state?.progress?.legIndex,steps=state?.route?.legs??[],step=steps[index];
    const compact=locationService.getState().usable&&!!step&&['walk','access','transfer','exit'].includes(step.type)&&!requiresIndoorConfirmation({route:{steps},progress:{stepIndex:index}},index);
    // GPS updates only change disclosure availability. Never rebuild a pending
    // correction or close it while its select, fields or confirmation has focus.
    if(details.dataset.compact!==String(compact)){
      details.dataset.compact=String(compact);
      if(!compact||!details.matches(':focus-within'))details.open=!compact;
    }
  }
  function render(){
    const p=state?.progress,r=state?.route,age=state?Math.max(0,Math.floor((Date.now()-state.acceptedAt)/60000)):0;
    const next=r?.legs[p.legIndex];
    const previousRecovery=host.querySelector('#legacy-manual-recovery'),recoveryOpen=previousRecovery?.open??true,recoveryCompact=previousRecovery?.dataset.compact??'';
    host.innerHTML=`<h2>Route-change comparison & confirmed progress</h2><p>A search above is a preview. Accept it here to start or replace guidance. No location or completed travel is inferred from the clock.</p><button class="secondary" id="accept-search">Accept displayed search as new journey</button><p id="journey-message" role="status" aria-live="polite">${esc(message)}</p>
    ${state?`<p><strong>${navigator.onLine?'Saved accepted guidance':'Offline · saved accepted guidance'}</strong> · accepted ${age} min ago · progress confirmed ${esc(new Date(p.confirmedAt).toISOString())}. Data: ${esc(state.build)}. ${navigator.onLine?'':'No current disruption claim.'}</p><p id="accepted-next"><strong>Last accepted next step:</strong> ${p.kind==='arrived'?'Arrival confirmed':esc(next?legLabel(next,p.legIndex):'Final step completed')}. ${p.kind==='unknown'?'Position unknown; retain these instructions until confirmed.':''}</p>
    <p id="progress-summary">${esc(p.kind)} · walking used ${mins(p.walkedSeconds)} of ${esc(state.input.walkingLimitMinutes)} min · original destination ${esc(name(state.input.destinationId))} · deadline ${r.deadlineSeconds===null?'none':clockTime(r.deadlineSeconds)}.</p>
    <details id="legacy-manual-recovery" data-compact="${recoveryCompact}" ${recoveryOpen?'open':''}><summary>Manual step &amp; timing correction</summary><form id="progress-form"><label>Confirm your situation<select name="kind">${[['not-departed','Not departed'],['waiting','Waiting at this exact stop/platform'],['onboard','Onboard this planned ride'],['transferring','At the start of this transfer or exit'],['arrived','Arrived after the final step'],['unknown','Position / progress unknown']].map(([v,l])=>`<option value="${v}" ${p.kind===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Current planned step (earlier steps completed)<select name="legIndex">${r.legs.map((l,i)=>`<option value="${i}" ${p.legIndex===i?'selected':''}>${esc(legLabel(l,i))}</option>`).join('')}<option value="${r.legs.length}" ${p.legIndex===r.legs.length?'selected':''}>All steps completed</option></select></label><div class="form-pair"><label>Confirmed time on ${esc(r.date)}<input type="time" step="1" name="time" required value="${clockTime(p.confirmedSeconds)}"></label><label>Total walking already used (seconds)<input type="number" min="0" step="1" name="walk" required value="${p.walkedSeconds}"></label></div><p>At a transfer, confirm its start; its full walking allowance remains. Onboard: keep the planned ride until you confirm alighting at its planned end. Intermediate alighting is not supported.</p><button class="secondary">Confirm progress</button></form></details>
    <button class="secondary" id="reassess">Compare from confirmed point</button><details><summary>Synthetic rerouting demonstrations</summary><p>These events are invented test conditions scoped to one planned rail trip; they are never real provider validation.</p><button class="secondary" id="demo-cancel">Synthetic: cancel next rail trip</button><button class="secondary" id="demo-recover">Synthetic: recover last event</button></details>
    <section id="comparison" aria-live="polite">${comparison?`<h3>Continue or switch</h3><p>${esc(comparison.status)} · ${esc(comparison.message)}</p>${comparison.relevant?.map(e=>`<p>SYNTHETIC · ${esc(e.effect)} · trip ${esc(e.tripId)} · direction ${esc(e.directionId)} · service day ${esc(e.serviceDate)}. Source time ${esc(e.sourceTime)}; retrieved ${esc(e.retrievedAt)}; valid ${esc(e.validFrom)}–${esc(e.validUntil)}.</p>`).join('')??''}${comparison.checked?.filter(c=>!c.applicable).map(c=>`<p>${esc(c.reason)}</p>`).join('')??''}${comparison.continuing?`<p>Continue: ${esc(comparison.continuing.reason)} · ${comparison.continuing.feasible?comparison.continuing.estimated?'estimated':'scheduled':'unsupported'} arrival ${comparison.continuing.feasible?clockTime(comparison.continuing.arrivalSeconds):'unavailable'} · ${!comparison.continuing.feasible?'deadline comparison unavailable':comparison.continuing.deadlineMet?'within deadline if assumptions hold':'misses deadline'} · remaining walking ${mins(comparison.continuing.walkingSeconds)}, waiting ${mins(comparison.continuing.waitSeconds)}.</p>`:''}${comparison.alternative?`<p>Alternative: ${comparison.alternative.estimated?'uncalibrated estimate':'schedule'} ${clockTime(comparison.alternative.arrivalSeconds)} · ${comparison.alternative.deadlineMet?'within deadline if assumptions hold':'LATE'} · remaining walking ${mins(comparison.alternative.walkingSeconds)}, waiting ${mins(comparison.alternative.waitSeconds)}, ${comparison.alternative.transfers} transfers. Change in walking ${mins(comparison.alternative.walkingSeconds-comparison.continuing.walkingSeconds)}, waiting ${mins(comparison.alternative.waitSeconds-comparison.continuing.waitSeconds)}, transfers ${comparison.alternative.transfers-Math.max(0,comparison.continuing.transfers)}. ${comparison.alternative.estimated?'Bus riding/waiting are uncalibrated. Boarding predictions cannot guarantee downstream arrival or rail connections.':''}</p>`:''}${comparison.status==='offer'?'<button id="accept-change" class="primary">Accept alternative guidance</button> <button id="decline-change" class="secondary">Keep accepted guidance</button>':''}`:''}</section>
    <details><summary>All accepted instructions</summary><ol>${r.legs.map((l,i)=>`<li>${esc(legLabel(l,i))}${l.pathId?' · reviewed path '+esc(l.pathId):''}</li>`).join('')}</ol></details>`:'<p>No active journey yet. Choose a supported search, then accept it.</p>'}
    <h3>Live feed health</h3><p>Official alerts remain advisory. Real trip cancellation, delay, recovery and segment effects are disabled until their mapping is validated. Missing updates never prove normal service.</p><button class="secondary" id="refresh-journey-feed" ${pending||!navigator.onLine?'disabled':''}>Refresh relevant notices</button><p id="journey-health">${health()}</p>${feed?.notices?.items?.length?'<details><summary>Last-known advisory messages (no routing effect)</summary><ul>'+feed.notices.items.map(i=>'<li>'+esc(i.text)+'</li>').join('')+'</ul></details>':''}`;
    host.querySelector('#accept-search').onclick=()=>{const selected=getSelected();if(!selected?.route)return status('Run a supported search first.');state=acceptJourney(selected.route,selected.input,getBuild());comparison=null;message='Displayed journey accepted and saved. Progress: not departed.';save('accept');render();};
    host.querySelector('#refresh-journey-feed').onclick=refresh;
    syncLocationControls();
    if(!state)return;
    host.querySelector('#progress-form').onsubmit=e=>{e.preventDefault();try{const v=Object.fromEntries(new FormData(e.target)),t=v.time.split(':').map(Number);state=confirmProgress(state,{kind:v.kind,legIndex:Number(v.legIndex),confirmedSeconds:t[0]*3600+t[1]*60+(t[2]??0),walkedSeconds:Number(v.walk)});message='Progress confirmed and saved.';save();reassess();host.querySelector('#progress-summary').setAttribute('tabindex','-1');host.querySelector('#progress-summary').focus();}catch(error){status(error.message);}};
    host.querySelector('#reassess').onclick=reassess;
    host.querySelector('#demo-cancel').onclick=()=>{const leg=state.route.legs.slice(state.progress.legIndex).find(l=>l.type==='ride'&&l.mode==='rail');if(!getRouter(state?.input))return status('Routing data unavailable; saved instructions retained.');if(!leg)return status('No remaining planned rail trip in this journey.');const now=Date.now(),e={id:`demo:${leg.tripId}`,revision:(state.events.find(e=>e.id===`demo:${leg.tripId}`)?.revision??0)+1,evidence:'synthetic',effect:'cancelled',build:state.build,tripId:leg.tripId,routeId:leg.routeId,directionId:leg.directionId,serviceDate:leg.serviceDate,impactStartSeconds:leg.startSeconds,impactEndSeconds:leg.endSeconds,sourceTime:new Date(now).toISOString(),retrievedAt:new Date(now).toISOString(),validFrom:new Date(now-1000).toISOString(),validUntil:new Date(now+90000).toISOString()};state=ingestEvents(state,[e],getRouter(state?.input).network);save();reassess();};
    host.querySelector('#demo-recover').onclick=()=>{const old=state.events.at(-1);if(!getRouter(state?.input))return status('Routing data unavailable; saved instructions retained.');if(!old)return status('No synthetic event to recover.');const now=Date.now();state=ingestEvents(state,[{...old,revision:old.revision+1,effect:'recovered',sourceTime:new Date(now).toISOString(),retrievedAt:new Date(now).toISOString(),validFrom:new Date(now-1000).toISOString(),validUntil:new Date(now+90000).toISOString()}],getRouter(state?.input).network);save();reassess();};
    for(const [id,decision] of [['accept-change','accepted'],['decline-change','declined']])host.querySelector('#'+id)?.addEventListener('click',()=>{try{const fresh=compareJourney(state,getRouter(state?.input),Date.now(),navigator.onLine);if(fresh.key!==comparison.key||fresh.status!=='offer')throw Error('Conditions changed; compare again.');state=decide(state,fresh,decision);save();message=decision==='accepted'?'Alternative guidance accepted and saved.':'Recommendation declined; accepted guidance retained.';comparison=null;render();host.querySelector('#accepted-next').setAttribute('tabindex','-1');host.querySelector('#accepted-next').focus();}catch(e){status(e.message);}});
  }
  function health(){if(!feed)return navigator.onLine?'No request made. Server credential is optional for saved routing.':'Offline; no current feed. Saved routing remains available.';const n=feed.notices??{};return esc(`${navigator.onLine?'':'Offline · last-known only. '}Notices ${n.retrievedAt&&Date.now()-Date.parse(n.retrievedAt)>90000?'stale / '+n.status:n.status??'unavailable'} ${n.error??''}. Last successful retrieval ${n.retrievedAt??'none'} (${n.retrievedAt?Math.max(0,Math.floor((Date.now()-Date.parse(n.retrievedAt))/1000))+'s old':'age unknown'}). Source time ${n.sourceTime??'not supplied'}; validity ${n.expiresAt??'not supplied'}; retry ${n.nextRefreshAt??'on next manual request'}. ${(n.items??[]).length} advisory messages; no routing effect.`);}
  async function refresh(){if(pending||!navigator.onLine||Date.now()-lastAttempt<60000)return;pending=true;lastAttempt=Date.now();const epoch=++requestEpoch;render();try{const r=await fetch('/api/notices',{cache:'no-store',signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error('unavailable');const next=noticeSnapshot(await r.json());if(!next)throw Error('malformed');if(epoch===requestEpoch&&navigator.onLine&&newerSnapshot(feed,next)){feed=next;try{localStorage.setItem(FEED_KEY,JSON.stringify(feed));}catch{}}}catch{if(epoch===requestEpoch)feed={...feed,notices:{...feed?.notices,status:'unavailable',error:'network_or_malformed'}};}finally{if(epoch===requestEpoch){pending=false;reassess();render();}}}
  window.addEventListener('offline',()=>{clearTimeout(reconnectTimer);requestEpoch++;if(pending)lastAttempt=0;pending=false;comparison=null;render();});
  window.addEventListener('online',()=>{render();clearTimeout(reconnectTimer);const delay=Math.max(0,lastAttempt+60000-Date.now());if(delay)reconnectTimer=setTimeout(()=>{if(navigator.onLine)refresh();},delay);else refresh();});
  // Age display only; no background upstream polling and no focus-destroying render.
  setInterval(()=>{const el=host.querySelector('#journey-health');if(el)el.textContent=health().replaceAll('&amp;','&');if(comparison?.status==='offer'&&Date.now()-comparison.computedAt>90000){comparison=null;status('Comparison expired. Service state is unknown; reassess before switching.');}},10000);
  locationService.subscribe(syncLocationControls);
  render();return {render};
}
