import {createPersonalStore,resolvedPlace,instantiateTemplate,singaporeNow,swapEndpoints,visiblePersonalState} from './personal.js';
import {createAddressSearch} from './address-search.js';
import {mountDatePickers} from './date-picker.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const browserStorage=()=>{try{return globalThis.localStorage;}catch{return undefined;}};
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function mountPersonal({host,storage=browserStorage(),getPlan=()=>null,onSelectPlan=()=>{},onEndpoint=()=>{},places=[],showJourneys=true,addressSearch=createAddressSearch()}={}){
 const store=createPersonalStore(storage);let message='',edit=null,editTemplate=null,selection={origin:null,destination:null};
 let draft={label:'',query:'',candidate:null,source:''},results=[],searchStatus='',datePickers;
 const changed=()=>host.dispatchEvent(new CustomEvent('copilot:personal-changed',{bubbles:true}));
 const run=(fn,mutates=false)=>{try{fn();if(mutates)changed();}catch(e){message=e.message;}render();};
 function render(){
  datePickers?.destroy();
  addressSearch.cancel();
  const loaded=store.read(),all=loaded.state,state=visiblePersonalState(all),now=singaporeNow();
  const placeOptions=role=>state.places.map(p=>`<option value="${esc(p.id)}" ${selection[role]?.id===p.id?'selected':''}>${esc(p.label)}</option>`).join('');
  host.innerHTML=`<section aria-labelledby="saved-title"><h2 id="saved-title">${showJourneys?'Saved routes &amp; places':'Your places'}</h2><p>They are saved in this browser.</p><p role="status">${esc(message||loaded.error||'')}</p>
   <form id="place-add"><h3>Add a place</h3><label>Place name <input name="label" required maxlength="80" placeholder="Home, Work or Hospital" value="${esc(draft.label)}"></label>
   <label>Address or place in Singapore <input name="address" maxlength="160" autocomplete="off" placeholder="Street address, building or postcode" value="${esc(draft.query)}" aria-describedby="address-privacy"></label>
   <p class="field-note" id="address-privacy">Searching sends this address to Photon (Komoot), using OpenStreetMap data. Your place name stays here. Search runs only when you press Search addresses.</p>
   <button type="button" id="search-address">Search addresses</button><p id="address-status" role="status" aria-live="polite"></p><ul class="address-results" id="address-results" aria-label="Matching Singapore addresses"></ul>
   <details${draft.source?' open':''}><summary>Or choose a station</summary><label>Station <select name="source"><option value="">Choose a station</option>${places.map((p,i)=>`<option value="${i}" ${draft.source===String(i)?'selected':''}>${esc(p.label)}${p.entranceId?' · '+esc(p.entranceId):''}</option>`).join('')}</select></label></details>
   <p id="selected-address"></p><p class="field-note">An address can be saved even when a route to its door is unavailable. Step-free access is checked separately.</p><button type="submit" id="save-place" ${!draft.candidate?'disabled':''}>Save place on this device</button></form>
   <ol class="personal-list">${state.places.map((p,i)=>`<li><strong>${esc(p.label)}</strong><p>${esc(p.address??p.stationId??'Saved location')}${p.coverage==='supported'?' · Available in the route planner':' · Routes to this address are not yet available'}</p>${edit===p.id?`<form data-rename="${esc(p.id)}"><label>New place name <input name="label" value="${esc(p.label)}" required maxlength="80"></label><button>Save name</button></form>`:''}<button type="button" data-place="${esc(p.id)}" data-action="origin">Use as start</button> <button type="button" data-place="${esc(p.id)}" data-action="destination">Use as destination</button> <button type="button" data-place="${esc(p.id)}" data-action="rename">Rename</button> <button type="button" data-place="${esc(p.id)}" data-action="up" ${i===0?'disabled':''} aria-label="Move ${esc(p.label)} earlier">Move up</button> <button type="button" data-place="${esc(p.id)}" data-action="down" ${i===state.places.length-1?'disabled':''} aria-label="Move ${esc(p.label)} later">Move down</button> <button type="button" data-place="${esc(p.id)}" data-action="delete">Delete place</button></li>`).join('')||'<li>No places added yet. Search for an address above to add your first place.</li>'}</ol>
   ${showJourneys?`<details><summary>Save a frequent journey between your places</summary><form id="pair-add"><label>Journey name <input name="label" required maxlength="80"></label><label>Start <select name="originId" required><option value="">Choose saved place</option>${placeOptions('origin')}</select></label><label>Destination <select name="destinationId" required><option value="">Choose saved place</option>${placeOptions('destination')}</select></label><button type="button" id="swap-saved">Swap endpoints</button><label><input name="stepFree" type="checkbox" ${getPlan()?.preferences?.stepFree?'checked':''}> Require step-free access</label><label>Walking limit (minutes) <input name="walkingLimitMinutes" type="number" min="0" max="240" required value="${Number(getPlan()?.preferences?.walkingLimitMinutes??30)}"></label><button>Save Route</button></form></details>
   <h3>Your saved journeys</h3><p>Choose a date and time, then plan again to get fresh journey times.</p><label>Travel date <input type="date" id="saved-date" name="saved-date" value="${now.departureDate}"></label><label>Departure time <input type="time" id="saved-time" value="${now.departureTime}"></label><ol>${state.templates.map(t=>{const a=all.places.find(p=>p.id===t.originId),b=all.places.find(p=>p.id===t.destinationId);return `<li><strong>${esc(t.label)}</strong><p>${esc(a?.label??'Deleted start')} → ${esc(b?.label??'Deleted destination')}</p>${editTemplate===t.id?`<form data-template-rename="${esc(t.id)}"><label>New journey name <input name="label" value="${esc(t.label)}" required maxlength="80"></label><button>Save name</button></form>`:''}<button data-template="${esc(t.id)}" data-action="select" ${!a||!b?'disabled':''}>Plan with selected date &amp; time</button> <button data-template="${esc(t.id)}" data-action="rename">Rename journey</button> <button data-template="${esc(t.id)}" data-action="delete">Delete journey</button>${!a||!b?'<p>A place was deleted. Save a new journey with your current places.</p>':''}</li>`;}).join('')||'<li>No saved journeys yet. Save a route after searching in Plan.</li>'}</ol>`:''}
   <details><summary>Manage saved data</summary><button id="export-personal">Export saved places &amp; journeys</button><details><summary>Delete local saved places and routes</summary><p>This does not delete expenditure or sharing permissions.</p><label><input type="checkbox" id="delete-personal-confirm"> Delete my saved places and journeys</label><button id="clear-personal">Delete selected local data</button></details></details></section>`;
  datePickers=mountDatePickers(host);
  const add=host.querySelector('#place-add'),status=host.querySelector('#address-status'),resultList=host.querySelector('#address-results');
  function renderAddress(){
   status.textContent=searchStatus;
   resultList.innerHTML=results.map((p,i)=>`<li><button type="button" data-address="${i}" aria-pressed="${draft.candidate?.sourceId===p.sourceId}">${esc(p.address)}</button></li>`).join('');
   host.querySelector('#selected-address').textContent=draft.candidate?`Selected: ${draft.candidate.address??draft.candidate.label}`:'Choose a matching address or a station before saving.';
   host.querySelector('#save-place').disabled=!draft.candidate;
   for(const button of resultList.querySelectorAll('[data-address]'))button.onclick=()=>{draft.candidate=results[Number(button.dataset.address)];draft.source='';add.elements.source.value='';searchStatus='Address selected. Give this place a name and save it.';renderAddress();};
  }
  add.elements.label.oninput=()=>{draft.label=add.elements.label.value;};
  add.elements.address.oninput=()=>{addressSearch.cancel();draft.query=add.elements.address.value;draft.candidate=null;draft.source='';add.elements.source.value='';results=[];searchStatus='';renderAddress();};
  host.querySelector('#search-address').onclick=async()=>{
   draft.query=add.elements.address.value;draft.candidate=null;draft.source='';add.elements.source.value='';results=[];searchStatus='Searching Singapore addresses…';renderAddress();
   const query=draft.query;
   try{const matches=await addressSearch.search(query);if(matches===null||!add.isConnected||draft.query!==query)return;results=matches;searchStatus=matches.length?'Choose the address that matches your place.':'No matching Singapore addresses found. Try a building name, street address or postcode.';}
   catch(e){if(!add.isConnected||draft.query!==query)return;searchStatus=e.message;}
   renderAddress();
  };
  add.elements.address.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();host.querySelector('#search-address').click();}};
  add.elements.source.onchange=()=>{addressSearch.cancel();draft.source=add.elements.source.value;draft.candidate=draft.source===''?null:places[Number(draft.source)]??null;draft.query='';add.elements.address.value='';results=[];searchStatus='';renderAddress();};
  add.onsubmit=e=>{e.preventDefault();run(()=>{if(!draft.candidate)throw Error('Search for and select an address, or choose a station first.');store.addPlace(resolvedPlace({...draft.candidate,id:crypto.randomUUID(),label:add.elements.label.value}));draft={label:'',query:'',candidate:null,source:''};results=[];searchStatus='';message='Place saved. You can find it in Your places.';},true);};
  renderAddress();
  for(const button of host.querySelectorAll('[data-place]'))button.onclick=()=>run(()=>{
   const p=state.places.find(p=>p.id===button.dataset.place),action=button.dataset.action;
   if(action==='rename'){edit=p.id;return;}if(action==='delete'){store.deletePlace(p.id);message='Place deleted. Saved journeys using it will need a replacement.';changed();return;}
   if(['up','down'].includes(action)){const visibleIds=state.places.map(p=>p.id),index=visibleIds.indexOf(p.id),target=index+(action==='up'?-1:1),ids=all.places.map(p=>p.id),a=ids.indexOf(p.id),b=ids.indexOf(visibleIds[target]);if(b<0)return;[ids[a],ids[b]]=[ids[b],ids[a]];store.reorderPlaces(ids);message='Place order updated.';changed();return;}
   selection[action]=p;onEndpoint(action,p);message=`${p.label} selected as ${action==='origin'?'start':'destination'}.${p.coverage==='unknown'?' A route to this address is not yet available. Choose a station in Plan to search for a journey.':''}`;
  });
  for(const form of host.querySelectorAll('[data-rename]'))form.onsubmit=e=>{e.preventDefault();run(()=>{store.renamePlace(form.dataset.rename,new FormData(form).get('label'));edit=null;message='Place renamed.';},true);};
  const pair=host.querySelector('#pair-add');
  if(pair){host.querySelector('#swap-saved').onclick=()=>run(()=>{const a=state.places.find(p=>p.id===pair.elements.originId.value),b=state.places.find(p=>p.id===pair.elements.destinationId.value);if(!a||!b)throw Error('Choose both saved places first.');selection=swapEndpoints({origin:a,destination:b});onEndpoint('origin',selection.origin);onEndpoint('destination',selection.destination);message='Start and destination swapped.';});pair.onsubmit=e=>{e.preventDefault();run(()=>{const f=new FormData(pair);store.addTemplate({label:f.get('label'),originId:f.get('originId'),destinationId:f.get('destinationId'),preferences:{...getPlan()?.preferences,stepFree:f.get('stepFree')==='on',walkingLimitMinutes:Number(f.get('walkingLimitMinutes'))},timeMode:getPlan()?.timeMode,deadlineTime:getPlan()?.deadline,deadlineDate:getPlan()?.deadlineDate});message='Journey saved. Plan again from Your saved journeys for fresh journey times.';},true);};}
  for(const b of host.querySelectorAll('[data-template]'))b.onclick=()=>run(()=>{if(b.dataset.action==='rename'){editTemplate=b.dataset.template;return;}if(b.dataset.action==='delete'){store.deleteTemplate(b.dataset.template);message='Saved journey deleted.';changed();return;}const plan=instantiateTemplate(all,b.dataset.template,{departureDate:host.querySelector('#saved-date').value,departureTime:host.querySelector('#saved-time').value});onSelectPlan(plan);message='Journey selected in Plan. Search and review the route before starting.';});
  for(const f of host.querySelectorAll('[data-template-rename]'))f.onsubmit=e=>{e.preventDefault();run(()=>{store.renameTemplate(f.dataset.templateRename,new FormData(f).get('label'));editTemplate=null;message='Journey renamed.';},true);};
  host.querySelector('#export-personal').onclick=()=>run(()=>{download(store.export(),'commute-saved-places.json');message='Saved data exported, including preserved records from older versions.';});
  host.querySelector('#clear-personal').onclick=()=>run(()=>{if(!host.querySelector('#delete-personal-confirm').checked)throw Error('Select the deletion checkbox first.');store.clear();selection={origin:null,destination:null};message='Saved places and journeys deleted.';},true);
 }
 render();return {refresh:render,getState:()=>store.read(),store};
}
