import {restoreJourney} from './storage.js';
import {STATIONS} from './data.js';
import {normalizePreferences} from './preferences.js';
import {validateSavedPilot} from './pilot-validation.js';

export const PERSONAL_KEY='commute-copilot-personal-v2';
const copy=v=>structuredClone(v);
const id=()=>crypto.randomUUID();
const cleanLabel=value=>{if(typeof value!=='string'||!value.trim()||value.trim().length>80)throw Error('Use a name between 1 and 80 characters.');return value.trim();};
export function validPlace(p){return !!p&&typeof p.id==='string'&&p.id.length>0&&p.id.length<=150&&(p.routingId==null||typeof p.routingId==='string'&&p.routingId.length>0&&p.routingId.length<=150)&&typeof p.label==='string'&&p.label.trim().length>0&&p.label.length<=80&&Number.isFinite(p.lat)&&Math.abs(p.lat)<=90&&Number.isFinite(p.lng)&&Math.abs(p.lng)<=180&&typeof p.sourceId==='string'&&p.sourceId.length>0&&['supported','unknown'].includes(p.coverage)&&['unknown','verified-step-free'].includes(p.accessibility);}
export function resolvedPlace(value){const p={id:value.id??id(),label:cleanLabel(value.label),lat:value.lat,lng:value.lng,sourceId:value.sourceId,routingId:value.routingId??value.stationId??null,entranceId:value.entranceId??null,stationId:value.stationId??null,coverage:value.coverage??'unknown',accessibility:value.accessibility??'unknown'};if(!validPlace(p))throw Error('Select a resolved place or deliberately enter valid coordinates; an address name alone is not a verified location.');return p;}
export const emptyPersonal=()=>({schemaVersion:2,places:[],templates:[],migrations:[]});
const preferences=normalizePreferences;
const date=value=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value+'T00:00:00Z'))&&new Date(value+'T00:00:00Z').toISOString().slice(0,10)===value;
const clock=value=>typeof value==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(value);
function savedTiming(value={}){const deadline=value.deadlineTime??value.deadline??null,mode=value.timeMode??(deadline?'arrive-by':'leave-now');if(!['leave-now','depart-later','arrive-by'].includes(mode))throw Error('Choose a supported travel-time mode.');if(deadline&&!clock(deadline)||value.deadlineDate!=null&&!date(value.deadlineDate)||mode==='arrive-by'&&(!deadline||!date(value.deadlineDate)))throw Error('Choose the complete arrival deadline date and time.');return {timeMode:mode,deadlineTime:deadline||null,deadlineDate:deadline?value.deadlineDate??null:null};}
const distinctLabel=(label,rows)=>{const base=cleanLabel(label);let candidate=base,n=2;while(rows.some(row=>row.label.toLocaleLowerCase()===candidate.toLocaleLowerCase())){const suffix=` (${n++})`;candidate=base.slice(0,80-suffix.length)+suffix;}return candidate;};
function appendRoute(s,{label,origin,destination,preferences:p,...timing}) {
  const normalized=preferences(p),selection=savedTiming(timing);
  function endpoint(value){if(!value)throw Error('Choose two resolved endpoints first.');const candidate=resolvedPlace({...value,routingId:value.routingId??value.stationId??(value.coverage==='supported'?value.id:null)});let place=s.places.find(p=>p.id===candidate.id&&p.lat===candidate.lat&&p.lng===candidate.lng);if(!place)place=s.places.find(p=>p.lat===candidate.lat&&p.lng===candidate.lng&&p.entranceId===candidate.entranceId&&(candidate.routingId?p.routingId===candidate.routingId||p.stationId===candidate.routingId:p.sourceId===candidate.sourceId));if(!place){place={...candidate,id:id(),label:distinctLabel(candidate.label,s.places)};s.places.push(place);}return place;}
  const from=endpoint(origin),to=endpoint(destination);if(from.id===to.id)throw Error('Choose two different resolved endpoints.');
  s.templates.push({id:id(),label:distinctLabel(label||`${from.label} → ${to.label}`.slice(0,80),s.templates),originId:from.id,destinationId:to.id,preferences:normalized,...selection,savedAt:new Date().toISOString()});return s;
}
export function validatePersonal(v){if(!v||v.schemaVersion!==2||!Array.isArray(v.places)||!Array.isArray(v.templates)||!Array.isArray(v.migrations)||v.places.length>500||v.templates.length>500||v.places.some(p=>!validPlace(p))||new Set(v.places.map(p=>p.id)).size!==v.places.length||new Set(v.places.map(p=>p.label.toLocaleLowerCase())).size!==v.places.length)return null;for(const t of v.templates){if(!t||typeof t.id!=='string'||!t.id||typeof t.label!=='string'||!t.label.trim()||t.label.length>80||typeof t.originId!=='string'||typeof t.destinationId!=='string')return null;try{preferences(t.preferences);savedTiming(t);}catch{return null;}}if(new Set(v.templates.map(t=>t.id)).size!==v.templates.length)return null;return v;}
export function singaporeNow(now=Date.now()){const f=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});const p=Object.fromEntries(f.formatToParts(new Date(now)).map(x=>[x.type,x.value]));return {departureDate:`${p.year}-${p.month}-${p.day}`,departureTime:`${p.hour}:${p.minute}`};}
export function swapEndpoints(plan){return {...copy(plan),origin:copy(plan.destination),destination:copy(plan.origin),requiresRecheck:true,route:null};}
export function instantiateTemplate(state,templateId,when=singaporeNow()){const t=state.templates.find(t=>t.id===templateId);if(!t)throw Error('Saved journey no longer exists.');const origin=state.places.find(p=>p.id===t.originId),destination=state.places.find(p=>p.id===t.destinationId);if(!origin||!destination)throw Error('A place used by this journey was deleted. Save a new pair with available places.');const departureDate=when.departureDate??when.date,departureTime=when.departureTime??when.departure;if(!date(departureDate)||!clock(departureTime))throw Error('Choose a valid current travel date and time.');return {schemaVersion:2,templateId:t.id,origin:copy(origin),destination:copy(destination),preferences:preferences(t.preferences),departureDate,departureTime,...savedTiming({...t,...when}),timeZone:'Asia/Singapore',requiresRecheck:true,route:null};}
export function createPersonalStore(storage){
  function read(){try{const raw=storage.getItem(PERSONAL_KEY);if(raw===null)return {ok:true,state:emptyPersonal()};const state=validatePersonal(JSON.parse(raw));if(!state)throw Error();return {ok:true,state};}catch{return {ok:false,state:emptyPersonal(),error:'Saved places could not be read. Existing data has been preserved; export or repair browser storage before changing it.'};}}
  function commit(change){const current=read();if(!current.ok)throw Error(current.error);const next=change(copy(current.state));if(!validatePersonal(next))throw Error('Invalid saved-place change.');try{const raw=JSON.stringify(next);storage.setItem(PERSONAL_KEY,raw);if(storage.getItem(PERSONAL_KEY)!==raw)throw Error();}catch{throw Error('Could not save on this device. Browser storage may be full or blocked.');}return copy(next);}
  return {read,
    addPlace(value){return commit(s=>{const p=resolvedPlace(value);if(s.places.some(x=>x.id===p.id||x.label.toLocaleLowerCase()===p.label.toLocaleLowerCase()))throw Error('A place with that name or identifier already exists. Choose a distinct name.');s.places.push(p);return s;});},
    renamePlace(placeId,label){return commit(s=>{const p=s.places.find(p=>p.id===placeId);if(!p)throw Error('Place no longer exists.');const name=cleanLabel(label);if(s.places.some(x=>x.id!==placeId&&x.label.toLocaleLowerCase()===name.toLocaleLowerCase()))throw Error('A place with that name already exists.');p.label=name;return s;});},
    deletePlace(placeId){return commit(s=>({...s,places:s.places.filter(p=>p.id!==placeId)}));},
    reorderPlaces(ids){return commit(s=>{if(ids.length!==s.places.length||new Set(ids).size!==ids.length||ids.some(id=>!s.places.some(p=>p.id===id)))throw Error('The order must contain every saved place once.');s.places=ids.map(id=>s.places.find(p=>p.id===id));return s;});},
    addTemplate({label,originId,destinationId,preferences:p,...timing}){return commit(s=>{const name=cleanLabel(label);if(s.templates.some(t=>t.label.toLocaleLowerCase()===name.toLocaleLowerCase()))throw Error('A saved journey with that name already exists.');if(!s.places.some(p=>p.id===originId)||!s.places.some(p=>p.id===destinationId)||originId===destinationId)throw Error('Choose two different saved places.');s.templates.push({id:id(),label:name,originId,destinationId,preferences:preferences(p),...savedTiming(timing)});return s;});},
    saveRoute(value){return commit(s=>appendRoute(s,value));},
    renameTemplate(templateId,label){return commit(s=>{const t=s.templates.find(t=>t.id===templateId);if(!t)throw Error('Journey no longer exists.');const name=cleanLabel(label);if(s.templates.some(t=>t.id!==templateId&&t.label.toLocaleLowerCase()===name.toLocaleLowerCase()))throw Error('A saved journey with that name already exists.');t.label=name;return s;});},
    deleteTemplate(templateId){return commit(s=>({...s,templates:s.templates.filter(t=>t.id!==templateId)}));},
    migrateLegacy(){const legacy=restoreJourney(storage);if(!legacy)return read();const marker='validated-offline-v1';const initial=read();if(!initial.ok||initial.state.migrations.includes(marker))return initial;commit(s=>{const refs={};for(const role of ['origin','destination']){const key=legacy.input[role],station=STATIONS[key];if(!station)throw Error('Legacy endpoint is unresolved.');const stable='legacy-station:'+key;let p=s.places.find(p=>p.id===stable);if(!p){let label=station.name+' (legacy station)';if(s.places.some(p=>p.label.toLocaleLowerCase()===label.toLocaleLowerCase()))label+=' '+s.places.length;p=resolvedPlace({id:stable,label,lat:station.lat,lng:station.lng,stationId:station.code.split(' / ')[0],sourceId:'legacy:public/data/sources.json',coverage:'supported',accessibility:'unknown'});s.places.push(p);}refs[role]=p.id;}if(!s.templates.some(t=>t.id==='legacy-offline-template'))s.templates.push({id:'legacy-offline-template',label:'Imported offline journey',originId:refs.origin,destinationId:refs.destination,preferences:preferences(legacy.input)});s.migrations.push(marker);return s;});return read();},
    // Import reusable choices only. The caller resolves identities against the current
    // supported catalogue; no saved route geometry or accessibility claim is trusted.
    migratePlannerSnapshots(resolveEndpoint){
      if(typeof resolveEndpoint!=='function')return read();const initial=read();if(!initial.ok)return initial;
      for(const [key,label] of [['commute-copilot-rail-guidance-v1','Imported rail route'],['commute-copilot-pilot-guidance-v1','Imported bus and rail route']]) {
        const marker='route-input:'+key;if(read().state.migrations.includes(marker))continue;let snapshot,route;
        try{snapshot=JSON.parse(storage.getItem(key));const input=snapshot?.input;if(snapshot?.schemaVersion!==1||!Number.isFinite(Date.parse(snapshot.savedAt))||!input||!date(input.date)||!clock(input.departureTime)||typeof input.originId!=='string'||typeof input.destinationId!=='string')continue;if(key.includes('-pilot-guidance-')&&!validateSavedPilot(snapshot))continue;
          if(key.includes('-rail-guidance-')&&(!snapshot.network?.stations?.some(s=>s.id===input.originId)||!snapshot.network?.stations?.some(s=>s.id===input.destinationId)||snapshot.manifest?.schemaVersion!==1||!snapshot.route?.id||!Array.isArray(snapshot.route.legs)||!snapshot.route.legs.length))continue;
          route={label,origin:resolveEndpoint(input.originId),destination:resolveEndpoint(input.destinationId),preferences:preferences(input),...savedTiming({timeMode:input.timeMode??(input.deadlineTime?'arrive-by':'leave-now'),deadlineTime:input.deadlineTime,deadlineDate:input.deadlineTime?input.deadlineDate:null})};resolvedPlace(route.origin);resolvedPlace(route.destination);
        }catch{continue;}
        commit(s=>{if(s.migrations.includes(marker))return s;appendRoute(s,route);s.migrations.push(marker);return s;});
      }
      return read();
    },
    export(){const r=read();if(!r.ok)throw Error(r.error);return JSON.stringify(r.state,null,2);},
    clear(){try{storage.removeItem(PERSONAL_KEY);if(storage.getItem(PERSONAL_KEY)!==null)throw Error();return emptyPersonal();}catch{throw Error('Could not delete saved places from this browser.');}}
  };
}
