import {STATION_FACTS,stationFacts,INDOOR_COVERAGE} from './station-guidance-data.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function indoorNoticeHTML(execution){const notice=execution?.indoorNotice;return notice?`<aside class="indoor-guidance-notice ${notice.kind==='fixture'?'guidance-fixture':''}" aria-label="Indoor guidance coverage"><strong>${esc(notice.title)}</strong><p>${esc(notice.message)}</p><button type="button" class="secondary" data-open-station-guide>View station guide</button></aside>`:'';}
function factsHTML(item){return `<section class="station-fact-card"><h3>${esc(item.name)} <span>${esc(item.codes.join(' / '))}</span></h3><p class="field-note">${esc(item.scope)} · operator-documented locations</p><ul>${item.facts.map(f=>`<li><strong>${f.kind==='lift'?'Lifts':'Toilets'}:</strong> ${esc(f.text)}</li>`).join('')}</ul>${item.limitations.map(v=>`<p class="field-note">${esc(v)}</p>`).join('')}<a href="${esc(item.source.url)}" target="_blank" rel="noopener noreferrer">View ${esc(item.name)} operator information (opens a new tab)</a><p class="field-note">Desk reviewed ${esc(item.source.reviewedAt)}. Source update date not supplied; no field survey or live availability check.</p></section>`;}
export function stationGuidanceHTML(execution,{stationId=null}={}){
  const selected=stationFacts(stationId??execution?.stationId),context=selected?.name??execution?.stationLabel;
  return `<div class="station-guide-content"><h2>Station guide${context?` · ${esc(context)}`:''}</h2><aside class="indoor-guidance-notice"><strong>${INDOOR_COVERAGE.title}</strong><p>No verified real indoor corridor is available in this release. Use station signs and ask staff to confirm the entrance, gates, lift and platform route.</p></aside>${execution?.fixture?'<p class="guidance-fixture">Your accepted journey is a training rehearsal. Its diagram is fictional.</p>':''}<p>Operator location facts help you ask for assistance. They do not confirm a connected step-free path, a working lift, toilet opening hours, gate side or toilet accessibility.</p>${selected?factsHTML(selected):'<p>No reviewed operator location facts are retained for this station yet. This does not mean it has no lifts or toilets.</p>'}<details class="station-coverage-details"><summary>Other reviewed stations and coverage</summary>${STATION_FACTS.filter(s=>s!==selected).map(factsHTML).join('')}<p>The verified indoor pilot is awaiting permitted corridor evidence and a review of both directions. External station maps and announcements are not imported as route graphs.</p><p><a href="https://www.onemap.gov.sg/apidocs/bfa" target="_blank" rel="noopener noreferrer">OneMap barrier-free routing information</a> describes selected-area coverage and approved-user access. It does not establish this app’s indoor coverage.</p></details></div>`;
}
let pageId=0;
/** Swipe is intentionally confined to the labelled page-switch strip. It never
 * captures touches on the map, station content, buttons or vertical trip sheet. */
export function mountMapStationPages({host,mapPanel,stationPanel,getExecution=()=>null,onShowMap=()=>{}}){
  const id=`guidance-pages-${++pageId}`,strip=document.createElement('div');strip.className='guidance-page-strip';strip.setAttribute('aria-label','Swipe here to change between map and station guide');
  strip.innerHTML=`<div role="tablist" aria-label="Journey map pages"><button type="button" role="tab" id="${id}-map-tab" aria-controls="${id}-map" data-map-page="map">Map</button><button type="button" role="tab" id="${id}-station-tab" aria-controls="${id}-station" data-map-page="station">Station guide</button></div><span class="map-page-swipe-hint" aria-hidden="true">Swipe here or choose a page</span>`;
  host.prepend(strip);mapPanel.id ||= `${id}-map`;stationPanel.id ||= `${id}-station`;
  for(const [key,panel] of [['map',mapPanel],['station',stationPanel]]){panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby',`${id}-${key}-tab`);strip.querySelector(`[data-map-page="${key}"]`).setAttribute('aria-controls',panel.id);}
  let page='map',start=null;
  function show(next,{focus=false}={}){page=next==='station'?'station':'map';mapPanel.hidden=page!=='map';stationPanel.hidden=page!=='station';for(const button of strip.querySelectorAll('[role="tab"]')){const selected=button.dataset.mapPage===page;button.setAttribute('aria-selected',String(selected));button.tabIndex=selected?0:-1;if(selected&&focus)button.focus();}if(page==='station')stationPanel.innerHTML=stationGuidanceHTML(getExecution());else onShowMap();}
  for(const button of strip.querySelectorAll('[role="tab"]')){button.onclick=()=>show(button.dataset.mapPage);button.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();show(e.key==='Home'?'map':e.key==='End'?'station':page==='map'?'station':'map',{focus:true});}};}
  const down=e=>{if(e.isPrimary!==false&&e.pointerType!=='mouse'&&!e.target.closest('button'))start={x:e.clientX,y:e.clientY,id:e.pointerId};};
  const up=e=>{if(!start||start.id!==e.pointerId)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;if(Math.abs(dx)>=50&&Math.abs(dx)>Math.abs(dy)*1.8)show(dx<0?'station':'map');};
  const cancel=()=>{start=null;};strip.addEventListener('pointerdown',down);strip.addEventListener('pointerup',up);strip.addEventListener('pointercancel',cancel);
  const layout=()=>{const height=`${Math.ceil(strip.getBoundingClientRect().height)}px`;host.style.setProperty('--guidance-strip-height',height);host.parentElement?.style.setProperty('--guidance-strip-height',height);},observer=typeof ResizeObserver==='function'?new ResizeObserver(layout):null;observer?.observe(strip);layout();
  show('map');return {show,refresh(){if(page==='station')stationPanel.innerHTML=stationGuidanceHTML(getExecution());},getPage:()=>page,destroy(){observer?.disconnect();strip.removeEventListener('pointerdown',down);strip.removeEventListener('pointerup',up);strip.removeEventListener('pointercancel',cancel);strip.remove();host.style.removeProperty('--guidance-strip-height');host.parentElement?.style.removeProperty('--guidance-strip-height');mapPanel.hidden=false;stationPanel.hidden=true;}};
}
