// A touch-scroll picker supplements (never replaces) direct keyboard time entry.
export function mountTimePickers(form) {
  const dialog=document.createElement('dialog');dialog.className='time-dialog';dialog.setAttribute('aria-labelledby','time-picker-title');
  dialog.innerHTML='<form method="dialog"><h2 id="time-picker-title">Choose a time</h2><p>Singapore time · scroll each column or use arrow keys.</p><div class="time-wheels"><div class="time-wheel" role="listbox" aria-label="Hour"></div><div class="time-wheel" role="listbox" aria-label="Minute"></div></div><div class="field-pair"><button value="cancel" class="secondary">Cancel</button><button value="apply" class="primary">Use this time</button></div></form>';
  document.body.append(dialog);let target=null,chosen=[0,0],opening=false;const wheels=[...dialog.querySelectorAll('.time-wheel')];
  function select(index,value,{scroll=false}={}){chosen[index]=value;const wheel=wheels[index];[...wheel.children].forEach((b,i)=>{b.setAttribute('aria-selected',String(i===value));b.tabIndex=i===value?0:-1;});if(scroll)wheel.scrollTop=value*48;}
  wheels.forEach((wheel,index)=>{const count=index?60:24;for(let value=0;value<count;value++){const b=document.createElement('button');b.type='button';b.role='option';b.textContent=String(value).padStart(2,'0');b.onclick=()=>select(index,value,{scroll:true});b.onkeydown=e=>{if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?count-1:(chosen[index]+(e.key==='ArrowDown'?1:-1)+count)%count;select(index,next,{scroll:true});wheel.children[next].focus({preventScroll:true});}};wheel.append(b);}let timer;wheel.addEventListener('scroll',()=>{clearTimeout(timer);timer=setTimeout(()=>{if(!opening)select(index,Math.max(0,Math.min(count-1,Math.round(wheel.scrollTop/48))));},90);});});
  form.querySelectorAll('input[type=time]').forEach(input=>{const button=document.createElement('button');button.type='button';button.className='time-picker-button';button.textContent='Scroll to choose';button.setAttribute('aria-label',`Choose ${input.name==='departureTime'?'departure':'arrival'} time by scrolling`);input.after(button);button.onclick=()=>{target=input;const parts=(input.value||'12:00').split(':').map(Number);opening=true;dialog.showModal();requestAnimationFrame(()=>{parts.forEach((n,i)=>select(i,n,{scroll:true}));opening=false;wheels[0].children[parts[0]].focus({preventScroll:true});});};});
  dialog.addEventListener('close',()=>{if(dialog.returnValue==='apply'&&target){target.value=chosen.map(n=>String(n).padStart(2,'0')).join(':');target.dispatchEvent(new Event('change',{bubbles:true}));}target?.focus();});
}
